/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESCENEVIEWPORTTOOLBARFIELDS_H_
#define _KESCENEVIEWPORTTOOLBARFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SceneViewportToolbar;

OSG_GEN_CONTAINERPTR(SceneViewportToolbar);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SceneViewportToolbar *> :
    public FieldTraitsFCPtrBase<SceneViewportToolbar *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SceneViewportToolbar *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSceneViewportToolbarPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSceneViewportToolbarPtr"; }
};

template<> inline
const Char8 *FieldTraits<SceneViewportToolbar *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSceneViewportToolbarPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneViewportToolbar *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSceneViewportToolbarPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneViewportToolbar *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSceneViewportToolbarPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneViewportToolbar *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSceneViewportToolbarPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneViewportToolbar *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSceneViewportToolbarPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneViewportToolbar *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSceneViewportToolbarPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneViewportToolbar *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSceneViewportToolbarPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneViewportToolbar *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSceneViewportToolbarPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneViewportToolbar *,
                      RecordedRefCountPolicy  > SFRecSceneViewportToolbarPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneViewportToolbar *,
                      UnrecordedRefCountPolicy> SFUnrecSceneViewportToolbarPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneViewportToolbar *,
                      WeakRefCountPolicy      > SFWeakSceneViewportToolbarPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneViewportToolbar *,
                      NoRefCountPolicy        > SFUncountedSceneViewportToolbarPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneViewportToolbar *,
                      RecordedRefCountPolicy  > MFRecSceneViewportToolbarPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneViewportToolbar *,
                      UnrecordedRefCountPolicy> MFUnrecSceneViewportToolbarPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneViewportToolbar *,
                      WeakRefCountPolicy      > MFWeakSceneViewportToolbarPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneViewportToolbar *,
                      NoRefCountPolicy        > MFUncountedSceneViewportToolbarPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSceneViewportToolbarPtr : 
    public PointerSField<SceneViewportToolbar *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSceneViewportToolbarPtr : 
    public PointerSField<SceneViewportToolbar *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSceneViewportToolbarPtr :
    public PointerSField<SceneViewportToolbar *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSceneViewportToolbarPtr :
    public PointerSField<SceneViewportToolbar *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecSceneViewportToolbarPtr :
    public PointerMField<SceneViewportToolbar *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecSceneViewportToolbarPtr :
    public PointerMField<SceneViewportToolbar *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakSceneViewportToolbarPtr :
    public PointerMField<SceneViewportToolbar *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedSceneViewportToolbarPtr :
    public PointerMField<SceneViewportToolbar *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESCENEVIEWPORTTOOLBARFIELDS_H_ */
