/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                                                                           *
 *   contact: djkabala@gmail.com                                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class LuaGraphTreeModel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILELUAGRAPHTREEMODELINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "KELuaGraphTreeModelBase.h"
#include "KELuaGraphTreeModel.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  LuaGraphTreeModelBase::InternalRootFieldMask = 
    (TypeTraits<BitVector>::One << LuaGraphTreeModelBase::InternalRootFieldId);

const OSG::BitVector LuaGraphTreeModelBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var Path            LuaGraphTreeModelBase::_sfInternalRoot
    
*/

//! LuaGraphTreeModel description

FieldDescription *LuaGraphTreeModelBase::_desc[] = 
{
    new FieldDescription(SFPath::getClassType(), 
                     "InternalRoot", 
                     InternalRootFieldId, InternalRootFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&LuaGraphTreeModelBase::editSFInternalRoot))
};


FieldContainerType LuaGraphTreeModelBase::_type(
    "LuaGraphTreeModel",
    "AbstractTreeModel",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&LuaGraphTreeModelBase::createEmpty),
    LuaGraphTreeModel::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(LuaGraphTreeModelBase, LuaGraphTreeModelPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &LuaGraphTreeModelBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &LuaGraphTreeModelBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr LuaGraphTreeModelBase::shallowCopy(void) const 
{ 
    LuaGraphTreeModelPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const LuaGraphTreeModel *>(this)); 

    return returnValue; 
}

UInt32 LuaGraphTreeModelBase::getContainerSize(void) const 
{ 
    return sizeof(LuaGraphTreeModel); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void LuaGraphTreeModelBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<LuaGraphTreeModelBase *>(&other),
                          whichField);
}
#else
void LuaGraphTreeModelBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((LuaGraphTreeModelBase *) &other, whichField, sInfo);
}
void LuaGraphTreeModelBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void LuaGraphTreeModelBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

LuaGraphTreeModelBase::LuaGraphTreeModelBase(void) :
    _sfInternalRoot           (), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

LuaGraphTreeModelBase::LuaGraphTreeModelBase(const LuaGraphTreeModelBase &source) :
    _sfInternalRoot           (source._sfInternalRoot           ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

LuaGraphTreeModelBase::~LuaGraphTreeModelBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 LuaGraphTreeModelBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (InternalRootFieldMask & whichField))
    {
        returnValue += _sfInternalRoot.getBinSize();
    }


    return returnValue;
}

void LuaGraphTreeModelBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (InternalRootFieldMask & whichField))
    {
        _sfInternalRoot.copyToBin(pMem);
    }


}

void LuaGraphTreeModelBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (InternalRootFieldMask & whichField))
    {
        _sfInternalRoot.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void LuaGraphTreeModelBase::executeSyncImpl(      LuaGraphTreeModelBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (InternalRootFieldMask & whichField))
        _sfInternalRoot.syncWith(pOther->_sfInternalRoot);


}
#else
void LuaGraphTreeModelBase::executeSyncImpl(      LuaGraphTreeModelBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (InternalRootFieldMask & whichField))
        _sfInternalRoot.syncWith(pOther->_sfInternalRoot);



}

void LuaGraphTreeModelBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<LuaGraphTreeModelPtr>::_type("LuaGraphTreeModelPtr", "AbstractTreeModelPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(LuaGraphTreeModelPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(LuaGraphTreeModelPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

