/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEKESCENECOMPONENTTREECOMPONENTGENERATORFIELDS_H_
#define _KEKESCENECOMPONENTTREECOMPONENTGENERATORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SceneComponentTreeComponentGenerator;

OSG_GEN_CONTAINERPTR(SceneComponentTreeComponentGenerator);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SceneComponentTreeComponentGenerator *> :
    public FieldTraitsFCPtrBase<SceneComponentTreeComponentGenerator *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SceneComponentTreeComponentGenerator *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSceneComponentTreeComponentGeneratorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSceneComponentTreeComponentGeneratorPtr"; }
};

template<> inline
const Char8 *FieldTraits<SceneComponentTreeComponentGenerator *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSceneComponentTreeComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneComponentTreeComponentGenerator *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSceneComponentTreeComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneComponentTreeComponentGenerator *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSceneComponentTreeComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneComponentTreeComponentGenerator *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSceneComponentTreeComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneComponentTreeComponentGenerator *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSceneComponentTreeComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneComponentTreeComponentGenerator *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSceneComponentTreeComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneComponentTreeComponentGenerator *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSceneComponentTreeComponentGeneratorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneComponentTreeComponentGenerator *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSceneComponentTreeComponentGeneratorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneComponentTreeComponentGenerator *,
                      RecordedRefCountPolicy  > SFRecSceneComponentTreeComponentGeneratorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneComponentTreeComponentGenerator *,
                      UnrecordedRefCountPolicy> SFUnrecSceneComponentTreeComponentGeneratorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneComponentTreeComponentGenerator *,
                      WeakRefCountPolicy      > SFWeakSceneComponentTreeComponentGeneratorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneComponentTreeComponentGenerator *,
                      NoRefCountPolicy        > SFUncountedSceneComponentTreeComponentGeneratorPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneComponentTreeComponentGenerator *,
                      RecordedRefCountPolicy  > MFRecSceneComponentTreeComponentGeneratorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneComponentTreeComponentGenerator *,
                      UnrecordedRefCountPolicy> MFUnrecSceneComponentTreeComponentGeneratorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneComponentTreeComponentGenerator *,
                      WeakRefCountPolicy      > MFWeakSceneComponentTreeComponentGeneratorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneComponentTreeComponentGenerator *,
                      NoRefCountPolicy        > MFUncountedSceneComponentTreeComponentGeneratorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSceneComponentTreeComponentGeneratorPtr : 
    public PointerSField<SceneComponentTreeComponentGenerator *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSceneComponentTreeComponentGeneratorPtr : 
    public PointerSField<SceneComponentTreeComponentGenerator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSceneComponentTreeComponentGeneratorPtr :
    public PointerSField<SceneComponentTreeComponentGenerator *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSceneComponentTreeComponentGeneratorPtr :
    public PointerSField<SceneComponentTreeComponentGenerator *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecSceneComponentTreeComponentGeneratorPtr :
    public PointerMField<SceneComponentTreeComponentGenerator *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecSceneComponentTreeComponentGeneratorPtr :
    public PointerMField<SceneComponentTreeComponentGenerator *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakSceneComponentTreeComponentGeneratorPtr :
    public PointerMField<SceneComponentTreeComponentGenerator *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedSceneComponentTreeComponentGeneratorPtr :
    public PointerMField<SceneComponentTreeComponentGenerator *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEKESCENECOMPONENTTREECOMPONENTGENERATORFIELDS_H_ */
