/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESCENETREEMODELFIELDS_H_
#define _KESCENETREEMODELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SceneTreeModel;

OSG_GEN_CONTAINERPTR(SceneTreeModel);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SceneTreeModel *> :
    public FieldTraitsFCPtrBase<SceneTreeModel *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SceneTreeModel *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSceneTreeModelPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSceneTreeModelPtr"; }
};

template<> inline
const Char8 *FieldTraits<SceneTreeModel *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSceneTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneTreeModel *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSceneTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneTreeModel *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSceneTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneTreeModel *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSceneTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneTreeModel *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSceneTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneTreeModel *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSceneTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneTreeModel *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSceneTreeModelPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneTreeModel *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSceneTreeModelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneTreeModel *,
                      RecordedRefCountPolicy  > SFRecSceneTreeModelPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneTreeModel *,
                      UnrecordedRefCountPolicy> SFUnrecSceneTreeModelPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneTreeModel *,
                      WeakRefCountPolicy      > SFWeakSceneTreeModelPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneTreeModel *,
                      NoRefCountPolicy        > SFUncountedSceneTreeModelPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneTreeModel *,
                      RecordedRefCountPolicy  > MFRecSceneTreeModelPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneTreeModel *,
                      UnrecordedRefCountPolicy> MFUnrecSceneTreeModelPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneTreeModel *,
                      WeakRefCountPolicy      > MFWeakSceneTreeModelPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneTreeModel *,
                      NoRefCountPolicy        > MFUncountedSceneTreeModelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSceneTreeModelPtr : 
    public PointerSField<SceneTreeModel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSceneTreeModelPtr : 
    public PointerSField<SceneTreeModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSceneTreeModelPtr :
    public PointerSField<SceneTreeModel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSceneTreeModelPtr :
    public PointerSField<SceneTreeModel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecSceneTreeModelPtr :
    public PointerMField<SceneTreeModel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecSceneTreeModelPtr :
    public PointerMField<SceneTreeModel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakSceneTreeModelPtr :
    public PointerMField<SceneTreeModel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedSceneTreeModelPtr :
    public PointerMField<SceneTreeModel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESCENETREEMODELFIELDS_H_ */
