/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                                                                           *
 *   contact: djkabala@gmail.com                                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Scene!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILESCENEINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "KESceneBase.h"
#include "KEScene.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  SceneBase::InternalParentProjectFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::InternalParentProjectFieldId);

const OSG::BitVector  SceneBase::ViewportsFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::ViewportsFieldId);

const OSG::BitVector  SceneBase::BackgroundsFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::BackgroundsFieldId);

const OSG::BitVector  SceneBase::UIDrawingSurfacesFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::UIDrawingSurfacesFieldId);

const OSG::BitVector  SceneBase::InitialBackgroundFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::InitialBackgroundFieldId);

const OSG::BitVector  SceneBase::ForegroundsFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::ForegroundsFieldId);

const OSG::BitVector  SceneBase::InitialForegroundsFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::InitialForegroundsFieldId);

const OSG::BitVector  SceneBase::ModelNodesFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::ModelNodesFieldId);

const OSG::BitVector  SceneBase::InitialModelNodesFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::InitialModelNodesFieldId);

const OSG::BitVector  SceneBase::RootFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::RootFieldId);

const OSG::BitVector  SceneBase::RootCoreFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::RootCoreFieldId);

const OSG::BitVector  SceneBase::DefaultCameraBeaconFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::DefaultCameraBeaconFieldId);

const OSG::BitVector  SceneBase::DefaultCameraBeaconCoreFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::DefaultCameraBeaconCoreFieldId);

const OSG::BitVector  SceneBase::CamerasFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::CamerasFieldId);

const OSG::BitVector  SceneBase::InitialCameraFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::InitialCameraFieldId);

const OSG::BitVector  SceneBase::AnimationsFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::AnimationsFieldId);

const OSG::BitVector  SceneBase::InitialAnimationsFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::InitialAnimationsFieldId);

const OSG::BitVector  SceneBase::ParticleSystemsFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::ParticleSystemsFieldId);

const OSG::BitVector  SceneBase::InitialParticleSystemsFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::InitialParticleSystemsFieldId);

const OSG::BitVector  SceneBase::LuaModuleFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::LuaModuleFieldId);

const OSG::BitVector  SceneBase::PhysicsHandlerFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::PhysicsHandlerFieldId);

const OSG::BitVector  SceneBase::PhysicsWorldFieldMask = 
    (TypeTraits<BitVector>::One << SceneBase::PhysicsWorldFieldId);

const OSG::BitVector  SceneBase::EventProducerFieldMask =
    (TypeTraits<BitVector>::One << SceneBase::EventProducerFieldId);

const OSG::BitVector SceneBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var ProjectPtr      SceneBase::_sfInternalParentProject
    
*/
/*! \var ViewportPtr     SceneBase::_mfViewports
    
*/
/*! \var BackgroundPtr   SceneBase::_mfBackgrounds
    
*/
/*! \var UIDrawingSurfacePtr SceneBase::_mfUIDrawingSurfaces
    
*/
/*! \var BackgroundPtr   SceneBase::_sfInitialBackground
    
*/
/*! \var ForegroundPtr   SceneBase::_mfForegrounds
    
*/
/*! \var ForegroundPtr   SceneBase::_mfInitialForegrounds
    
*/
/*! \var NodePtr         SceneBase::_mfModelNodes
    
*/
/*! \var NodePtr         SceneBase::_mfInitialModelNodes
    
*/
/*! \var NodePtr         SceneBase::_sfRoot
    
*/
/*! \var TransformPtr    SceneBase::_sfRootCore
    
*/
/*! \var NodePtr         SceneBase::_sfDefaultCameraBeacon
    
*/
/*! \var TransformPtr    SceneBase::_sfDefaultCameraBeaconCore
    
*/
/*! \var CameraPtr       SceneBase::_mfCameras
    
*/
/*! \var CameraPtr       SceneBase::_sfInitialCamera
    
*/
/*! \var AnimationPtr    SceneBase::_mfAnimations
    
*/
/*! \var AnimationPtr    SceneBase::_mfInitialAnimations
    
*/
/*! \var ParticleSystemPtr SceneBase::_mfParticleSystems
    
*/
/*! \var ParticleSystemPtr SceneBase::_mfInitialParticleSystems
    
*/
/*! \var Path            SceneBase::_sfLuaModule
    
*/
/*! \var PhysicsHandlerPtr SceneBase::_sfPhysicsHandler
    
*/
/*! \var PhysicsWorldPtr SceneBase::_sfPhysicsWorld
    
*/

//! Scene description

FieldDescription *SceneBase::_desc[] = 
{
    new FieldDescription(SFProjectPtr::getClassType(), 
                     "InternalParentProject", 
                     InternalParentProjectFieldId, InternalParentProjectFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFInternalParentProject)),
    new FieldDescription(MFViewportPtr::getClassType(), 
                     "Viewports", 
                     ViewportsFieldId, ViewportsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFViewports)),
    new FieldDescription(MFBackgroundPtr::getClassType(), 
                     "Backgrounds", 
                     BackgroundsFieldId, BackgroundsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFBackgrounds)),
    new FieldDescription(MFUIDrawingSurfacePtr::getClassType(), 
                     "UIDrawingSurfaces", 
                     UIDrawingSurfacesFieldId, UIDrawingSurfacesFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFUIDrawingSurfaces)),
    new FieldDescription(SFBackgroundPtr::getClassType(), 
                     "InitialBackground", 
                     InitialBackgroundFieldId, InitialBackgroundFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFInitialBackground)),
    new FieldDescription(MFForegroundPtr::getClassType(), 
                     "Foregrounds", 
                     ForegroundsFieldId, ForegroundsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFForegrounds)),
    new FieldDescription(MFForegroundPtr::getClassType(), 
                     "InitialForegrounds", 
                     InitialForegroundsFieldId, InitialForegroundsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFInitialForegrounds)),
    new FieldDescription(MFNodePtr::getClassType(), 
                     "ModelNodes", 
                     ModelNodesFieldId, ModelNodesFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFModelNodes)),
    new FieldDescription(MFNodePtr::getClassType(), 
                     "InitialModelNodes", 
                     InitialModelNodesFieldId, InitialModelNodesFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFInitialModelNodes)),
    new FieldDescription(SFNodePtr::getClassType(), 
                     "Root", 
                     RootFieldId, RootFieldMask,
                     true,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFRoot)),
    new FieldDescription(SFTransformPtr::getClassType(), 
                     "RootCore", 
                     RootCoreFieldId, RootCoreFieldMask,
                     true,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFRootCore)),
    new FieldDescription(SFNodePtr::getClassType(), 
                     "DefaultCameraBeacon", 
                     DefaultCameraBeaconFieldId, DefaultCameraBeaconFieldMask,
                     true,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFDefaultCameraBeacon)),
    new FieldDescription(SFTransformPtr::getClassType(), 
                     "DefaultCameraBeaconCore", 
                     DefaultCameraBeaconCoreFieldId, DefaultCameraBeaconCoreFieldMask,
                     true,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFDefaultCameraBeaconCore)),
    new FieldDescription(MFCameraPtr::getClassType(), 
                     "Cameras", 
                     CamerasFieldId, CamerasFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFCameras)),
    new FieldDescription(SFCameraPtr::getClassType(), 
                     "InitialCamera", 
                     InitialCameraFieldId, InitialCameraFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFInitialCamera)),
    new FieldDescription(MFAnimationPtr::getClassType(), 
                     "Animations", 
                     AnimationsFieldId, AnimationsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFAnimations)),
    new FieldDescription(MFAnimationPtr::getClassType(), 
                     "InitialAnimations", 
                     InitialAnimationsFieldId, InitialAnimationsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFInitialAnimations)),
    new FieldDescription(MFParticleSystemPtr::getClassType(), 
                     "ParticleSystems", 
                     ParticleSystemsFieldId, ParticleSystemsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFParticleSystems)),
    new FieldDescription(MFParticleSystemPtr::getClassType(), 
                     "InitialParticleSystems", 
                     InitialParticleSystemsFieldId, InitialParticleSystemsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editMFInitialParticleSystems)),
    new FieldDescription(SFPath::getClassType(), 
                     "LuaModule", 
                     LuaModuleFieldId, LuaModuleFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFLuaModule)),
    new FieldDescription(SFPhysicsHandlerPtr::getClassType(), 
                     "PhysicsHandler", 
                     PhysicsHandlerFieldId, PhysicsHandlerFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFPhysicsHandler)),
    new FieldDescription(SFPhysicsWorldPtr::getClassType(), 
                     "PhysicsWorld", 
                     PhysicsWorldFieldId, PhysicsWorldFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFPhysicsWorld))
    , 
    new FieldDescription(SFEventProducerPtr::getClassType(), 
                     "EventProducer", 
                     EventProducerFieldId,EventProducerFieldMask,
                     true,
                     reinterpret_cast<FieldAccessMethod>(&SceneBase::editSFEventProducer))
};


FieldContainerType SceneBase::_type(
    "Scene",
    "AttachmentContainer",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&SceneBase::createEmpty),
    Scene::initMethod,
    _desc,
    sizeof(_desc));

//! Scene Produced Methods

MethodDescription *SceneBase::_methodDesc[] =
{
    new MethodDescription("SceneEntered", 
                     SceneEnteredMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("SceneExited", 
                     SceneExitedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("SceneStarted", 
                     SceneStartedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("SceneEnded", 
                     SceneEndedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("SceneReset", 
                     SceneResetMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("WindowOpened", 
                     WindowOpenedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("WindowClosing", 
                     WindowClosingMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("WindowClosed", 
                     WindowClosedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("WindowIconified", 
                     WindowIconifiedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("WindowDeiconified", 
                     WindowDeiconifiedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("WindowActivated", 
                     WindowActivatedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("WindowDeactivated", 
                     WindowDeactivatedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("WindowEntered", 
                     WindowEnteredMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("WindowExited", 
                     WindowExitedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("MouseClicked", 
                     MouseClickedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("MouseEntered", 
                     MouseEnteredMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("MouseExited", 
                     MouseExitedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("MousePressed", 
                     MousePressedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("MouseReleased", 
                     MouseReleasedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("MouseMoved", 
                     MouseMovedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("MouseDragged", 
                     MouseDraggedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("MouseWheelMoved", 
                     MouseWheelMovedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("KeyPressed", 
                     KeyPressedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("KeyReleased", 
                     KeyReleasedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("KeyTyped", 
                     KeyTypedMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod()),
    new MethodDescription("Update", 
                     UpdateMethodId, 
                     SFEventPtr::getClassType(),
                     FunctorAccessMethod())
};

EventProducerType SceneBase::_producerType(
    "SceneProducerType",
    "EventProducerType",
    NULL,
    InitEventProducerFunctor(),
    _methodDesc,
    sizeof(_methodDesc));
//OSG_FIELD_CONTAINER_DEF(SceneBase, ScenePtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &SceneBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &SceneBase::getType(void) const 
{
    return _type;
} 

const EventProducerType &SceneBase::getProducerType(void) const
{
    return _producerType;
}


FieldContainerPtr SceneBase::shallowCopy(void) const 
{ 
    ScenePtr returnValue; 

    newPtr(returnValue, dynamic_cast<const Scene *>(this)); 

    return returnValue; 
}

UInt32 SceneBase::getContainerSize(void) const 
{ 
    return sizeof(Scene); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void SceneBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<SceneBase *>(&other),
                          whichField);
}
#else
void SceneBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((SceneBase *) &other, whichField, sInfo);
}
void SceneBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void SceneBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

    _mfViewports.terminateShare(uiAspect, this->getContainerSize());
    _mfBackgrounds.terminateShare(uiAspect, this->getContainerSize());
    _mfUIDrawingSurfaces.terminateShare(uiAspect, this->getContainerSize());
    _mfForegrounds.terminateShare(uiAspect, this->getContainerSize());
    _mfInitialForegrounds.terminateShare(uiAspect, this->getContainerSize());
    _mfModelNodes.terminateShare(uiAspect, this->getContainerSize());
    _mfInitialModelNodes.terminateShare(uiAspect, this->getContainerSize());
    _mfCameras.terminateShare(uiAspect, this->getContainerSize());
    _mfAnimations.terminateShare(uiAspect, this->getContainerSize());
    _mfInitialAnimations.terminateShare(uiAspect, this->getContainerSize());
    _mfParticleSystems.terminateShare(uiAspect, this->getContainerSize());
    _mfInitialParticleSystems.terminateShare(uiAspect, this->getContainerSize());
}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

SceneBase::SceneBase(void) :
    _Producer(&getProducerType()),
    _sfInternalParentProject  (ProjectPtr(NullFC)), 
    _mfViewports              (), 
    _mfBackgrounds            (), 
    _mfUIDrawingSurfaces      (), 
    _sfInitialBackground      (BackgroundPtr(NullFC)), 
    _mfForegrounds            (), 
    _mfInitialForegrounds     (), 
    _mfModelNodes             (), 
    _mfInitialModelNodes      (), 
    _sfRoot                   (NodePtr(NullFC)), 
    _sfRootCore               (TransformPtr(NullFC)), 
    _sfDefaultCameraBeacon    (NodePtr(NullFC)), 
    _sfDefaultCameraBeaconCore(TransformPtr(NullFC)), 
    _mfCameras                (), 
    _sfInitialCamera          (CameraPtr(NullFC)), 
    _mfAnimations             (), 
    _mfInitialAnimations      (), 
    _mfParticleSystems        (), 
    _mfInitialParticleSystems (), 
    _sfLuaModule              (), 
    _sfPhysicsHandler         (PhysicsHandlerPtr(NullFC)), 
    _sfPhysicsWorld           (PhysicsWorldPtr(NullFC)), 
    _sfEventProducer(&_Producer),
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

SceneBase::SceneBase(const SceneBase &source) :
    _Producer(&source.getProducerType()),
    _sfInternalParentProject  (source._sfInternalParentProject  ), 
    _mfViewports              (source._mfViewports              ), 
    _mfBackgrounds            (source._mfBackgrounds            ), 
    _mfUIDrawingSurfaces      (source._mfUIDrawingSurfaces      ), 
    _sfInitialBackground      (source._sfInitialBackground      ), 
    _mfForegrounds            (source._mfForegrounds            ), 
    _mfInitialForegrounds     (source._mfInitialForegrounds     ), 
    _mfModelNodes             (source._mfModelNodes             ), 
    _mfInitialModelNodes      (source._mfInitialModelNodes      ), 
    _sfRoot                   (source._sfRoot                   ), 
    _sfRootCore               (source._sfRootCore               ), 
    _sfDefaultCameraBeacon    (source._sfDefaultCameraBeacon    ), 
    _sfDefaultCameraBeaconCore(source._sfDefaultCameraBeaconCore), 
    _mfCameras                (source._mfCameras                ), 
    _sfInitialCamera          (source._sfInitialCamera          ), 
    _mfAnimations             (source._mfAnimations             ), 
    _mfInitialAnimations      (source._mfInitialAnimations      ), 
    _mfParticleSystems        (source._mfParticleSystems        ), 
    _mfInitialParticleSystems (source._mfInitialParticleSystems ), 
    _sfLuaModule              (source._sfLuaModule              ), 
    _sfPhysicsHandler         (source._sfPhysicsHandler         ), 
    _sfPhysicsWorld           (source._sfPhysicsWorld           ), 
    _sfEventProducer(&_Producer),
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

SceneBase::~SceneBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 SceneBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (InternalParentProjectFieldMask & whichField))
    {
        returnValue += _sfInternalParentProject.getBinSize();
    }

    if(FieldBits::NoField != (ViewportsFieldMask & whichField))
    {
        returnValue += _mfViewports.getBinSize();
    }

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
    {
        returnValue += _mfBackgrounds.getBinSize();
    }

    if(FieldBits::NoField != (UIDrawingSurfacesFieldMask & whichField))
    {
        returnValue += _mfUIDrawingSurfaces.getBinSize();
    }

    if(FieldBits::NoField != (InitialBackgroundFieldMask & whichField))
    {
        returnValue += _sfInitialBackground.getBinSize();
    }

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
    {
        returnValue += _mfForegrounds.getBinSize();
    }

    if(FieldBits::NoField != (InitialForegroundsFieldMask & whichField))
    {
        returnValue += _mfInitialForegrounds.getBinSize();
    }

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
    {
        returnValue += _mfModelNodes.getBinSize();
    }

    if(FieldBits::NoField != (InitialModelNodesFieldMask & whichField))
    {
        returnValue += _mfInitialModelNodes.getBinSize();
    }

    if(FieldBits::NoField != (RootFieldMask & whichField))
    {
        returnValue += _sfRoot.getBinSize();
    }

    if(FieldBits::NoField != (RootCoreFieldMask & whichField))
    {
        returnValue += _sfRootCore.getBinSize();
    }

    if(FieldBits::NoField != (DefaultCameraBeaconFieldMask & whichField))
    {
        returnValue += _sfDefaultCameraBeacon.getBinSize();
    }

    if(FieldBits::NoField != (DefaultCameraBeaconCoreFieldMask & whichField))
    {
        returnValue += _sfDefaultCameraBeaconCore.getBinSize();
    }

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
    {
        returnValue += _mfCameras.getBinSize();
    }

    if(FieldBits::NoField != (InitialCameraFieldMask & whichField))
    {
        returnValue += _sfInitialCamera.getBinSize();
    }

    if(FieldBits::NoField != (AnimationsFieldMask & whichField))
    {
        returnValue += _mfAnimations.getBinSize();
    }

    if(FieldBits::NoField != (InitialAnimationsFieldMask & whichField))
    {
        returnValue += _mfInitialAnimations.getBinSize();
    }

    if(FieldBits::NoField != (ParticleSystemsFieldMask & whichField))
    {
        returnValue += _mfParticleSystems.getBinSize();
    }

    if(FieldBits::NoField != (InitialParticleSystemsFieldMask & whichField))
    {
        returnValue += _mfInitialParticleSystems.getBinSize();
    }

    if(FieldBits::NoField != (LuaModuleFieldMask & whichField))
    {
        returnValue += _sfLuaModule.getBinSize();
    }

    if(FieldBits::NoField != (PhysicsHandlerFieldMask & whichField))
    {
        returnValue += _sfPhysicsHandler.getBinSize();
    }

    if(FieldBits::NoField != (PhysicsWorldFieldMask & whichField))
    {
        returnValue += _sfPhysicsWorld.getBinSize();
    }

    if(FieldBits::NoField != (EventProducerFieldMask & whichField))
    {
        returnValue += _sfEventProducer.getBinSize();
    }


    return returnValue;
}

void SceneBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (InternalParentProjectFieldMask & whichField))
    {
        _sfInternalParentProject.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ViewportsFieldMask & whichField))
    {
        _mfViewports.copyToBin(pMem);
    }

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
    {
        _mfBackgrounds.copyToBin(pMem);
    }

    if(FieldBits::NoField != (UIDrawingSurfacesFieldMask & whichField))
    {
        _mfUIDrawingSurfaces.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InitialBackgroundFieldMask & whichField))
    {
        _sfInitialBackground.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
    {
        _mfForegrounds.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InitialForegroundsFieldMask & whichField))
    {
        _mfInitialForegrounds.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
    {
        _mfModelNodes.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InitialModelNodesFieldMask & whichField))
    {
        _mfInitialModelNodes.copyToBin(pMem);
    }

    if(FieldBits::NoField != (RootFieldMask & whichField))
    {
        _sfRoot.copyToBin(pMem);
    }

    if(FieldBits::NoField != (RootCoreFieldMask & whichField))
    {
        _sfRootCore.copyToBin(pMem);
    }

    if(FieldBits::NoField != (DefaultCameraBeaconFieldMask & whichField))
    {
        _sfDefaultCameraBeacon.copyToBin(pMem);
    }

    if(FieldBits::NoField != (DefaultCameraBeaconCoreFieldMask & whichField))
    {
        _sfDefaultCameraBeaconCore.copyToBin(pMem);
    }

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
    {
        _mfCameras.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InitialCameraFieldMask & whichField))
    {
        _sfInitialCamera.copyToBin(pMem);
    }

    if(FieldBits::NoField != (AnimationsFieldMask & whichField))
    {
        _mfAnimations.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InitialAnimationsFieldMask & whichField))
    {
        _mfInitialAnimations.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ParticleSystemsFieldMask & whichField))
    {
        _mfParticleSystems.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InitialParticleSystemsFieldMask & whichField))
    {
        _mfInitialParticleSystems.copyToBin(pMem);
    }

    if(FieldBits::NoField != (LuaModuleFieldMask & whichField))
    {
        _sfLuaModule.copyToBin(pMem);
    }

    if(FieldBits::NoField != (PhysicsHandlerFieldMask & whichField))
    {
        _sfPhysicsHandler.copyToBin(pMem);
    }

    if(FieldBits::NoField != (PhysicsWorldFieldMask & whichField))
    {
        _sfPhysicsWorld.copyToBin(pMem);
    }

    if(FieldBits::NoField != (EventProducerFieldMask & whichField))
    {
        _sfEventProducer.copyToBin(pMem);
    }


}

void SceneBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (InternalParentProjectFieldMask & whichField))
    {
        _sfInternalParentProject.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ViewportsFieldMask & whichField))
    {
        _mfViewports.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
    {
        _mfBackgrounds.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (UIDrawingSurfacesFieldMask & whichField))
    {
        _mfUIDrawingSurfaces.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InitialBackgroundFieldMask & whichField))
    {
        _sfInitialBackground.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
    {
        _mfForegrounds.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InitialForegroundsFieldMask & whichField))
    {
        _mfInitialForegrounds.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
    {
        _mfModelNodes.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InitialModelNodesFieldMask & whichField))
    {
        _mfInitialModelNodes.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (RootFieldMask & whichField))
    {
        _sfRoot.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (RootCoreFieldMask & whichField))
    {
        _sfRootCore.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (DefaultCameraBeaconFieldMask & whichField))
    {
        _sfDefaultCameraBeacon.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (DefaultCameraBeaconCoreFieldMask & whichField))
    {
        _sfDefaultCameraBeaconCore.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
    {
        _mfCameras.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InitialCameraFieldMask & whichField))
    {
        _sfInitialCamera.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (AnimationsFieldMask & whichField))
    {
        _mfAnimations.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InitialAnimationsFieldMask & whichField))
    {
        _mfInitialAnimations.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ParticleSystemsFieldMask & whichField))
    {
        _mfParticleSystems.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InitialParticleSystemsFieldMask & whichField))
    {
        _mfInitialParticleSystems.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (LuaModuleFieldMask & whichField))
    {
        _sfLuaModule.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (PhysicsHandlerFieldMask & whichField))
    {
        _sfPhysicsHandler.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (PhysicsWorldFieldMask & whichField))
    {
        _sfPhysicsWorld.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (EventProducerFieldMask & whichField))
    {
        _sfEventProducer.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void SceneBase::executeSyncImpl(      SceneBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (InternalParentProjectFieldMask & whichField))
        _sfInternalParentProject.syncWith(pOther->_sfInternalParentProject);

    if(FieldBits::NoField != (ViewportsFieldMask & whichField))
        _mfViewports.syncWith(pOther->_mfViewports);

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
        _mfBackgrounds.syncWith(pOther->_mfBackgrounds);

    if(FieldBits::NoField != (UIDrawingSurfacesFieldMask & whichField))
        _mfUIDrawingSurfaces.syncWith(pOther->_mfUIDrawingSurfaces);

    if(FieldBits::NoField != (InitialBackgroundFieldMask & whichField))
        _sfInitialBackground.syncWith(pOther->_sfInitialBackground);

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
        _mfForegrounds.syncWith(pOther->_mfForegrounds);

    if(FieldBits::NoField != (InitialForegroundsFieldMask & whichField))
        _mfInitialForegrounds.syncWith(pOther->_mfInitialForegrounds);

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
        _mfModelNodes.syncWith(pOther->_mfModelNodes);

    if(FieldBits::NoField != (InitialModelNodesFieldMask & whichField))
        _mfInitialModelNodes.syncWith(pOther->_mfInitialModelNodes);

    if(FieldBits::NoField != (RootFieldMask & whichField))
        _sfRoot.syncWith(pOther->_sfRoot);

    if(FieldBits::NoField != (RootCoreFieldMask & whichField))
        _sfRootCore.syncWith(pOther->_sfRootCore);

    if(FieldBits::NoField != (DefaultCameraBeaconFieldMask & whichField))
        _sfDefaultCameraBeacon.syncWith(pOther->_sfDefaultCameraBeacon);

    if(FieldBits::NoField != (DefaultCameraBeaconCoreFieldMask & whichField))
        _sfDefaultCameraBeaconCore.syncWith(pOther->_sfDefaultCameraBeaconCore);

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
        _mfCameras.syncWith(pOther->_mfCameras);

    if(FieldBits::NoField != (InitialCameraFieldMask & whichField))
        _sfInitialCamera.syncWith(pOther->_sfInitialCamera);

    if(FieldBits::NoField != (AnimationsFieldMask & whichField))
        _mfAnimations.syncWith(pOther->_mfAnimations);

    if(FieldBits::NoField != (InitialAnimationsFieldMask & whichField))
        _mfInitialAnimations.syncWith(pOther->_mfInitialAnimations);

    if(FieldBits::NoField != (ParticleSystemsFieldMask & whichField))
        _mfParticleSystems.syncWith(pOther->_mfParticleSystems);

    if(FieldBits::NoField != (InitialParticleSystemsFieldMask & whichField))
        _mfInitialParticleSystems.syncWith(pOther->_mfInitialParticleSystems);

    if(FieldBits::NoField != (LuaModuleFieldMask & whichField))
        _sfLuaModule.syncWith(pOther->_sfLuaModule);

    if(FieldBits::NoField != (PhysicsHandlerFieldMask & whichField))
        _sfPhysicsHandler.syncWith(pOther->_sfPhysicsHandler);

    if(FieldBits::NoField != (PhysicsWorldFieldMask & whichField))
        _sfPhysicsWorld.syncWith(pOther->_sfPhysicsWorld);

    if(FieldBits::NoField != (EventProducerFieldMask & whichField))
        _sfEventProducer.syncWith(pOther->_sfEventProducer);


}
#else
void SceneBase::executeSyncImpl(      SceneBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (InternalParentProjectFieldMask & whichField))
        _sfInternalParentProject.syncWith(pOther->_sfInternalParentProject);

    if(FieldBits::NoField != (InitialBackgroundFieldMask & whichField))
        _sfInitialBackground.syncWith(pOther->_sfInitialBackground);

    if(FieldBits::NoField != (RootFieldMask & whichField))
        _sfRoot.syncWith(pOther->_sfRoot);

    if(FieldBits::NoField != (RootCoreFieldMask & whichField))
        _sfRootCore.syncWith(pOther->_sfRootCore);

    if(FieldBits::NoField != (DefaultCameraBeaconFieldMask & whichField))
        _sfDefaultCameraBeacon.syncWith(pOther->_sfDefaultCameraBeacon);

    if(FieldBits::NoField != (DefaultCameraBeaconCoreFieldMask & whichField))
        _sfDefaultCameraBeaconCore.syncWith(pOther->_sfDefaultCameraBeaconCore);

    if(FieldBits::NoField != (InitialCameraFieldMask & whichField))
        _sfInitialCamera.syncWith(pOther->_sfInitialCamera);

    if(FieldBits::NoField != (LuaModuleFieldMask & whichField))
        _sfLuaModule.syncWith(pOther->_sfLuaModule);

    if(FieldBits::NoField != (PhysicsHandlerFieldMask & whichField))
        _sfPhysicsHandler.syncWith(pOther->_sfPhysicsHandler);

    if(FieldBits::NoField != (PhysicsWorldFieldMask & whichField))
        _sfPhysicsWorld.syncWith(pOther->_sfPhysicsWorld);


    if(FieldBits::NoField != (ViewportsFieldMask & whichField))
        _mfViewports.syncWith(pOther->_mfViewports, sInfo);

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
        _mfBackgrounds.syncWith(pOther->_mfBackgrounds, sInfo);

    if(FieldBits::NoField != (UIDrawingSurfacesFieldMask & whichField))
        _mfUIDrawingSurfaces.syncWith(pOther->_mfUIDrawingSurfaces, sInfo);

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
        _mfForegrounds.syncWith(pOther->_mfForegrounds, sInfo);

    if(FieldBits::NoField != (InitialForegroundsFieldMask & whichField))
        _mfInitialForegrounds.syncWith(pOther->_mfInitialForegrounds, sInfo);

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
        _mfModelNodes.syncWith(pOther->_mfModelNodes, sInfo);

    if(FieldBits::NoField != (InitialModelNodesFieldMask & whichField))
        _mfInitialModelNodes.syncWith(pOther->_mfInitialModelNodes, sInfo);

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
        _mfCameras.syncWith(pOther->_mfCameras, sInfo);

    if(FieldBits::NoField != (AnimationsFieldMask & whichField))
        _mfAnimations.syncWith(pOther->_mfAnimations, sInfo);

    if(FieldBits::NoField != (InitialAnimationsFieldMask & whichField))
        _mfInitialAnimations.syncWith(pOther->_mfInitialAnimations, sInfo);

    if(FieldBits::NoField != (ParticleSystemsFieldMask & whichField))
        _mfParticleSystems.syncWith(pOther->_mfParticleSystems, sInfo);

    if(FieldBits::NoField != (InitialParticleSystemsFieldMask & whichField))
        _mfInitialParticleSystems.syncWith(pOther->_mfInitialParticleSystems, sInfo);


}

void SceneBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

    if(FieldBits::NoField != (ViewportsFieldMask & whichField))
        _mfViewports.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
        _mfBackgrounds.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (UIDrawingSurfacesFieldMask & whichField))
        _mfUIDrawingSurfaces.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
        _mfForegrounds.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (InitialForegroundsFieldMask & whichField))
        _mfInitialForegrounds.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
        _mfModelNodes.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (InitialModelNodesFieldMask & whichField))
        _mfInitialModelNodes.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
        _mfCameras.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (AnimationsFieldMask & whichField))
        _mfAnimations.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (InitialAnimationsFieldMask & whichField))
        _mfInitialAnimations.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (ParticleSystemsFieldMask & whichField))
        _mfParticleSystems.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (InitialParticleSystemsFieldMask & whichField))
        _mfInitialParticleSystems.beginEdit(uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<ScenePtr>::_type("ScenePtr", "AttachmentContainerPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(ScenePtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(ScenePtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

