/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESCENEEVENTDETAILSFIELDS_H_
#define _KESCENEEVENTDETAILSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SceneEventDetails;

OSG_GEN_CONTAINERPTR(SceneEventDetails);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SceneEventDetails *> :
    public FieldTraitsFCPtrBase<SceneEventDetails *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SceneEventDetails *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSceneEventDetailsPtr"; }
};

template<> inline
const Char8 *FieldTraits<SceneEventDetails *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSceneEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEventDetails *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSceneEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEventDetails *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSceneEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEventDetails *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSceneEventDetailsPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEventDetails *,
                      RecordedRefCountPolicy  > SFRecSceneEventDetailsPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEventDetails *,
                      UnrecordedRefCountPolicy> SFUnrecSceneEventDetailsPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEventDetails *,
                      WeakRefCountPolicy      > SFWeakSceneEventDetailsPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEventDetails *,
                      NoRefCountPolicy        > SFUncountedSceneEventDetailsPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSceneEventDetailsPtr : 
    public PointerSField<SceneEventDetails *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSceneEventDetailsPtr : 
    public PointerSField<SceneEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSceneEventDetailsPtr :
    public PointerSField<SceneEventDetails *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSceneEventDetailsPtr :
    public PointerSField<SceneEventDetails *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESCENEEVENTDETAILSFIELDS_H_ */
