/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESCENEFIELDS_H_
#define _KESCENEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class Scene;

OSG_GEN_CONTAINERPTR(Scene);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<Scene *> :
    public FieldTraitsFCPtrBase<Scene *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<Scene *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFScenePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFScenePtr"; }
};

template<> inline
const Char8 *FieldTraits<Scene *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecScenePtr"; 
}

template<> inline
const Char8 *FieldTraits<Scene *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecScenePtr"; 
}

template<> inline
const Char8 *FieldTraits<Scene *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakScenePtr"; 
}

template<> inline
const Char8 *FieldTraits<Scene *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdScenePtr"; 
}

template<> inline
const Char8 *FieldTraits<Scene *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecScenePtr"; 
}

template<> inline
const Char8 *FieldTraits<Scene *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecScenePtr"; 
}

template<> inline
const Char8 *FieldTraits<Scene *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakScenePtr"; 
}

template<> inline
const Char8 *FieldTraits<Scene *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdScenePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<Scene *,
                      RecordedRefCountPolicy  > SFRecScenePtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<Scene *,
                      UnrecordedRefCountPolicy> SFUnrecScenePtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<Scene *,
                      WeakRefCountPolicy      > SFWeakScenePtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<Scene *,
                      NoRefCountPolicy        > SFUncountedScenePtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<Scene *,
                      RecordedRefCountPolicy  > MFRecScenePtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<Scene *,
                      UnrecordedRefCountPolicy> MFUnrecScenePtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<Scene *,
                      WeakRefCountPolicy      > MFWeakScenePtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<Scene *,
                      NoRefCountPolicy        > MFUncountedScenePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecScenePtr : 
    public PointerSField<Scene *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecScenePtr : 
    public PointerSField<Scene *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakScenePtr :
    public PointerSField<Scene *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedScenePtr :
    public PointerSField<Scene *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecScenePtr :
    public PointerMField<Scene *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecScenePtr :
    public PointerMField<Scene *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakScenePtr :
    public PointerMField<Scene *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedScenePtr :
    public PointerMField<Scene *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESCENEFIELDS_H_ */
