/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESCENEEVENTFIELDS_H_
#define _KESCENEEVENTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SceneEvent;

OSG_GEN_CONTAINERPTR(SceneEvent);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SceneEvent *> :
    public FieldTraitsFCPtrBase<SceneEvent *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SceneEvent *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSceneEventPtr"; }
};

template<> inline
const Char8 *FieldTraits<SceneEvent *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSceneEventPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEvent *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSceneEventPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEvent *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSceneEventPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEvent *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSceneEventPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEvent *,
                      RecordedRefCountPolicy  > SFRecSceneEventPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEvent *,
                      UnrecordedRefCountPolicy> SFUnrecSceneEventPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEvent *,
                      WeakRefCountPolicy      > SFWeakSceneEventPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEvent *,
                      NoRefCountPolicy        > SFUncountedSceneEventPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSceneEventPtr : 
    public PointerSField<SceneEvent *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSceneEventPtr : 
    public PointerSField<SceneEvent *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSceneEventPtr :
    public PointerSField<SceneEvent *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSceneEventPtr :
    public PointerSField<SceneEvent *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESCENEEVENTFIELDS_H_ */
