/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEPARTICLESYSTEMEDITORFIELDS_H_
#define _KEPARTICLESYSTEMEDITORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class ParticleSystemEditor;

OSG_GEN_CONTAINERPTR(ParticleSystemEditor);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<ParticleSystemEditor *> :
    public FieldTraitsFCPtrBase<ParticleSystemEditor *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ParticleSystemEditor *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFParticleSystemEditorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFParticleSystemEditorPtr"; }
};

template<> inline
const Char8 *FieldTraits<ParticleSystemEditor *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecParticleSystemEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleSystemEditor *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecParticleSystemEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleSystemEditor *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakParticleSystemEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleSystemEditor *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdParticleSystemEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleSystemEditor *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecParticleSystemEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleSystemEditor *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecParticleSystemEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleSystemEditor *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakParticleSystemEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<ParticleSystemEditor *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdParticleSystemEditorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ParticleSystemEditor *,
                      RecordedRefCountPolicy  > SFRecParticleSystemEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ParticleSystemEditor *,
                      UnrecordedRefCountPolicy> SFUnrecParticleSystemEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ParticleSystemEditor *,
                      WeakRefCountPolicy      > SFWeakParticleSystemEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ParticleSystemEditor *,
                      NoRefCountPolicy        > SFUncountedParticleSystemEditorPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ParticleSystemEditor *,
                      RecordedRefCountPolicy  > MFRecParticleSystemEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ParticleSystemEditor *,
                      UnrecordedRefCountPolicy> MFUnrecParticleSystemEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ParticleSystemEditor *,
                      WeakRefCountPolicy      > MFWeakParticleSystemEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ParticleSystemEditor *,
                      NoRefCountPolicy        > MFUncountedParticleSystemEditorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecParticleSystemEditorPtr : 
    public PointerSField<ParticleSystemEditor *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecParticleSystemEditorPtr : 
    public PointerSField<ParticleSystemEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakParticleSystemEditorPtr :
    public PointerSField<ParticleSystemEditor *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedParticleSystemEditorPtr :
    public PointerSField<ParticleSystemEditor *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecParticleSystemEditorPtr :
    public PointerMField<ParticleSystemEditor *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecParticleSystemEditorPtr :
    public PointerMField<ParticleSystemEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakParticleSystemEditorPtr :
    public PointerMField<ParticleSystemEditor *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedParticleSystemEditorPtr :
    public PointerMField<ParticleSystemEditor *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEPARTICLESYSTEMEDITORFIELDS_H_ */
