/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ParticleSystemEditor!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>




#include "KEParticleSystemEditorBase.h"
#include "KEParticleSystemEditor.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ParticleSystemEditor
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<ParticleSystemEditor *>::_type("ParticleSystemEditorPtr", "EditorInterfacePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(ParticleSystemEditor *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ParticleSystemEditor *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ParticleSystemEditor *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ParticleSystemEditorBase::classDescInserter(TypeObject &oType)
{
}


ParticleSystemEditorBase::TypeObject ParticleSystemEditorBase::_type(
    ParticleSystemEditorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&ParticleSystemEditorBase::createEmptyLocal),
    ParticleSystemEditor::initMethod,
    ParticleSystemEditor::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ParticleSystemEditor::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"ParticleSystemEditor\"\n"
    "\tparent=\"EditorInterface\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ParticleSystemEditorBase::getType(void)
{
    return _type;
}

const FieldContainerType &ParticleSystemEditorBase::getType(void) const
{
    return _type;
}

UInt32 ParticleSystemEditorBase::getContainerSize(void) const
{
    return sizeof(ParticleSystemEditor);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 ParticleSystemEditorBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void ParticleSystemEditorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void ParticleSystemEditorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
ParticleSystemEditorTransitPtr ParticleSystemEditorBase::createLocal(BitVector bFlags)
{
    ParticleSystemEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ParticleSystemEditor>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ParticleSystemEditorTransitPtr ParticleSystemEditorBase::createDependent(BitVector bFlags)
{
    ParticleSystemEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ParticleSystemEditor>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ParticleSystemEditorTransitPtr ParticleSystemEditorBase::create(void)
{
    ParticleSystemEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ParticleSystemEditor>(tmpPtr);
    }

    return fc;
}

ParticleSystemEditor *ParticleSystemEditorBase::createEmptyLocal(BitVector bFlags)
{
    ParticleSystemEditor *returnValue;

    newPtr<ParticleSystemEditor>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ParticleSystemEditor *ParticleSystemEditorBase::createEmpty(void)
{
    ParticleSystemEditor *returnValue;

    newPtr<ParticleSystemEditor>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ParticleSystemEditorBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ParticleSystemEditor *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ParticleSystemEditor *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ParticleSystemEditorBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ParticleSystemEditor *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ParticleSystemEditor *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ParticleSystemEditorBase::shallowCopy(void) const
{
    ParticleSystemEditor *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ParticleSystemEditor *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

ParticleSystemEditorBase::ParticleSystemEditorBase(void) :
    Inherited()
{
}

ParticleSystemEditorBase::ParticleSystemEditorBase(const ParticleSystemEditorBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ParticleSystemEditorBase::~ParticleSystemEditorBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void ParticleSystemEditorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ParticleSystemEditor *pThis = static_cast<ParticleSystemEditor *>(this);

    pThis->execSync(static_cast<ParticleSystemEditor *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ParticleSystemEditorBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ParticleSystemEditor *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ParticleSystemEditor *>(pRefAspect),
                  dynamic_cast<const ParticleSystemEditor *>(this));

    return returnValue;
}
#endif

void ParticleSystemEditorBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
