/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                                                                           *
 *   contact: djkabala@gmail.com                                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Behavior!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILEBEHAVIORINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "KEBehaviorBase.h"
#include "KEBehavior.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  BehaviorBase::SceneObjectFieldMask = 
    (TypeTraits<BitVector>::One << BehaviorBase::SceneObjectFieldId);

const OSG::BitVector  BehaviorBase::DependenciesFieldMask = 
    (TypeTraits<BitVector>::One << BehaviorBase::DependenciesFieldId);

const OSG::BitVector BehaviorBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var SceneObjectPtr  BehaviorBase::_sfSceneObject
    
*/
/*! \var std::string     BehaviorBase::_mfDependencies
    
*/

//! Behavior description

FieldDescription *BehaviorBase::_desc[] = 
{
    new FieldDescription(SFSceneObjectPtr::getClassType(), 
                     "SceneObject", 
                     SceneObjectFieldId, SceneObjectFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&BehaviorBase::editSFSceneObject)),
    new FieldDescription(MFString::getClassType(), 
                     "Dependencies", 
                     DependenciesFieldId, DependenciesFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&BehaviorBase::editMFDependencies))
};


FieldContainerType BehaviorBase::_type(
    "Behavior",
    "AttachmentContainer",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&BehaviorBase::createEmpty),
    Behavior::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(BehaviorBase, BehaviorPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &BehaviorBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &BehaviorBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr BehaviorBase::shallowCopy(void) const 
{ 
    BehaviorPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const Behavior *>(this)); 

    return returnValue; 
}

UInt32 BehaviorBase::getContainerSize(void) const 
{ 
    return sizeof(Behavior); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void BehaviorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<BehaviorBase *>(&other),
                          whichField);
}
#else
void BehaviorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((BehaviorBase *) &other, whichField, sInfo);
}
void BehaviorBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void BehaviorBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

    _mfDependencies.terminateShare(uiAspect, this->getContainerSize());
}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

BehaviorBase::BehaviorBase(void) :
    _sfSceneObject            (), 
    _mfDependencies           (), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

BehaviorBase::BehaviorBase(const BehaviorBase &source) :
    _sfSceneObject            (source._sfSceneObject            ), 
    _mfDependencies           (source._mfDependencies           ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

BehaviorBase::~BehaviorBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 BehaviorBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (SceneObjectFieldMask & whichField))
    {
        returnValue += _sfSceneObject.getBinSize();
    }

    if(FieldBits::NoField != (DependenciesFieldMask & whichField))
    {
        returnValue += _mfDependencies.getBinSize();
    }


    return returnValue;
}

void BehaviorBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (SceneObjectFieldMask & whichField))
    {
        _sfSceneObject.copyToBin(pMem);
    }

    if(FieldBits::NoField != (DependenciesFieldMask & whichField))
    {
        _mfDependencies.copyToBin(pMem);
    }


}

void BehaviorBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (SceneObjectFieldMask & whichField))
    {
        _sfSceneObject.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (DependenciesFieldMask & whichField))
    {
        _mfDependencies.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void BehaviorBase::executeSyncImpl(      BehaviorBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (SceneObjectFieldMask & whichField))
        _sfSceneObject.syncWith(pOther->_sfSceneObject);

    if(FieldBits::NoField != (DependenciesFieldMask & whichField))
        _mfDependencies.syncWith(pOther->_mfDependencies);


}
#else
void BehaviorBase::executeSyncImpl(      BehaviorBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (SceneObjectFieldMask & whichField))
        _sfSceneObject.syncWith(pOther->_sfSceneObject);


    if(FieldBits::NoField != (DependenciesFieldMask & whichField))
        _mfDependencies.syncWith(pOther->_mfDependencies, sInfo);


}

void BehaviorBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

    if(FieldBits::NoField != (DependenciesFieldMask & whichField))
        _mfDependencies.beginEdit(uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<BehaviorPtr>::_type("BehaviorPtr", "AttachmentContainerPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(BehaviorPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(BehaviorPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

