/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                                                                           *
 *   contact: djkabala@gmail.com                                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class CapabilityFactory!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILECAPABILITYFACTORYINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "KECapabilityFactoryBase.h"
#include "KECapabilityFactory.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  CapabilityFactoryBase::CapabilityTypesFieldMask = 
    (TypeTraits<BitVector>::One << CapabilityFactoryBase::CapabilityTypesFieldId);

const OSG::BitVector CapabilityFactoryBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var CapabilityTypePtr CapabilityFactoryBase::_mfCapabilityTypes
    
*/

//! CapabilityFactory description

FieldDescription *CapabilityFactoryBase::_desc[] = 
{
    new FieldDescription(MFCapabilityTypePtr::getClassType(), 
                     "CapabilityTypes", 
                     CapabilityTypesFieldId, CapabilityTypesFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&CapabilityFactoryBase::editMFCapabilityTypes))
};


FieldContainerType CapabilityFactoryBase::_type(
    "CapabilityFactory",
    "AttachmentContainer",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&CapabilityFactoryBase::createEmpty),
    CapabilityFactory::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(CapabilityFactoryBase, CapabilityFactoryPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &CapabilityFactoryBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &CapabilityFactoryBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr CapabilityFactoryBase::shallowCopy(void) const 
{ 
    CapabilityFactoryPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const CapabilityFactory *>(this)); 

    return returnValue; 
}

UInt32 CapabilityFactoryBase::getContainerSize(void) const 
{ 
    return sizeof(CapabilityFactory); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void CapabilityFactoryBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<CapabilityFactoryBase *>(&other),
                          whichField);
}
#else
void CapabilityFactoryBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((CapabilityFactoryBase *) &other, whichField, sInfo);
}
void CapabilityFactoryBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void CapabilityFactoryBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

    _mfCapabilityTypes.terminateShare(uiAspect, this->getContainerSize());
}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

CapabilityFactoryBase::CapabilityFactoryBase(void) :
    _mfCapabilityTypes        (), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

CapabilityFactoryBase::CapabilityFactoryBase(const CapabilityFactoryBase &source) :
    _mfCapabilityTypes        (source._mfCapabilityTypes        ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

CapabilityFactoryBase::~CapabilityFactoryBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 CapabilityFactoryBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (CapabilityTypesFieldMask & whichField))
    {
        returnValue += _mfCapabilityTypes.getBinSize();
    }


    return returnValue;
}

void CapabilityFactoryBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (CapabilityTypesFieldMask & whichField))
    {
        _mfCapabilityTypes.copyToBin(pMem);
    }


}

void CapabilityFactoryBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (CapabilityTypesFieldMask & whichField))
    {
        _mfCapabilityTypes.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void CapabilityFactoryBase::executeSyncImpl(      CapabilityFactoryBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (CapabilityTypesFieldMask & whichField))
        _mfCapabilityTypes.syncWith(pOther->_mfCapabilityTypes);


}
#else
void CapabilityFactoryBase::executeSyncImpl(      CapabilityFactoryBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);


    if(FieldBits::NoField != (CapabilityTypesFieldMask & whichField))
        _mfCapabilityTypes.syncWith(pOther->_mfCapabilityTypes, sInfo);


}

void CapabilityFactoryBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

    if(FieldBits::NoField != (CapabilityTypesFieldMask & whichField))
        _mfCapabilityTypes.beginEdit(uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<CapabilityFactoryPtr>::_type("CapabilityFactoryPtr", "AttachmentContainerPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(CapabilityFactoryPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(CapabilityFactoryPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

