/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com), Eric Langkamp              *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KELUABEHAVIORFIELDS_H_
#define _KELUABEHAVIORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class LuaBehavior;

OSG_GEN_CONTAINERPTR(LuaBehavior);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<LuaBehavior *> :
    public FieldTraitsFCPtrBase<LuaBehavior *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<LuaBehavior *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFLuaBehaviorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFLuaBehaviorPtr"; }
};

template<> inline
const Char8 *FieldTraits<LuaBehavior *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecLuaBehaviorPtr"; 
}

template<> inline
const Char8 *FieldTraits<LuaBehavior *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecLuaBehaviorPtr"; 
}

template<> inline
const Char8 *FieldTraits<LuaBehavior *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakLuaBehaviorPtr"; 
}

template<> inline
const Char8 *FieldTraits<LuaBehavior *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdLuaBehaviorPtr"; 
}

template<> inline
const Char8 *FieldTraits<LuaBehavior *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecLuaBehaviorPtr"; 
}

template<> inline
const Char8 *FieldTraits<LuaBehavior *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecLuaBehaviorPtr"; 
}

template<> inline
const Char8 *FieldTraits<LuaBehavior *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakLuaBehaviorPtr"; 
}

template<> inline
const Char8 *FieldTraits<LuaBehavior *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdLuaBehaviorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<LuaBehavior *,
                      RecordedRefCountPolicy  > SFRecLuaBehaviorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<LuaBehavior *,
                      UnrecordedRefCountPolicy> SFUnrecLuaBehaviorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<LuaBehavior *,
                      WeakRefCountPolicy      > SFWeakLuaBehaviorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<LuaBehavior *,
                      NoRefCountPolicy        > SFUncountedLuaBehaviorPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<LuaBehavior *,
                      RecordedRefCountPolicy  > MFRecLuaBehaviorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<LuaBehavior *,
                      UnrecordedRefCountPolicy> MFUnrecLuaBehaviorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<LuaBehavior *,
                      WeakRefCountPolicy      > MFWeakLuaBehaviorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<LuaBehavior *,
                      NoRefCountPolicy        > MFUncountedLuaBehaviorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecLuaBehaviorPtr : 
    public PointerSField<LuaBehavior *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecLuaBehaviorPtr : 
    public PointerSField<LuaBehavior *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakLuaBehaviorPtr :
    public PointerSField<LuaBehavior *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedLuaBehaviorPtr :
    public PointerSField<LuaBehavior *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecLuaBehaviorPtr :
    public PointerMField<LuaBehavior *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecLuaBehaviorPtr :
    public PointerMField<LuaBehavior *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakLuaBehaviorPtr :
    public PointerMField<LuaBehavior *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedLuaBehaviorPtr :
    public PointerMField<LuaBehavior *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KELUABEHAVIORFIELDS_H_ */
