/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com), Eric Langkamp             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESCENEOBJECTFIELDS_H_
#define _KESCENEOBJECTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SceneObject;

OSG_GEN_CONTAINERPTR(SceneObject);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SceneObject *> :
    public FieldTraitsFCPtrBase<SceneObject *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SceneObject *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSceneObjectPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSceneObjectPtr"; }
};

template<> inline
const Char8 *FieldTraits<SceneObject *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSceneObjectPtr"; 
}


/*! \ingroup GrpKabalaEngineFieldTraits
 */
template <>
struct FieldTraits<SceneObject *, 1> :
    public FieldTraitsFCPtrBase<SceneObject *, 1>
{
  private:

  public:
    typedef FieldTraits<SceneObject *, 1>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);
};

template<> inline
const Char8 *FieldTraits<SceneObject *, 1>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecChildSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 1>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecChildSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 1>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakChildSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 1>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdChildSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 1>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecChildSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 1>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecChildSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 1>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakChildSceneObjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObject *, 1>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdChildSceneObjectPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneObject *,
                      RecordedRefCountPolicy  > SFRecSceneObjectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneObject *,
                      UnrecordedRefCountPolicy> SFUnrecSceneObjectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneObject *,
                      WeakRefCountPolicy      > SFWeakSceneObjectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneObject *,
                      NoRefCountPolicy        > SFUncountedSceneObjectPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneObject *,
                      RecordedRefCountPolicy  > MFRecSceneObjectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneObject *,
                      UnrecordedRefCountPolicy> MFUnrecSceneObjectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneObject *,
                      WeakRefCountPolicy      > MFWeakSceneObjectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneObject *,
                      NoRefCountPolicy        > MFUncountedSceneObjectPtr;



/*! \ingroup GrpKabalaEngineFieldMFields */
typedef ChildPointerMField<
          SceneObject *, 
          UnrecordedRefCountPolicy,
          1             > MFUnrecChildSceneObjectPtr;



#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSceneObjectPtr : 
    public PointerSField<SceneObject *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSceneObjectPtr : 
    public PointerSField<SceneObject *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSceneObjectPtr :
    public PointerSField<SceneObject *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSceneObjectPtr :
    public PointerSField<SceneObject *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecSceneObjectPtr :
    public PointerMField<SceneObject *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecSceneObjectPtr :
    public PointerMField<SceneObject *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakSceneObjectPtr :
    public PointerMField<SceneObject *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedSceneObjectPtr :
    public PointerMField<SceneObject *,
                         NoRefCountPolicy        > {};



/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecChildSceneObjectPtr :
    public ChildPointerMField<
        SceneObject *, 
        UnrecordedRefCountPolicy,
        1             > {};


#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESCENEOBJECTFIELDS_H_ */
