/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                                                                           *
 *   contact: djkabala@gmail.com                                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class SceneObjectContainer!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILESCENEOBJECTCONTAINERINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "KESceneObjectContainerBase.h"
#include "KESceneObjectContainer.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  SceneObjectContainerBase::SceneObjectsFieldMask = 
    (TypeTraits<BitVector>::One << SceneObjectContainerBase::SceneObjectsFieldId);

const OSG::BitVector SceneObjectContainerBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var SceneObjectPtr  SceneObjectContainerBase::_mfSceneObjects
    
*/

//! SceneObjectContainer description

FieldDescription *SceneObjectContainerBase::_desc[] = 
{
    new FieldDescription(MFSceneObjectPtr::getClassType(), 
                     "SceneObjects", 
                     SceneObjectsFieldId, SceneObjectsFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&SceneObjectContainerBase::editMFSceneObjects))
};


FieldContainerType SceneObjectContainerBase::_type(
    "SceneObjectContainer",
    "SceneObject",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&SceneObjectContainerBase::createEmpty),
    SceneObjectContainer::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(SceneObjectContainerBase, SceneObjectContainerPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &SceneObjectContainerBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &SceneObjectContainerBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr SceneObjectContainerBase::shallowCopy(void) const 
{ 
    SceneObjectContainerPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const SceneObjectContainer *>(this)); 

    return returnValue; 
}

UInt32 SceneObjectContainerBase::getContainerSize(void) const 
{ 
    return sizeof(SceneObjectContainer); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void SceneObjectContainerBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<SceneObjectContainerBase *>(&other),
                          whichField);
}
#else
void SceneObjectContainerBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((SceneObjectContainerBase *) &other, whichField, sInfo);
}
void SceneObjectContainerBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void SceneObjectContainerBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

    _mfSceneObjects.terminateShare(uiAspect, this->getContainerSize());
}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

SceneObjectContainerBase::SceneObjectContainerBase(void) :
    _mfSceneObjects           (), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

SceneObjectContainerBase::SceneObjectContainerBase(const SceneObjectContainerBase &source) :
    _mfSceneObjects           (source._mfSceneObjects           ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

SceneObjectContainerBase::~SceneObjectContainerBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 SceneObjectContainerBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (SceneObjectsFieldMask & whichField))
    {
        returnValue += _mfSceneObjects.getBinSize();
    }


    return returnValue;
}

void SceneObjectContainerBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (SceneObjectsFieldMask & whichField))
    {
        _mfSceneObjects.copyToBin(pMem);
    }


}

void SceneObjectContainerBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (SceneObjectsFieldMask & whichField))
    {
        _mfSceneObjects.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void SceneObjectContainerBase::executeSyncImpl(      SceneObjectContainerBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (SceneObjectsFieldMask & whichField))
        _mfSceneObjects.syncWith(pOther->_mfSceneObjects);


}
#else
void SceneObjectContainerBase::executeSyncImpl(      SceneObjectContainerBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);


    if(FieldBits::NoField != (SceneObjectsFieldMask & whichField))
        _mfSceneObjects.syncWith(pOther->_mfSceneObjects, sInfo);


}

void SceneObjectContainerBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

    if(FieldBits::NoField != (SceneObjectsFieldMask & whichField))
        _mfSceneObjects.beginEdit(uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<SceneObjectContainerPtr>::_type("SceneObjectContainerPtr", "SceneObjectPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(SceneObjectContainerPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(SceneObjectContainerPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

