/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESCENEEDITINGVIEWPORTFIELDS_H_
#define _KESCENEEDITINGVIEWPORTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SceneEditingViewport;

OSG_GEN_CONTAINERPTR(SceneEditingViewport);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SceneEditingViewport *> :
    public FieldTraitsFCPtrBase<SceneEditingViewport *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SceneEditingViewport *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSceneEditingViewportPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSceneEditingViewportPtr"; }
};

template<> inline
const Char8 *FieldTraits<SceneEditingViewport *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSceneEditingViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditingViewport *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSceneEditingViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditingViewport *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSceneEditingViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditingViewport *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSceneEditingViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditingViewport *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSceneEditingViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditingViewport *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSceneEditingViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditingViewport *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSceneEditingViewportPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditingViewport *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSceneEditingViewportPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEditingViewport *,
                      RecordedRefCountPolicy  > SFRecSceneEditingViewportPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEditingViewport *,
                      UnrecordedRefCountPolicy> SFUnrecSceneEditingViewportPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEditingViewport *,
                      WeakRefCountPolicy      > SFWeakSceneEditingViewportPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEditingViewport *,
                      NoRefCountPolicy        > SFUncountedSceneEditingViewportPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneEditingViewport *,
                      RecordedRefCountPolicy  > MFRecSceneEditingViewportPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneEditingViewport *,
                      UnrecordedRefCountPolicy> MFUnrecSceneEditingViewportPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneEditingViewport *,
                      WeakRefCountPolicy      > MFWeakSceneEditingViewportPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneEditingViewport *,
                      NoRefCountPolicy        > MFUncountedSceneEditingViewportPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSceneEditingViewportPtr : 
    public PointerSField<SceneEditingViewport *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSceneEditingViewportPtr : 
    public PointerSField<SceneEditingViewport *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSceneEditingViewportPtr :
    public PointerSField<SceneEditingViewport *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSceneEditingViewportPtr :
    public PointerSField<SceneEditingViewport *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecSceneEditingViewportPtr :
    public PointerMField<SceneEditingViewport *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecSceneEditingViewportPtr :
    public PointerMField<SceneEditingViewport *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakSceneEditingViewportPtr :
    public PointerMField<SceneEditingViewport *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedSceneEditingViewportPtr :
    public PointerMField<SceneEditingViewport *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESCENEEDITINGVIEWPORTFIELDS_H_ */
