/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class SceneViewportPanel!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>




#include "KESceneViewportPanelBase.h"
#include "KESceneViewportPanel.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::SceneViewportPanel
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<SceneViewportPanel *>::_type("SceneViewportPanelPtr", "InterfacePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(SceneViewportPanel *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           SceneViewportPanel *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           SceneViewportPanel *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void SceneViewportPanelBase::classDescInserter(TypeObject &oType)
{
}


SceneViewportPanelBase::TypeObject SceneViewportPanelBase::_type(
    SceneViewportPanelBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&SceneViewportPanelBase::createEmptyLocal),
    SceneViewportPanel::initMethod,
    SceneViewportPanel::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&SceneViewportPanel::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"SceneViewportPanel\"\n"
    "\tparent=\"Interface\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &SceneViewportPanelBase::getType(void)
{
    return _type;
}

const FieldContainerType &SceneViewportPanelBase::getType(void) const
{
    return _type;
}

UInt32 SceneViewportPanelBase::getContainerSize(void) const
{
    return sizeof(SceneViewportPanel);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 SceneViewportPanelBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void SceneViewportPanelBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void SceneViewportPanelBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
SceneViewportPanelTransitPtr SceneViewportPanelBase::createLocal(BitVector bFlags)
{
    SceneViewportPanelTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<SceneViewportPanel>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
SceneViewportPanelTransitPtr SceneViewportPanelBase::createDependent(BitVector bFlags)
{
    SceneViewportPanelTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<SceneViewportPanel>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
SceneViewportPanelTransitPtr SceneViewportPanelBase::create(void)
{
    SceneViewportPanelTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<SceneViewportPanel>(tmpPtr);
    }

    return fc;
}

SceneViewportPanel *SceneViewportPanelBase::createEmptyLocal(BitVector bFlags)
{
    SceneViewportPanel *returnValue;

    newPtr<SceneViewportPanel>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
SceneViewportPanel *SceneViewportPanelBase::createEmpty(void)
{
    SceneViewportPanel *returnValue;

    newPtr<SceneViewportPanel>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr SceneViewportPanelBase::shallowCopyLocal(
    BitVector bFlags) const
{
    SceneViewportPanel *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const SceneViewportPanel *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr SceneViewportPanelBase::shallowCopyDependent(
    BitVector bFlags) const
{
    SceneViewportPanel *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const SceneViewportPanel *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr SceneViewportPanelBase::shallowCopy(void) const
{
    SceneViewportPanel *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const SceneViewportPanel *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

SceneViewportPanelBase::SceneViewportPanelBase(void) :
    Inherited()
{
}

SceneViewportPanelBase::SceneViewportPanelBase(const SceneViewportPanelBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

SceneViewportPanelBase::~SceneViewportPanelBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void SceneViewportPanelBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    SceneViewportPanel *pThis = static_cast<SceneViewportPanel *>(this);

    pThis->execSync(static_cast<SceneViewportPanel *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *SceneViewportPanelBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    SceneViewportPanel *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const SceneViewportPanel *>(pRefAspect),
                  dynamic_cast<const SceneViewportPanel *>(this));

    return returnValue;
}
#endif

void SceneViewportPanelBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
