/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class GettingStartedWindow!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>




#include "KEGettingStartedWindowBase.h"
#include "KEGettingStartedWindow.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::GettingStartedWindow
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<GettingStartedWindow *>::_type("GettingStartedWindowPtr", "InterfacePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(GettingStartedWindow *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           GettingStartedWindow *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           GettingStartedWindow *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void GettingStartedWindowBase::classDescInserter(TypeObject &oType)
{
}


GettingStartedWindowBase::TypeObject GettingStartedWindowBase::_type(
    GettingStartedWindowBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&GettingStartedWindowBase::createEmptyLocal),
    GettingStartedWindow::initMethod,
    GettingStartedWindow::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&GettingStartedWindow::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"GettingStartedWindow\"\n"
    "\tparent=\"Interface\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &GettingStartedWindowBase::getType(void)
{
    return _type;
}

const FieldContainerType &GettingStartedWindowBase::getType(void) const
{
    return _type;
}

UInt32 GettingStartedWindowBase::getContainerSize(void) const
{
    return sizeof(GettingStartedWindow);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 GettingStartedWindowBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void GettingStartedWindowBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void GettingStartedWindowBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
GettingStartedWindowTransitPtr GettingStartedWindowBase::createLocal(BitVector bFlags)
{
    GettingStartedWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<GettingStartedWindow>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
GettingStartedWindowTransitPtr GettingStartedWindowBase::createDependent(BitVector bFlags)
{
    GettingStartedWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<GettingStartedWindow>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
GettingStartedWindowTransitPtr GettingStartedWindowBase::create(void)
{
    GettingStartedWindowTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<GettingStartedWindow>(tmpPtr);
    }

    return fc;
}

GettingStartedWindow *GettingStartedWindowBase::createEmptyLocal(BitVector bFlags)
{
    GettingStartedWindow *returnValue;

    newPtr<GettingStartedWindow>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
GettingStartedWindow *GettingStartedWindowBase::createEmpty(void)
{
    GettingStartedWindow *returnValue;

    newPtr<GettingStartedWindow>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr GettingStartedWindowBase::shallowCopyLocal(
    BitVector bFlags) const
{
    GettingStartedWindow *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const GettingStartedWindow *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr GettingStartedWindowBase::shallowCopyDependent(
    BitVector bFlags) const
{
    GettingStartedWindow *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const GettingStartedWindow *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr GettingStartedWindowBase::shallowCopy(void) const
{
    GettingStartedWindow *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const GettingStartedWindow *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

GettingStartedWindowBase::GettingStartedWindowBase(void) :
    Inherited()
{
}

GettingStartedWindowBase::GettingStartedWindowBase(const GettingStartedWindowBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

GettingStartedWindowBase::~GettingStartedWindowBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void GettingStartedWindowBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    GettingStartedWindow *pThis = static_cast<GettingStartedWindow *>(this);

    pThis->execSync(static_cast<GettingStartedWindow *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *GettingStartedWindowBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    GettingStartedWindow *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const GettingStartedWindow *>(pRefAspect),
                  dynamic_cast<const GettingStartedWindow *>(this));

    return returnValue;
}
#endif

void GettingStartedWindowBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
