/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEGETTINGSTARTEDWINDOWFIELDS_H_
#define _KEGETTINGSTARTEDWINDOWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class GettingStartedWindow;

OSG_GEN_CONTAINERPTR(GettingStartedWindow);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<GettingStartedWindow *> :
    public FieldTraitsFCPtrBase<GettingStartedWindow *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<GettingStartedWindow *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFGettingStartedWindowPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFGettingStartedWindowPtr"; }
};

template<> inline
const Char8 *FieldTraits<GettingStartedWindow *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecGettingStartedWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GettingStartedWindow *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecGettingStartedWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GettingStartedWindow *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakGettingStartedWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GettingStartedWindow *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdGettingStartedWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GettingStartedWindow *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecGettingStartedWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GettingStartedWindow *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecGettingStartedWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GettingStartedWindow *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakGettingStartedWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<GettingStartedWindow *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdGettingStartedWindowPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<GettingStartedWindow *,
                      RecordedRefCountPolicy  > SFRecGettingStartedWindowPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<GettingStartedWindow *,
                      UnrecordedRefCountPolicy> SFUnrecGettingStartedWindowPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<GettingStartedWindow *,
                      WeakRefCountPolicy      > SFWeakGettingStartedWindowPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<GettingStartedWindow *,
                      NoRefCountPolicy        > SFUncountedGettingStartedWindowPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<GettingStartedWindow *,
                      RecordedRefCountPolicy  > MFRecGettingStartedWindowPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<GettingStartedWindow *,
                      UnrecordedRefCountPolicy> MFUnrecGettingStartedWindowPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<GettingStartedWindow *,
                      WeakRefCountPolicy      > MFWeakGettingStartedWindowPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<GettingStartedWindow *,
                      NoRefCountPolicy        > MFUncountedGettingStartedWindowPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecGettingStartedWindowPtr : 
    public PointerSField<GettingStartedWindow *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecGettingStartedWindowPtr : 
    public PointerSField<GettingStartedWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakGettingStartedWindowPtr :
    public PointerSField<GettingStartedWindow *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedGettingStartedWindowPtr :
    public PointerSField<GettingStartedWindow *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecGettingStartedWindowPtr :
    public PointerMField<GettingStartedWindow *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecGettingStartedWindowPtr :
    public PointerMField<GettingStartedWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakGettingStartedWindowPtr :
    public PointerMField<GettingStartedWindow *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedGettingStartedWindowPtr :
    public PointerMField<GettingStartedWindow *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEGETTINGSTARTEDWINDOWFIELDS_H_ */
