/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEHIERARCHYPANELFIELDS_H_
#define _KEHIERARCHYPANELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class HierarchyPanel;

OSG_GEN_CONTAINERPTR(HierarchyPanel);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<HierarchyPanel *> :
    public FieldTraitsFCPtrBase<HierarchyPanel *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<HierarchyPanel *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFHierarchyPanelPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFHierarchyPanelPtr"; }
};

template<> inline
const Char8 *FieldTraits<HierarchyPanel *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecHierarchyPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<HierarchyPanel *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecHierarchyPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<HierarchyPanel *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakHierarchyPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<HierarchyPanel *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdHierarchyPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<HierarchyPanel *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecHierarchyPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<HierarchyPanel *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecHierarchyPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<HierarchyPanel *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakHierarchyPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<HierarchyPanel *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdHierarchyPanelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<HierarchyPanel *,
                      RecordedRefCountPolicy  > SFRecHierarchyPanelPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<HierarchyPanel *,
                      UnrecordedRefCountPolicy> SFUnrecHierarchyPanelPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<HierarchyPanel *,
                      WeakRefCountPolicy      > SFWeakHierarchyPanelPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<HierarchyPanel *,
                      NoRefCountPolicy        > SFUncountedHierarchyPanelPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<HierarchyPanel *,
                      RecordedRefCountPolicy  > MFRecHierarchyPanelPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<HierarchyPanel *,
                      UnrecordedRefCountPolicy> MFUnrecHierarchyPanelPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<HierarchyPanel *,
                      WeakRefCountPolicy      > MFWeakHierarchyPanelPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<HierarchyPanel *,
                      NoRefCountPolicy        > MFUncountedHierarchyPanelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecHierarchyPanelPtr : 
    public PointerSField<HierarchyPanel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecHierarchyPanelPtr : 
    public PointerSField<HierarchyPanel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakHierarchyPanelPtr :
    public PointerSField<HierarchyPanel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedHierarchyPanelPtr :
    public PointerSField<HierarchyPanel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecHierarchyPanelPtr :
    public PointerMField<HierarchyPanel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecHierarchyPanelPtr :
    public PointerMField<HierarchyPanel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakHierarchyPanelPtr :
    public PointerMField<HierarchyPanel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedHierarchyPanelPtr :
    public PointerMField<HierarchyPanel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEHIERARCHYPANELFIELDS_H_ */
