/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESCENEOBJECTEDITORFIELDS_H_
#define _KESCENEOBJECTEDITORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SceneObjectEditor;

OSG_GEN_CONTAINERPTR(SceneObjectEditor);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SceneObjectEditor *> :
    public FieldTraitsFCPtrBase<SceneObjectEditor *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SceneObjectEditor *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSceneObjectEditorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSceneObjectEditorPtr"; }
};

template<> inline
const Char8 *FieldTraits<SceneObjectEditor *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSceneObjectEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObjectEditor *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSceneObjectEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObjectEditor *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSceneObjectEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObjectEditor *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSceneObjectEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObjectEditor *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSceneObjectEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObjectEditor *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSceneObjectEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObjectEditor *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSceneObjectEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneObjectEditor *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSceneObjectEditorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneObjectEditor *,
                      RecordedRefCountPolicy  > SFRecSceneObjectEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneObjectEditor *,
                      UnrecordedRefCountPolicy> SFUnrecSceneObjectEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneObjectEditor *,
                      WeakRefCountPolicy      > SFWeakSceneObjectEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneObjectEditor *,
                      NoRefCountPolicy        > SFUncountedSceneObjectEditorPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneObjectEditor *,
                      RecordedRefCountPolicy  > MFRecSceneObjectEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneObjectEditor *,
                      UnrecordedRefCountPolicy> MFUnrecSceneObjectEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneObjectEditor *,
                      WeakRefCountPolicy      > MFWeakSceneObjectEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneObjectEditor *,
                      NoRefCountPolicy        > MFUncountedSceneObjectEditorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSceneObjectEditorPtr : 
    public PointerSField<SceneObjectEditor *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSceneObjectEditorPtr : 
    public PointerSField<SceneObjectEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSceneObjectEditorPtr :
    public PointerSField<SceneObjectEditor *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSceneObjectEditorPtr :
    public PointerSField<SceneObjectEditor *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecSceneObjectEditorPtr :
    public PointerMField<SceneObjectEditor *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecSceneObjectEditorPtr :
    public PointerMField<SceneObjectEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakSceneObjectEditorPtr :
    public PointerMField<SceneObjectEditor *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedSceneObjectEditorPtr :
    public PointerMField<SceneObjectEditor *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESCENEOBJECTEDITORFIELDS_H_ */
