/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KECONTENTPANELFIELDS_H_
#define _KECONTENTPANELFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class ContentPanel;

OSG_GEN_CONTAINERPTR(ContentPanel);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<ContentPanel *> :
    public FieldTraitsFCPtrBase<ContentPanel *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ContentPanel *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFContentPanelPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFContentPanelPtr"; }
};

template<> inline
const Char8 *FieldTraits<ContentPanel *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecContentPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ContentPanel *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecContentPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ContentPanel *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakContentPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ContentPanel *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdContentPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ContentPanel *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecContentPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ContentPanel *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecContentPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ContentPanel *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakContentPanelPtr"; 
}

template<> inline
const Char8 *FieldTraits<ContentPanel *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdContentPanelPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ContentPanel *,
                      RecordedRefCountPolicy  > SFRecContentPanelPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ContentPanel *,
                      UnrecordedRefCountPolicy> SFUnrecContentPanelPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ContentPanel *,
                      WeakRefCountPolicy      > SFWeakContentPanelPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ContentPanel *,
                      NoRefCountPolicy        > SFUncountedContentPanelPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ContentPanel *,
                      RecordedRefCountPolicy  > MFRecContentPanelPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ContentPanel *,
                      UnrecordedRefCountPolicy> MFUnrecContentPanelPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ContentPanel *,
                      WeakRefCountPolicy      > MFWeakContentPanelPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ContentPanel *,
                      NoRefCountPolicy        > MFUncountedContentPanelPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecContentPanelPtr : 
    public PointerSField<ContentPanel *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecContentPanelPtr : 
    public PointerSField<ContentPanel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakContentPanelPtr :
    public PointerSField<ContentPanel *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedContentPanelPtr :
    public PointerSField<ContentPanel *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecContentPanelPtr :
    public PointerMField<ContentPanel *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecContentPanelPtr :
    public PointerMField<ContentPanel *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakContentPanelPtr :
    public PointerMField<ContentPanel *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedContentPanelPtr :
    public PointerMField<ContentPanel *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KECONTENTPANELFIELDS_H_ */
