/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ApplicationPlayer!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>




#include "KEApplicationPlayerBase.h"
#include "KEApplicationPlayer.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ApplicationPlayer
    The ApplicationPlayer.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<ApplicationPlayer *>::_type("ApplicationPlayerPtr", "ApplicationModePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(ApplicationPlayer *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ApplicationPlayer *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ApplicationPlayer *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ApplicationPlayerBase::classDescInserter(TypeObject &oType)
{
}


ApplicationPlayerBase::TypeObject ApplicationPlayerBase::_type(
    ApplicationPlayerBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&ApplicationPlayerBase::createEmptyLocal),
    ApplicationPlayer::initMethod,
    ApplicationPlayer::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ApplicationPlayer::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"ApplicationPlayer\"\n"
    "\tparent=\"ApplicationMode\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "The ApplicationPlayer.\n"
    "</FieldContainer>\n",
    "The ApplicationPlayer.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ApplicationPlayerBase::getType(void)
{
    return _type;
}

const FieldContainerType &ApplicationPlayerBase::getType(void) const
{
    return _type;
}

UInt32 ApplicationPlayerBase::getContainerSize(void) const
{
    return sizeof(ApplicationPlayer);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 ApplicationPlayerBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void ApplicationPlayerBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void ApplicationPlayerBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
ApplicationPlayerTransitPtr ApplicationPlayerBase::createLocal(BitVector bFlags)
{
    ApplicationPlayerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ApplicationPlayer>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ApplicationPlayerTransitPtr ApplicationPlayerBase::createDependent(BitVector bFlags)
{
    ApplicationPlayerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ApplicationPlayer>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ApplicationPlayerTransitPtr ApplicationPlayerBase::create(void)
{
    ApplicationPlayerTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ApplicationPlayer>(tmpPtr);
    }

    return fc;
}

ApplicationPlayer *ApplicationPlayerBase::createEmptyLocal(BitVector bFlags)
{
    ApplicationPlayer *returnValue;

    newPtr<ApplicationPlayer>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ApplicationPlayer *ApplicationPlayerBase::createEmpty(void)
{
    ApplicationPlayer *returnValue;

    newPtr<ApplicationPlayer>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ApplicationPlayerBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ApplicationPlayer *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ApplicationPlayer *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ApplicationPlayerBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ApplicationPlayer *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ApplicationPlayer *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ApplicationPlayerBase::shallowCopy(void) const
{
    ApplicationPlayer *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ApplicationPlayer *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

ApplicationPlayerBase::ApplicationPlayerBase(void) :
    Inherited()
{
}

ApplicationPlayerBase::ApplicationPlayerBase(const ApplicationPlayerBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ApplicationPlayerBase::~ApplicationPlayerBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void ApplicationPlayerBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ApplicationPlayer *pThis = static_cast<ApplicationPlayer *>(this);

    pThis->execSync(static_cast<ApplicationPlayer *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ApplicationPlayerBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ApplicationPlayer *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ApplicationPlayer *>(pRefAspect),
                  dynamic_cast<const ApplicationPlayer *>(this));

    return returnValue;
}
#endif

void ApplicationPlayerBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
