/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEPROJECTFIELDS_H_
#define _KEPROJECTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class Project;

OSG_GEN_CONTAINERPTR(Project);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<Project *> :
    public FieldTraitsFCPtrBase<Project *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<Project *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFProjectPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFProjectPtr"; }
};

template<> inline
const Char8 *FieldTraits<Project *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecProjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<Project *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecProjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<Project *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakProjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<Project *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdProjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<Project *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecProjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<Project *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecProjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<Project *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakProjectPtr"; 
}

template<> inline
const Char8 *FieldTraits<Project *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdProjectPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<Project *,
                      RecordedRefCountPolicy  > SFRecProjectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<Project *,
                      UnrecordedRefCountPolicy> SFUnrecProjectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<Project *,
                      WeakRefCountPolicy      > SFWeakProjectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<Project *,
                      NoRefCountPolicy        > SFUncountedProjectPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<Project *,
                      RecordedRefCountPolicy  > MFRecProjectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<Project *,
                      UnrecordedRefCountPolicy> MFUnrecProjectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<Project *,
                      WeakRefCountPolicy      > MFWeakProjectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<Project *,
                      NoRefCountPolicy        > MFUncountedProjectPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecProjectPtr : 
    public PointerSField<Project *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecProjectPtr : 
    public PointerSField<Project *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakProjectPtr :
    public PointerSField<Project *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedProjectPtr :
    public PointerSField<Project *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecProjectPtr :
    public PointerMField<Project *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecProjectPtr :
    public PointerMField<Project *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakProjectPtr :
    public PointerMField<Project *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedProjectPtr :
    public PointerMField<Project *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEPROJECTFIELDS_H_ */
