/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala (dkabala@vrac.iastate.edu)                        *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Project!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILEPROJECTINST

#include <stdlib.h>
#include <stdio.h>

#include "KEConfig.h"

#include "KEProjectBase.h"
#include "KEProject.h"


KE_USING_NAMESPACE

const OSG::BitVector  ProjectBase::NameFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::NameFieldId);

const OSG::BitVector  ProjectBase::MainWindowTitleFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::MainWindowTitleFieldId);

const OSG::BitVector  ProjectBase::FilePathFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::FilePathFieldId);

const OSG::BitVector  ProjectBase::ScenesFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::ScenesFieldId);

const OSG::BitVector  ProjectBase::InitialSceneFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::InitialSceneFieldId);

const OSG::BitVector  ProjectBase::InternalActiveSceneFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::InternalActiveSceneFieldId);

const OSG::BitVector  ProjectBase::BackgroundsFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::BackgroundsFieldId);

const OSG::BitVector  ProjectBase::InternalActiveBackgroundFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::InternalActiveBackgroundFieldId);

const OSG::BitVector  ProjectBase::ForegroundsFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::ForegroundsFieldId);

const OSG::BitVector  ProjectBase::InternalActiveForegroundsFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::InternalActiveForegroundsFieldId);

const OSG::BitVector  ProjectBase::ModelNodesFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::ModelNodesFieldId);

const OSG::BitVector  ProjectBase::InternalActiveModelNodesFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::InternalActiveModelNodesFieldId);

const OSG::BitVector  ProjectBase::CamerasFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::CamerasFieldId);

const OSG::BitVector  ProjectBase::InternalActiveCameraFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::InternalActiveCameraFieldId);

const OSG::BitVector  ProjectBase::InternalParentApplicationFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::InternalParentApplicationFieldId);

const OSG::BitVector  ProjectBase::InternalActiveViewportFieldMask = 
    (TypeTraits<BitVector>::One << ProjectBase::InternalActiveViewportFieldId);

const OSG::BitVector ProjectBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var std::string     ProjectBase::_sfName
    
*/
/*! \var std::string     ProjectBase::_sfMainWindowTitle
    
*/
/*! \var Path            ProjectBase::_sfFilePath
    
*/
/*! \var ScenePtr        ProjectBase::_mfScenes
    
*/
/*! \var ScenePtr        ProjectBase::_sfInitialScene
    
*/
/*! \var ScenePtr        ProjectBase::_sfInternalActiveScene
    
*/
/*! \var BackgroundPtr   ProjectBase::_mfBackgrounds
    
*/
/*! \var BackgroundPtr   ProjectBase::_sfInternalActiveBackground
    
*/
/*! \var ForegroundPtr   ProjectBase::_mfForegrounds
    
*/
/*! \var ForegroundPtr   ProjectBase::_mfInternalActiveForegrounds
    
*/
/*! \var NodePtr         ProjectBase::_mfModelNodes
    
*/
/*! \var NodePtr         ProjectBase::_mfInternalActiveModelNodes
    
*/
/*! \var CameraPtr       ProjectBase::_mfCameras
    
*/
/*! \var CameraPtr       ProjectBase::_sfInternalActiveCamera
    
*/
/*! \var MainApplicationPtr ProjectBase::_sfInternalParentApplication
    
*/
/*! \var ViewportPtr     ProjectBase::_sfInternalActiveViewport
    
*/

//! Project description

FieldDescription *ProjectBase::_desc[] = 
{
    new FieldDescription(SFString::getClassType(), 
                     "Name", 
                     NameFieldId, NameFieldMask,
                     false,
                     (FieldAccessMethod) &ProjectBase::getSFName),
    new FieldDescription(SFString::getClassType(), 
                     "MainWindowTitle", 
                     MainWindowTitleFieldId, MainWindowTitleFieldMask,
                     false,
                     (FieldAccessMethod) &ProjectBase::getSFMainWindowTitle),
    new FieldDescription(SFPath::getClassType(), 
                     "FilePath", 
                     FilePathFieldId, FilePathFieldMask,
                     false,
                     (FieldAccessMethod) &ProjectBase::getSFFilePath),
    new FieldDescription(MFScenePtr::getClassType(), 
                     "Scenes", 
                     ScenesFieldId, ScenesFieldMask,
                     false,
                     (FieldAccessMethod) &ProjectBase::getMFScenes),
    new FieldDescription(SFScenePtr::getClassType(), 
                     "InitialScene", 
                     InitialSceneFieldId, InitialSceneFieldMask,
                     false,
                     (FieldAccessMethod) &ProjectBase::getSFInitialScene),
    new FieldDescription(SFScenePtr::getClassType(), 
                     "InternalActiveScene", 
                     InternalActiveSceneFieldId, InternalActiveSceneFieldMask,
                     true,
                     (FieldAccessMethod) &ProjectBase::getSFInternalActiveScene),
    new FieldDescription(MFBackgroundPtr::getClassType(), 
                     "Backgrounds", 
                     BackgroundsFieldId, BackgroundsFieldMask,
                     false,
                     (FieldAccessMethod) &ProjectBase::getMFBackgrounds),
    new FieldDescription(SFBackgroundPtr::getClassType(), 
                     "InternalActiveBackground", 
                     InternalActiveBackgroundFieldId, InternalActiveBackgroundFieldMask,
                     true,
                     (FieldAccessMethod) &ProjectBase::getSFInternalActiveBackground),
    new FieldDescription(MFForegroundPtr::getClassType(), 
                     "Foregrounds", 
                     ForegroundsFieldId, ForegroundsFieldMask,
                     false,
                     (FieldAccessMethod) &ProjectBase::getMFForegrounds),
    new FieldDescription(MFForegroundPtr::getClassType(), 
                     "InternalActiveForegrounds", 
                     InternalActiveForegroundsFieldId, InternalActiveForegroundsFieldMask,
                     true,
                     (FieldAccessMethod) &ProjectBase::getMFInternalActiveForegrounds),
    new FieldDescription(MFNodePtr::getClassType(), 
                     "ModelNodes", 
                     ModelNodesFieldId, ModelNodesFieldMask,
                     false,
                     (FieldAccessMethod) &ProjectBase::getMFModelNodes),
    new FieldDescription(MFNodePtr::getClassType(), 
                     "InternalActiveModelNodes", 
                     InternalActiveModelNodesFieldId, InternalActiveModelNodesFieldMask,
                     true,
                     (FieldAccessMethod) &ProjectBase::getMFInternalActiveModelNodes),
    new FieldDescription(MFCameraPtr::getClassType(), 
                     "Cameras", 
                     CamerasFieldId, CamerasFieldMask,
                     false,
                     (FieldAccessMethod) &ProjectBase::getMFCameras),
    new FieldDescription(SFCameraPtr::getClassType(), 
                     "InternalActiveCamera", 
                     InternalActiveCameraFieldId, InternalActiveCameraFieldMask,
                     true,
                     (FieldAccessMethod) &ProjectBase::getSFInternalActiveCamera),
    new FieldDescription(SFMainApplicationPtr::getClassType(), 
                     "InternalParentApplication", 
                     InternalParentApplicationFieldId, InternalParentApplicationFieldMask,
                     true,
                     (FieldAccessMethod) &ProjectBase::getSFInternalParentApplication),
    new FieldDescription(SFViewportPtr::getClassType(), 
                     "InternalActiveViewport", 
                     InternalActiveViewportFieldId, InternalActiveViewportFieldMask,
                     true,
                     (FieldAccessMethod) &ProjectBase::getSFInternalActiveViewport)
};


FieldContainerType ProjectBase::_type(
    "Project",
    "FieldContainer",
    NULL,
    (PrototypeCreateF) &ProjectBase::createEmpty,
    Project::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(ProjectBase, ProjectPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &ProjectBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &ProjectBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr ProjectBase::shallowCopy(void) const 
{ 
    ProjectPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const Project *>(this)); 

    return returnValue; 
}

::osg::UInt32 ProjectBase::getContainerSize(void) const 
{ 
    return sizeof(Project); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void ProjectBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((ProjectBase *) &other, whichField);
}
#else
void ProjectBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((ProjectBase *) &other, whichField, sInfo);
}
void ProjectBase::execBeginEdit(const BitVector &whichField, 
                                            ::osg::UInt32     uiAspect,
                                            ::osg::UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void ProjectBase::onDestroyAspect(::osg::UInt32 uiId, ::osg::UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

    _mfScenes.terminateShare(uiAspect, this->getContainerSize());
    _mfBackgrounds.terminateShare(uiAspect, this->getContainerSize());
    _mfForegrounds.terminateShare(uiAspect, this->getContainerSize());
    _mfInternalActiveForegrounds.terminateShare(uiAspect, this->getContainerSize());
    _mfModelNodes.terminateShare(uiAspect, this->getContainerSize());
    _mfInternalActiveModelNodes.terminateShare(uiAspect, this->getContainerSize());
    _mfCameras.terminateShare(uiAspect, this->getContainerSize());
}
#endif

/*------------------------- constructors ----------------------------------*/

ProjectBase::ProjectBase(void) :
    _sfName                   (), 
    _sfMainWindowTitle        (), 
    _sfFilePath               (), 
    _mfScenes                 (), 
    _sfInitialScene           (ScenePtr(NullFC)), 
    _sfInternalActiveScene    (ScenePtr(NullFC)), 
    _mfBackgrounds            (), 
    _sfInternalActiveBackground(BackgroundPtr(NullFC)), 
    _mfForegrounds            (), 
    _mfInternalActiveForegrounds(), 
    _mfModelNodes             (), 
    _mfInternalActiveModelNodes(), 
    _mfCameras                (), 
    _sfInternalActiveCamera   (CameraPtr(NullFC)), 
    _sfInternalParentApplication(MainApplicationPtr(NullFC)), 
    _sfInternalActiveViewport (ViewportPtr(NullFC)), 
    Inherited() 
{
}

ProjectBase::ProjectBase(const ProjectBase &source) :
    _sfName                   (source._sfName                   ), 
    _sfMainWindowTitle        (source._sfMainWindowTitle        ), 
    _sfFilePath               (source._sfFilePath               ), 
    _mfScenes                 (source._mfScenes                 ), 
    _sfInitialScene           (source._sfInitialScene           ), 
    _sfInternalActiveScene    (source._sfInternalActiveScene    ), 
    _mfBackgrounds            (source._mfBackgrounds            ), 
    _sfInternalActiveBackground(source._sfInternalActiveBackground), 
    _mfForegrounds            (source._mfForegrounds            ), 
    _mfInternalActiveForegrounds(source._mfInternalActiveForegrounds), 
    _mfModelNodes             (source._mfModelNodes             ), 
    _mfInternalActiveModelNodes(source._mfInternalActiveModelNodes), 
    _mfCameras                (source._mfCameras                ), 
    _sfInternalActiveCamera   (source._sfInternalActiveCamera   ), 
    _sfInternalParentApplication(source._sfInternalParentApplication), 
    _sfInternalActiveViewport (source._sfInternalActiveViewport ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

ProjectBase::~ProjectBase(void)
{
}

/*------------------------------ access -----------------------------------*/

::osg::UInt32 ProjectBase::getBinSize(const BitVector &whichField)
{
    ::osg::UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (NameFieldMask & whichField))
    {
        returnValue += _sfName.getBinSize();
    }

    if(FieldBits::NoField != (MainWindowTitleFieldMask & whichField))
    {
        returnValue += _sfMainWindowTitle.getBinSize();
    }

    if(FieldBits::NoField != (FilePathFieldMask & whichField))
    {
        returnValue += _sfFilePath.getBinSize();
    }

    if(FieldBits::NoField != (ScenesFieldMask & whichField))
    {
        returnValue += _mfScenes.getBinSize();
    }

    if(FieldBits::NoField != (InitialSceneFieldMask & whichField))
    {
        returnValue += _sfInitialScene.getBinSize();
    }

    if(FieldBits::NoField != (InternalActiveSceneFieldMask & whichField))
    {
        returnValue += _sfInternalActiveScene.getBinSize();
    }

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
    {
        returnValue += _mfBackgrounds.getBinSize();
    }

    if(FieldBits::NoField != (InternalActiveBackgroundFieldMask & whichField))
    {
        returnValue += _sfInternalActiveBackground.getBinSize();
    }

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
    {
        returnValue += _mfForegrounds.getBinSize();
    }

    if(FieldBits::NoField != (InternalActiveForegroundsFieldMask & whichField))
    {
        returnValue += _mfInternalActiveForegrounds.getBinSize();
    }

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
    {
        returnValue += _mfModelNodes.getBinSize();
    }

    if(FieldBits::NoField != (InternalActiveModelNodesFieldMask & whichField))
    {
        returnValue += _mfInternalActiveModelNodes.getBinSize();
    }

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
    {
        returnValue += _mfCameras.getBinSize();
    }

    if(FieldBits::NoField != (InternalActiveCameraFieldMask & whichField))
    {
        returnValue += _sfInternalActiveCamera.getBinSize();
    }

    if(FieldBits::NoField != (InternalParentApplicationFieldMask & whichField))
    {
        returnValue += _sfInternalParentApplication.getBinSize();
    }

    if(FieldBits::NoField != (InternalActiveViewportFieldMask & whichField))
    {
        returnValue += _sfInternalActiveViewport.getBinSize();
    }


    return returnValue;
}

void ProjectBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (NameFieldMask & whichField))
    {
        _sfName.copyToBin(pMem);
    }

    if(FieldBits::NoField != (MainWindowTitleFieldMask & whichField))
    {
        _sfMainWindowTitle.copyToBin(pMem);
    }

    if(FieldBits::NoField != (FilePathFieldMask & whichField))
    {
        _sfFilePath.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ScenesFieldMask & whichField))
    {
        _mfScenes.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InitialSceneFieldMask & whichField))
    {
        _sfInitialScene.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveSceneFieldMask & whichField))
    {
        _sfInternalActiveScene.copyToBin(pMem);
    }

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
    {
        _mfBackgrounds.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveBackgroundFieldMask & whichField))
    {
        _sfInternalActiveBackground.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
    {
        _mfForegrounds.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveForegroundsFieldMask & whichField))
    {
        _mfInternalActiveForegrounds.copyToBin(pMem);
    }

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
    {
        _mfModelNodes.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveModelNodesFieldMask & whichField))
    {
        _mfInternalActiveModelNodes.copyToBin(pMem);
    }

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
    {
        _mfCameras.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveCameraFieldMask & whichField))
    {
        _sfInternalActiveCamera.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InternalParentApplicationFieldMask & whichField))
    {
        _sfInternalParentApplication.copyToBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveViewportFieldMask & whichField))
    {
        _sfInternalActiveViewport.copyToBin(pMem);
    }


}

void ProjectBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (NameFieldMask & whichField))
    {
        _sfName.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (MainWindowTitleFieldMask & whichField))
    {
        _sfMainWindowTitle.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (FilePathFieldMask & whichField))
    {
        _sfFilePath.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ScenesFieldMask & whichField))
    {
        _mfScenes.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InitialSceneFieldMask & whichField))
    {
        _sfInitialScene.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveSceneFieldMask & whichField))
    {
        _sfInternalActiveScene.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
    {
        _mfBackgrounds.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveBackgroundFieldMask & whichField))
    {
        _sfInternalActiveBackground.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
    {
        _mfForegrounds.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveForegroundsFieldMask & whichField))
    {
        _mfInternalActiveForegrounds.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
    {
        _mfModelNodes.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveModelNodesFieldMask & whichField))
    {
        _mfInternalActiveModelNodes.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
    {
        _mfCameras.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveCameraFieldMask & whichField))
    {
        _sfInternalActiveCamera.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InternalParentApplicationFieldMask & whichField))
    {
        _sfInternalParentApplication.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (InternalActiveViewportFieldMask & whichField))
    {
        _sfInternalActiveViewport.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void ProjectBase::executeSyncImpl(      ProjectBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (NameFieldMask & whichField))
        _sfName.syncWith(pOther->_sfName);

    if(FieldBits::NoField != (MainWindowTitleFieldMask & whichField))
        _sfMainWindowTitle.syncWith(pOther->_sfMainWindowTitle);

    if(FieldBits::NoField != (FilePathFieldMask & whichField))
        _sfFilePath.syncWith(pOther->_sfFilePath);

    if(FieldBits::NoField != (ScenesFieldMask & whichField))
        _mfScenes.syncWith(pOther->_mfScenes);

    if(FieldBits::NoField != (InitialSceneFieldMask & whichField))
        _sfInitialScene.syncWith(pOther->_sfInitialScene);

    if(FieldBits::NoField != (InternalActiveSceneFieldMask & whichField))
        _sfInternalActiveScene.syncWith(pOther->_sfInternalActiveScene);

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
        _mfBackgrounds.syncWith(pOther->_mfBackgrounds);

    if(FieldBits::NoField != (InternalActiveBackgroundFieldMask & whichField))
        _sfInternalActiveBackground.syncWith(pOther->_sfInternalActiveBackground);

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
        _mfForegrounds.syncWith(pOther->_mfForegrounds);

    if(FieldBits::NoField != (InternalActiveForegroundsFieldMask & whichField))
        _mfInternalActiveForegrounds.syncWith(pOther->_mfInternalActiveForegrounds);

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
        _mfModelNodes.syncWith(pOther->_mfModelNodes);

    if(FieldBits::NoField != (InternalActiveModelNodesFieldMask & whichField))
        _mfInternalActiveModelNodes.syncWith(pOther->_mfInternalActiveModelNodes);

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
        _mfCameras.syncWith(pOther->_mfCameras);

    if(FieldBits::NoField != (InternalActiveCameraFieldMask & whichField))
        _sfInternalActiveCamera.syncWith(pOther->_sfInternalActiveCamera);

    if(FieldBits::NoField != (InternalParentApplicationFieldMask & whichField))
        _sfInternalParentApplication.syncWith(pOther->_sfInternalParentApplication);

    if(FieldBits::NoField != (InternalActiveViewportFieldMask & whichField))
        _sfInternalActiveViewport.syncWith(pOther->_sfInternalActiveViewport);


}
#else
void ProjectBase::executeSyncImpl(      ProjectBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (NameFieldMask & whichField))
        _sfName.syncWith(pOther->_sfName);

    if(FieldBits::NoField != (MainWindowTitleFieldMask & whichField))
        _sfMainWindowTitle.syncWith(pOther->_sfMainWindowTitle);

    if(FieldBits::NoField != (FilePathFieldMask & whichField))
        _sfFilePath.syncWith(pOther->_sfFilePath);

    if(FieldBits::NoField != (InitialSceneFieldMask & whichField))
        _sfInitialScene.syncWith(pOther->_sfInitialScene);

    if(FieldBits::NoField != (InternalActiveSceneFieldMask & whichField))
        _sfInternalActiveScene.syncWith(pOther->_sfInternalActiveScene);

    if(FieldBits::NoField != (InternalActiveBackgroundFieldMask & whichField))
        _sfInternalActiveBackground.syncWith(pOther->_sfInternalActiveBackground);

    if(FieldBits::NoField != (InternalActiveCameraFieldMask & whichField))
        _sfInternalActiveCamera.syncWith(pOther->_sfInternalActiveCamera);

    if(FieldBits::NoField != (InternalParentApplicationFieldMask & whichField))
        _sfInternalParentApplication.syncWith(pOther->_sfInternalParentApplication);

    if(FieldBits::NoField != (InternalActiveViewportFieldMask & whichField))
        _sfInternalActiveViewport.syncWith(pOther->_sfInternalActiveViewport);


    if(FieldBits::NoField != (ScenesFieldMask & whichField))
        _mfScenes.syncWith(pOther->_mfScenes, sInfo);

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
        _mfBackgrounds.syncWith(pOther->_mfBackgrounds, sInfo);

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
        _mfForegrounds.syncWith(pOther->_mfForegrounds, sInfo);

    if(FieldBits::NoField != (InternalActiveForegroundsFieldMask & whichField))
        _mfInternalActiveForegrounds.syncWith(pOther->_mfInternalActiveForegrounds, sInfo);

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
        _mfModelNodes.syncWith(pOther->_mfModelNodes, sInfo);

    if(FieldBits::NoField != (InternalActiveModelNodesFieldMask & whichField))
        _mfInternalActiveModelNodes.syncWith(pOther->_mfInternalActiveModelNodes, sInfo);

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
        _mfCameras.syncWith(pOther->_mfCameras, sInfo);


}

void ProjectBase::execBeginEditImpl (const BitVector &whichField, 
                                                 ::osg::UInt32     uiAspect,
                                                 ::osg::UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

    if(FieldBits::NoField != (ScenesFieldMask & whichField))
        _mfScenes.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (BackgroundsFieldMask & whichField))
        _mfBackgrounds.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (ForegroundsFieldMask & whichField))
        _mfForegrounds.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (InternalActiveForegroundsFieldMask & whichField))
        _mfInternalActiveForegrounds.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (ModelNodesFieldMask & whichField))
        _mfModelNodes.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (InternalActiveModelNodesFieldMask & whichField))
        _mfInternalActiveModelNodes.beginEdit(uiAspect, uiContainerSize);

    if(FieldBits::NoField != (CamerasFieldMask & whichField))
        _mfCameras.beginEdit(uiAspect, uiContainerSize);

}
#endif



#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<ProjectPtr>::_type("ProjectPtr", "FieldContainerPtr");
#endif

KE_BEGIN_NAMESPACE

OSG_DLLEXPORT_SFIELD_DEF1(ProjectPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(ProjectPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);

KE_END_NAMESPACE


