/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ProjectEvent!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>




#include "KEProjectEventBase.h"
#include "KEProjectEvent.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ProjectEvent
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<ProjectEvent *>::_type("ProjectEventPtr", "EventPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(ProjectEvent *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ProjectEvent *,
                           0);


/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ProjectEventBase::classDescInserter(TypeObject &oType)
{
}


ProjectEventBase::TypeObject ProjectEventBase::_type(
    ProjectEventBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&ProjectEventBase::createEmptyLocal),
    ProjectEvent::initMethod,
    ProjectEvent::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ProjectEvent::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"ProjectEvent\"\n"
    "\tparent=\"Event\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"single\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"true\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ProjectEventBase::getType(void)
{
    return _type;
}

const FieldContainerType &ProjectEventBase::getType(void) const
{
    return _type;
}

UInt32 ProjectEventBase::getContainerSize(void) const
{
    return sizeof(ProjectEvent);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 ProjectEventBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void ProjectEventBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void ProjectEventBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
ProjectEventTransitPtr ProjectEventBase::createLocal(BitVector bFlags)
{
    ProjectEventTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ProjectEvent>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ProjectEventTransitPtr ProjectEventBase::createDependent(BitVector bFlags)
{
    ProjectEventTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ProjectEvent>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ProjectEventTransitPtr ProjectEventBase::create(void)
{
    ProjectEventTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ProjectEvent>(tmpPtr);
    }

    return fc;
}

ProjectEvent *ProjectEventBase::createEmptyLocal(BitVector bFlags)
{
    ProjectEvent *returnValue;

    newPtr<ProjectEvent>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ProjectEvent *ProjectEventBase::createEmpty(void)
{
    ProjectEvent *returnValue;

    newPtr<ProjectEvent>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ProjectEventBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ProjectEvent *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ProjectEvent *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ProjectEventBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ProjectEvent *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ProjectEvent *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ProjectEventBase::shallowCopy(void) const
{
    ProjectEvent *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ProjectEvent *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

ProjectEventBase::ProjectEventBase(void) :
    Inherited()
{
}

ProjectEventBase::ProjectEventBase(const ProjectEventBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

ProjectEventBase::~ProjectEventBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void ProjectEventBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ProjectEvent *pThis = static_cast<ProjectEvent *>(this);

    pThis->execSync(static_cast<ProjectEvent *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ProjectEventBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ProjectEvent *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ProjectEvent *>(pRefAspect),
                  dynamic_cast<const ProjectEvent *>(this));

    return returnValue;
}
#endif

void ProjectEventBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
