/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ChangeSceneActivity!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>



#include "Project/Scene/KEScene.h"      // GotoScene Class

#include "KEChangeSceneActivityBase.h"
#include "KEChangeSceneActivity.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ChangeSceneActivity
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var Scene *         ChangeSceneActivityBase::_sfGotoScene
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<ChangeSceneActivity *>::_type("ChangeSceneActivityPtr", "ActivityPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(ChangeSceneActivity *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ChangeSceneActivity *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ChangeSceneActivity *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ChangeSceneActivityBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecScenePtr::Description(
        SFUnrecScenePtr::getClassType(),
        "GotoScene",
        "",
        GotoSceneFieldId, GotoSceneFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&ChangeSceneActivity::editHandleGotoScene),
        static_cast<FieldGetMethodSig >(&ChangeSceneActivity::getHandleGotoScene));

    oType.addInitialDesc(pDesc);
}


ChangeSceneActivityBase::TypeObject ChangeSceneActivityBase::_type(
    ChangeSceneActivityBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&ChangeSceneActivityBase::createEmptyLocal),
    ChangeSceneActivity::initMethod,
    ChangeSceneActivity::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ChangeSceneActivity::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"ChangeSceneActivity\"\n"
    "\tparent=\"Activity\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"true\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "\t<Field\n"
    "\t\tname=\"GotoScene\"\n"
    "\t\ttype=\"Scene\"\n"
    "\t\tcategory=\"pointer\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\tfieldHeader=\"Project/Scene/KESceneFields.h\"\n"
    "\t\ttypeHeader=\"Project/Scene/KEScene.h\"\n"
    "\t\taccess=\"public\"\n"
    "\t\tdefaultValue=\"NULL\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ChangeSceneActivityBase::getType(void)
{
    return _type;
}

const FieldContainerType &ChangeSceneActivityBase::getType(void) const
{
    return _type;
}

UInt32 ChangeSceneActivityBase::getContainerSize(void) const
{
    return sizeof(ChangeSceneActivity);
}

/*------------------------- decorator get ------------------------------*/


//! Get the ChangeSceneActivity::_sfGotoScene field.
const SFUnrecScenePtr *ChangeSceneActivityBase::getSFGotoScene(void) const
{
    return &_sfGotoScene;
}

SFUnrecScenePtr     *ChangeSceneActivityBase::editSFGotoScene      (void)
{
    editSField(GotoSceneFieldMask);

    return &_sfGotoScene;
}





/*------------------------------ access -----------------------------------*/

UInt32 ChangeSceneActivityBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (GotoSceneFieldMask & whichField))
    {
        returnValue += _sfGotoScene.getBinSize();
    }

    return returnValue;
}

void ChangeSceneActivityBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (GotoSceneFieldMask & whichField))
    {
        _sfGotoScene.copyToBin(pMem);
    }
}

void ChangeSceneActivityBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (GotoSceneFieldMask & whichField))
    {
        _sfGotoScene.copyFromBin(pMem);
    }
}

//! create a new instance of the class
ChangeSceneActivityTransitPtr ChangeSceneActivityBase::createLocal(BitVector bFlags)
{
    ChangeSceneActivityTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ChangeSceneActivity>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ChangeSceneActivityTransitPtr ChangeSceneActivityBase::createDependent(BitVector bFlags)
{
    ChangeSceneActivityTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ChangeSceneActivity>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ChangeSceneActivityTransitPtr ChangeSceneActivityBase::create(void)
{
    ChangeSceneActivityTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ChangeSceneActivity>(tmpPtr);
    }

    return fc;
}

ChangeSceneActivity *ChangeSceneActivityBase::createEmptyLocal(BitVector bFlags)
{
    ChangeSceneActivity *returnValue;

    newPtr<ChangeSceneActivity>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ChangeSceneActivity *ChangeSceneActivityBase::createEmpty(void)
{
    ChangeSceneActivity *returnValue;

    newPtr<ChangeSceneActivity>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ChangeSceneActivityBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ChangeSceneActivity *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ChangeSceneActivity *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ChangeSceneActivityBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ChangeSceneActivity *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ChangeSceneActivity *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ChangeSceneActivityBase::shallowCopy(void) const
{
    ChangeSceneActivity *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ChangeSceneActivity *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

ChangeSceneActivityBase::ChangeSceneActivityBase(void) :
    Inherited(),
    _sfGotoScene              (NULL)
{
}

ChangeSceneActivityBase::ChangeSceneActivityBase(const ChangeSceneActivityBase &source) :
    Inherited(source),
    _sfGotoScene              (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

ChangeSceneActivityBase::~ChangeSceneActivityBase(void)
{
}

void ChangeSceneActivityBase::onCreate(const ChangeSceneActivity *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        ChangeSceneActivity *pThis = static_cast<ChangeSceneActivity *>(this);

        pThis->setGotoScene(source->getGotoScene());
    }
}

GetFieldHandlePtr ChangeSceneActivityBase::getHandleGotoScene       (void) const
{
    SFUnrecScenePtr::GetHandlePtr returnValue(
        new  SFUnrecScenePtr::GetHandle(
             &_sfGotoScene,
             this->getType().getFieldDesc(GotoSceneFieldId),
             const_cast<ChangeSceneActivityBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ChangeSceneActivityBase::editHandleGotoScene      (void)
{
    SFUnrecScenePtr::EditHandlePtr returnValue(
        new  SFUnrecScenePtr::EditHandle(
             &_sfGotoScene,
             this->getType().getFieldDesc(GotoSceneFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&ChangeSceneActivity::setGotoScene,
                    static_cast<ChangeSceneActivity *>(this), _1));

    editSField(GotoSceneFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void ChangeSceneActivityBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ChangeSceneActivity *pThis = static_cast<ChangeSceneActivity *>(this);

    pThis->execSync(static_cast<ChangeSceneActivity *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ChangeSceneActivityBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ChangeSceneActivity *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ChangeSceneActivity *>(pRefAspect),
                  dynamic_cast<const ChangeSceneActivity *>(this));

    return returnValue;
}
#endif

void ChangeSceneActivityBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<ChangeSceneActivity *>(this)->setGotoScene(NULL);


}


OSG_END_NAMESPACE
