/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                                                                           *
 *   contact: djkabala@gmail.com                                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ChangeSceneActivity!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILECHANGESCENEACTIVITYINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "KEChangeSceneActivityBase.h"
#include "KEChangeSceneActivity.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  ChangeSceneActivityBase::GotoSceneFieldMask = 
    (TypeTraits<BitVector>::One << ChangeSceneActivityBase::GotoSceneFieldId);

const OSG::BitVector ChangeSceneActivityBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var ScenePtr        ChangeSceneActivityBase::_sfGotoScene
    
*/

//! ChangeSceneActivity description

FieldDescription *ChangeSceneActivityBase::_desc[] = 
{
    new FieldDescription(SFScenePtr::getClassType(), 
                     "GotoScene", 
                     GotoSceneFieldId, GotoSceneFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&ChangeSceneActivityBase::editSFGotoScene))
};


FieldContainerType ChangeSceneActivityBase::_type(
    "ChangeSceneActivity",
    "Activity",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&ChangeSceneActivityBase::createEmpty),
    ChangeSceneActivity::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(ChangeSceneActivityBase, ChangeSceneActivityPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &ChangeSceneActivityBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &ChangeSceneActivityBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr ChangeSceneActivityBase::shallowCopy(void) const 
{ 
    ChangeSceneActivityPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const ChangeSceneActivity *>(this)); 

    return returnValue; 
}

UInt32 ChangeSceneActivityBase::getContainerSize(void) const 
{ 
    return sizeof(ChangeSceneActivity); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void ChangeSceneActivityBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<ChangeSceneActivityBase *>(&other),
                          whichField);
}
#else
void ChangeSceneActivityBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((ChangeSceneActivityBase *) &other, whichField, sInfo);
}
void ChangeSceneActivityBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void ChangeSceneActivityBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

ChangeSceneActivityBase::ChangeSceneActivityBase(void) :
    _sfGotoScene              (ScenePtr(NullFC)), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

ChangeSceneActivityBase::ChangeSceneActivityBase(const ChangeSceneActivityBase &source) :
    _sfGotoScene              (source._sfGotoScene              ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

ChangeSceneActivityBase::~ChangeSceneActivityBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 ChangeSceneActivityBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (GotoSceneFieldMask & whichField))
    {
        returnValue += _sfGotoScene.getBinSize();
    }


    return returnValue;
}

void ChangeSceneActivityBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (GotoSceneFieldMask & whichField))
    {
        _sfGotoScene.copyToBin(pMem);
    }


}

void ChangeSceneActivityBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (GotoSceneFieldMask & whichField))
    {
        _sfGotoScene.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void ChangeSceneActivityBase::executeSyncImpl(      ChangeSceneActivityBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (GotoSceneFieldMask & whichField))
        _sfGotoScene.syncWith(pOther->_sfGotoScene);


}
#else
void ChangeSceneActivityBase::executeSyncImpl(      ChangeSceneActivityBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (GotoSceneFieldMask & whichField))
        _sfGotoScene.syncWith(pOther->_sfGotoScene);



}

void ChangeSceneActivityBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<ChangeSceneActivityPtr>::_type("ChangeSceneActivityPtr", "ActivityPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(ChangeSceneActivityPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(ChangeSceneActivityPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);


OSG_END_NAMESPACE

