/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala (dkabala@vrac.iastate.edu)                        *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class BackgroundsListComponentGenerator
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEBACKGROUNDSLISTCOMPONENTGENERATORBASE_H_
#define _KEBACKGROUNDSLISTCOMPONENTGENERATORBASE_H_
#ifdef __sgi
#pragma once
#endif


#include "KEConfig.h"
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGBaseTypes.h>
#include <OpenSG/OSGRefPtr.h>
#include <OpenSG/OSGCoredNodePtr.h>

#include <OpenSG/UserInterface/OSGListComponentGenerator.h> // Parent
#include <OpenSG/OSGVec2fFields.h> // IconSize type

#include "KEBackgroundsListComponentGeneratorFields.h"

OSG_USING_NAMESPACE
KE_BEGIN_NAMESPACE

class BackgroundsListComponentGenerator;
class osg::BinaryDataHandler;

//! \brief BackgroundsListComponentGenerator Base Class.

class KE_KABALAENGINELIB_DLLMAPPING BackgroundsListComponentGeneratorBase : public ListComponentGenerator
{
  private:

    typedef ListComponentGenerator    Inherited;

    /*==========================  PUBLIC  =================================*/
  public:

    typedef BackgroundsListComponentGeneratorPtr  Ptr;

    enum
    {
        IconSizeFieldId = Inherited::NextFieldId,
        NextFieldId     = IconSizeFieldId + 1
    };

    static const OSG::BitVector IconSizeFieldMask;


    static const OSG::BitVector MTInfluenceMask;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static        FieldContainerType &getClassType    (void); 
    static        ::osg::UInt32              getClassTypeId  (void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType  (void); 
    virtual const FieldContainerType &getType  (void) const; 

    virtual       ::osg::UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

           SFVec2f             *getSFIconSize       (void);

           Vec2f               &getIconSize       (void);
     const Vec2f               &getIconSize       (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

     void setIconSize       ( const Vec2f &value );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual ::osg::UInt32 getBinSize (const BitVector         &whichField);
    virtual void   copyToBin  (      BinaryDataHandler &pMem,
                               const BitVector         &whichField);
    virtual void   copyFromBin(      BinaryDataHandler &pMem,
                               const BitVector         &whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  BackgroundsListComponentGeneratorPtr      create          (void); 
    static  BackgroundsListComponentGeneratorPtr      createEmpty     (void); 

    /*! \}                                                                 */

    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerPtr     shallowCopy     (void) const; 

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/
  protected:

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFVec2f             _sfIconSize;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    BackgroundsListComponentGeneratorBase(void);
    BackgroundsListComponentGeneratorBase(const BackgroundsListComponentGeneratorBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~BackgroundsListComponentGeneratorBase(void); 

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#if !defined(OSG_FIXED_MFIELDSYNC)
    void executeSyncImpl(      BackgroundsListComponentGeneratorBase *pOther,
                         const BitVector         &whichField);

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField);
#else
    void executeSyncImpl(      BackgroundsListComponentGeneratorBase *pOther,
                         const BitVector         &whichField,
                         const SyncInfo          &sInfo     );

    virtual void   executeSync(      FieldContainer    &other,
                               const BitVector         &whichField,
                               const SyncInfo          &sInfo);

    virtual void execBeginEdit     (const BitVector &whichField,
                                          ::osg::UInt32     uiAspect,
                                          ::osg::UInt32     uiContainerSize);

            void execBeginEditImpl (const BitVector &whichField,
                                          ::osg::UInt32     uiAspect,
                                          ::osg::UInt32     uiContainerSize);

    virtual void onDestroyAspect(::osg::UInt32 uiId, ::osg::UInt32 uiAspect);
#endif

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/
  private:

    friend class FieldContainer;

    static FieldDescription   *_desc[];
    static FieldContainerType  _type;


    // prohibit default functions (move to 'public' if you need one)
    void operator =(const BackgroundsListComponentGeneratorBase &source);
};

//---------------------------------------------------------------------------
//   Exported Types
//---------------------------------------------------------------------------


typedef BackgroundsListComponentGeneratorBase *BackgroundsListComponentGeneratorBaseP;

typedef osgIF<BackgroundsListComponentGeneratorBase::isNodeCore,
              CoredNodePtr<BackgroundsListComponentGenerator>,
              FieldContainer::attempt_to_create_CoredNodePtr_on_non_NodeCore_FC
              >::_IRet BackgroundsListComponentGeneratorNodePtr;

typedef RefPtr<BackgroundsListComponentGeneratorPtr> BackgroundsListComponentGeneratorRefPtr;

KE_END_NAMESPACE

#endif /* _KEBACKGROUNDSLISTCOMPONENTGENERATORBASE_H_ */
