/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala (dkabala@vrac.iastate.edu)                        *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class SceneBackgroundsEditor!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILESCENEBACKGROUNDSEDITORINST

#include <stdlib.h>
#include <stdio.h>

#include "KEConfig.h"

#include "KESceneBackgroundsEditorBase.h"
#include "KESceneBackgroundsEditor.h"


KE_USING_NAMESPACE

const OSG::BitVector  SceneBackgroundsEditorBase::EditingBackgroundFieldMask = 
    (TypeTraits<BitVector>::One << SceneBackgroundsEditorBase::EditingBackgroundFieldId);

const OSG::BitVector SceneBackgroundsEditorBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var BackgroundPtr   SceneBackgroundsEditorBase::_sfEditingBackground
    
*/

//! SceneBackgroundsEditor description

FieldDescription *SceneBackgroundsEditorBase::_desc[] = 
{
    new FieldDescription(SFBackgroundPtr::getClassType(), 
                     "EditingBackground", 
                     EditingBackgroundFieldId, EditingBackgroundFieldMask,
                     false,
                     (FieldAccessMethod) &SceneBackgroundsEditorBase::getSFEditingBackground)
};


FieldContainerType SceneBackgroundsEditorBase::_type(
    "SceneBackgroundsEditor",
    "SceneComponentEditor",
    NULL,
    (PrototypeCreateF) &SceneBackgroundsEditorBase::createEmpty,
    SceneBackgroundsEditor::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(SceneBackgroundsEditorBase, SceneBackgroundsEditorPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &SceneBackgroundsEditorBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &SceneBackgroundsEditorBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr SceneBackgroundsEditorBase::shallowCopy(void) const 
{ 
    SceneBackgroundsEditorPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const SceneBackgroundsEditor *>(this)); 

    return returnValue; 
}

::osg::UInt32 SceneBackgroundsEditorBase::getContainerSize(void) const 
{ 
    return sizeof(SceneBackgroundsEditor); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void SceneBackgroundsEditorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((SceneBackgroundsEditorBase *) &other, whichField);
}
#else
void SceneBackgroundsEditorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((SceneBackgroundsEditorBase *) &other, whichField, sInfo);
}
void SceneBackgroundsEditorBase::execBeginEdit(const BitVector &whichField, 
                                            ::osg::UInt32     uiAspect,
                                            ::osg::UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void SceneBackgroundsEditorBase::onDestroyAspect(::osg::UInt32 uiId, ::osg::UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

SceneBackgroundsEditorBase::SceneBackgroundsEditorBase(void) :
    _sfEditingBackground      (BackgroundPtr(NullFC)), 
    Inherited() 
{
}

SceneBackgroundsEditorBase::SceneBackgroundsEditorBase(const SceneBackgroundsEditorBase &source) :
    _sfEditingBackground      (source._sfEditingBackground      ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

SceneBackgroundsEditorBase::~SceneBackgroundsEditorBase(void)
{
}

/*------------------------------ access -----------------------------------*/

::osg::UInt32 SceneBackgroundsEditorBase::getBinSize(const BitVector &whichField)
{
    ::osg::UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EditingBackgroundFieldMask & whichField))
    {
        returnValue += _sfEditingBackground.getBinSize();
    }


    return returnValue;
}

void SceneBackgroundsEditorBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EditingBackgroundFieldMask & whichField))
    {
        _sfEditingBackground.copyToBin(pMem);
    }


}

void SceneBackgroundsEditorBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EditingBackgroundFieldMask & whichField))
    {
        _sfEditingBackground.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void SceneBackgroundsEditorBase::executeSyncImpl(      SceneBackgroundsEditorBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (EditingBackgroundFieldMask & whichField))
        _sfEditingBackground.syncWith(pOther->_sfEditingBackground);


}
#else
void SceneBackgroundsEditorBase::executeSyncImpl(      SceneBackgroundsEditorBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (EditingBackgroundFieldMask & whichField))
        _sfEditingBackground.syncWith(pOther->_sfEditingBackground);



}

void SceneBackgroundsEditorBase::execBeginEditImpl (const BitVector &whichField, 
                                                 ::osg::UInt32     uiAspect,
                                                 ::osg::UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<SceneBackgroundsEditorPtr>::_type("SceneBackgroundsEditorPtr", "SceneComponentEditorPtr");
#endif

KE_BEGIN_NAMESPACE

OSG_DLLEXPORT_SFIELD_DEF1(SceneBackgroundsEditorPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(SceneBackgroundsEditorPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);

KE_END_NAMESPACE


