/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                                                                           *
 *   contact: djkabala@gmail.com                                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class FieldContainerTypeComponentGenerator!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILEFIELDCONTAINERTYPECOMPONENTGENERATORINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "KEFieldContainerTypeComponentGeneratorBase.h"
#include "KEFieldContainerTypeComponentGenerator.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  FieldContainerTypeComponentGeneratorBase::IconSizeFieldMask = 
    (TypeTraits<BitVector>::One << FieldContainerTypeComponentGeneratorBase::IconSizeFieldId);

const OSG::BitVector FieldContainerTypeComponentGeneratorBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var Vec2f           FieldContainerTypeComponentGeneratorBase::_sfIconSize
    
*/

//! FieldContainerTypeComponentGenerator description

FieldDescription *FieldContainerTypeComponentGeneratorBase::_desc[] = 
{
    new FieldDescription(SFVec2f::getClassType(), 
                     "IconSize", 
                     IconSizeFieldId, IconSizeFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&FieldContainerTypeComponentGeneratorBase::editSFIconSize))
};


FieldContainerType FieldContainerTypeComponentGeneratorBase::_type(
    "FieldContainerTypeComponentGenerator",
    "ListComponentGenerator",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&FieldContainerTypeComponentGeneratorBase::createEmpty),
    FieldContainerTypeComponentGenerator::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(FieldContainerTypeComponentGeneratorBase, FieldContainerTypeComponentGeneratorPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &FieldContainerTypeComponentGeneratorBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &FieldContainerTypeComponentGeneratorBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr FieldContainerTypeComponentGeneratorBase::shallowCopy(void) const 
{ 
    FieldContainerTypeComponentGeneratorPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const FieldContainerTypeComponentGenerator *>(this)); 

    return returnValue; 
}

UInt32 FieldContainerTypeComponentGeneratorBase::getContainerSize(void) const 
{ 
    return sizeof(FieldContainerTypeComponentGenerator); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void FieldContainerTypeComponentGeneratorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<FieldContainerTypeComponentGeneratorBase *>(&other),
                          whichField);
}
#else
void FieldContainerTypeComponentGeneratorBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((FieldContainerTypeComponentGeneratorBase *) &other, whichField, sInfo);
}
void FieldContainerTypeComponentGeneratorBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void FieldContainerTypeComponentGeneratorBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

FieldContainerTypeComponentGeneratorBase::FieldContainerTypeComponentGeneratorBase(void) :
    _sfIconSize               (Vec2f(30.0,30.0)), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

FieldContainerTypeComponentGeneratorBase::FieldContainerTypeComponentGeneratorBase(const FieldContainerTypeComponentGeneratorBase &source) :
    _sfIconSize               (source._sfIconSize               ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

FieldContainerTypeComponentGeneratorBase::~FieldContainerTypeComponentGeneratorBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 FieldContainerTypeComponentGeneratorBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (IconSizeFieldMask & whichField))
    {
        returnValue += _sfIconSize.getBinSize();
    }


    return returnValue;
}

void FieldContainerTypeComponentGeneratorBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (IconSizeFieldMask & whichField))
    {
        _sfIconSize.copyToBin(pMem);
    }


}

void FieldContainerTypeComponentGeneratorBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (IconSizeFieldMask & whichField))
    {
        _sfIconSize.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void FieldContainerTypeComponentGeneratorBase::executeSyncImpl(      FieldContainerTypeComponentGeneratorBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (IconSizeFieldMask & whichField))
        _sfIconSize.syncWith(pOther->_sfIconSize);


}
#else
void FieldContainerTypeComponentGeneratorBase::executeSyncImpl(      FieldContainerTypeComponentGeneratorBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (IconSizeFieldMask & whichField))
        _sfIconSize.syncWith(pOther->_sfIconSize);



}

void FieldContainerTypeComponentGeneratorBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<FieldContainerTypeComponentGeneratorPtr>::_type("FieldContainerTypeComponentGeneratorPtr", "ListComponentGeneratorPtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(FieldContainerTypeComponentGeneratorPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(FieldContainerTypeComponentGeneratorPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);

OSG_END_NAMESPACE

