/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  Robert Goetz (rdgoetz@iastate.edu)                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEANIMATIONEFFECTFIELDS_H_
#define _KEANIMATIONEFFECTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class AnimationEffect;

OSG_GEN_CONTAINERPTR(AnimationEffect);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<AnimationEffect *> :
    public FieldTraitsFCPtrBase<AnimationEffect *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<AnimationEffect *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFAnimationEffectPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFAnimationEffectPtr"; }
};

template<> inline
const Char8 *FieldTraits<AnimationEffect *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecAnimationEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimationEffect *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecAnimationEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimationEffect *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakAnimationEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimationEffect *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdAnimationEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimationEffect *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecAnimationEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimationEffect *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecAnimationEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimationEffect *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakAnimationEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<AnimationEffect *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdAnimationEffectPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<AnimationEffect *,
                      RecordedRefCountPolicy  > SFRecAnimationEffectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<AnimationEffect *,
                      UnrecordedRefCountPolicy> SFUnrecAnimationEffectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<AnimationEffect *,
                      WeakRefCountPolicy      > SFWeakAnimationEffectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<AnimationEffect *,
                      NoRefCountPolicy        > SFUncountedAnimationEffectPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<AnimationEffect *,
                      RecordedRefCountPolicy  > MFRecAnimationEffectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<AnimationEffect *,
                      UnrecordedRefCountPolicy> MFUnrecAnimationEffectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<AnimationEffect *,
                      WeakRefCountPolicy      > MFWeakAnimationEffectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<AnimationEffect *,
                      NoRefCountPolicy        > MFUncountedAnimationEffectPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecAnimationEffectPtr : 
    public PointerSField<AnimationEffect *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecAnimationEffectPtr : 
    public PointerSField<AnimationEffect *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakAnimationEffectPtr :
    public PointerSField<AnimationEffect *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedAnimationEffectPtr :
    public PointerSField<AnimationEffect *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecAnimationEffectPtr :
    public PointerMField<AnimationEffect *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecAnimationEffectPtr :
    public PointerMField<AnimationEffect *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakAnimationEffectPtr :
    public PointerMField<AnimationEffect *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedAnimationEffectPtr :
    public PointerMField<AnimationEffect *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEANIMATIONEFFECTFIELDS_H_ */
