/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  Robert Goetz (rdgoetz@iastate.edu)                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KECONCURRENTEFFECTGROUPFIELDS_H_
#define _KECONCURRENTEFFECTGROUPFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class ConcurrentEffectGroup;

OSG_GEN_CONTAINERPTR(ConcurrentEffectGroup);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<ConcurrentEffectGroup *> :
    public FieldTraitsFCPtrBase<ConcurrentEffectGroup *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ConcurrentEffectGroup *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFConcurrentEffectGroupPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFConcurrentEffectGroupPtr"; }
};

template<> inline
const Char8 *FieldTraits<ConcurrentEffectGroup *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecConcurrentEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConcurrentEffectGroup *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecConcurrentEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConcurrentEffectGroup *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakConcurrentEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConcurrentEffectGroup *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdConcurrentEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConcurrentEffectGroup *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecConcurrentEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConcurrentEffectGroup *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecConcurrentEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConcurrentEffectGroup *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakConcurrentEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<ConcurrentEffectGroup *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdConcurrentEffectGroupPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ConcurrentEffectGroup *,
                      RecordedRefCountPolicy  > SFRecConcurrentEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ConcurrentEffectGroup *,
                      UnrecordedRefCountPolicy> SFUnrecConcurrentEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ConcurrentEffectGroup *,
                      WeakRefCountPolicy      > SFWeakConcurrentEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ConcurrentEffectGroup *,
                      NoRefCountPolicy        > SFUncountedConcurrentEffectGroupPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ConcurrentEffectGroup *,
                      RecordedRefCountPolicy  > MFRecConcurrentEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ConcurrentEffectGroup *,
                      UnrecordedRefCountPolicy> MFUnrecConcurrentEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ConcurrentEffectGroup *,
                      WeakRefCountPolicy      > MFWeakConcurrentEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ConcurrentEffectGroup *,
                      NoRefCountPolicy        > MFUncountedConcurrentEffectGroupPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecConcurrentEffectGroupPtr : 
    public PointerSField<ConcurrentEffectGroup *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecConcurrentEffectGroupPtr : 
    public PointerSField<ConcurrentEffectGroup *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakConcurrentEffectGroupPtr :
    public PointerSField<ConcurrentEffectGroup *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedConcurrentEffectGroupPtr :
    public PointerSField<ConcurrentEffectGroup *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecConcurrentEffectGroupPtr :
    public PointerMField<ConcurrentEffectGroup *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecConcurrentEffectGroupPtr :
    public PointerMField<ConcurrentEffectGroup *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakConcurrentEffectGroupPtr :
    public PointerMField<ConcurrentEffectGroup *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedConcurrentEffectGroupPtr :
    public PointerMField<ConcurrentEffectGroup *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KECONCURRENTEFFECTGROUPFIELDS_H_ */
