/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  Robert Goetz (rdgoetz@iastate.edu)                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class Effect
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEEFFECTBASE_H_
#define _KEEFFECTBASE_H_
#ifdef __sgi
#pragma once
#endif



#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"
#include "KEConfig.h"

//#include "OpenSG/OSGBaseTypes.h"


#include <OpenSG/OSGAttachmentContainer.h> // Parent

#include <OpenSG/OSGFieldContainerFields.h> // ParentSceneObject type

#include "KEEffectFields.h"

//Event Producer Headers
#include <OpenSG/OSGActivity.h>
#include <OpenSG/OSGConsumableEventCombiner.h>

#include "Project/Effect/KEEffectEventDetailsFields.h"

OSG_BEGIN_NAMESPACE

class Effect;

//! \brief Effect Base Class.

class KE_KABALAENGINE_DLLMAPPING EffectBase : public AttachmentContainer
{
  public:

    typedef AttachmentContainer Inherited;
    typedef AttachmentContainer ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(Effect);
    
    
    typedef EffectEventDetails EffectBeganEventDetailsType;
    typedef EffectEventDetails EffectPausedEventDetailsType;
    typedef EffectEventDetails EffectUnpausedEventDetailsType;
    typedef EffectEventDetails EffectFinishedEventDetailsType;
    typedef EffectEventDetails EffectStoppedEventDetailsType;

    typedef boost::signals2::signal<void (EventDetails* const            , UInt32)> BaseEventType;
    typedef boost::signals2::signal<void (EffectEventDetails* const, UInt32), ConsumableEventCombiner> EffectBeganEventType;
    typedef boost::signals2::signal<void (EffectEventDetails* const, UInt32), ConsumableEventCombiner> EffectPausedEventType;
    typedef boost::signals2::signal<void (EffectEventDetails* const, UInt32), ConsumableEventCombiner> EffectUnpausedEventType;
    typedef boost::signals2::signal<void (EffectEventDetails* const, UInt32), ConsumableEventCombiner> EffectFinishedEventType;
    typedef boost::signals2::signal<void (EffectEventDetails* const, UInt32), ConsumableEventCombiner> EffectStoppedEventType;

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        ParentSceneObjectFieldId = Inherited::NextFieldId,
        NextFieldId = ParentSceneObjectFieldId + 1
    };

    static const OSG::BitVector ParentSceneObjectFieldMask =
        (TypeTraits<BitVector>::One << ParentSceneObjectFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef SFParentFieldContainerPtr SFParentSceneObjectType;

    enum
    {
        EffectBeganEventId = 1,
        EffectPausedEventId = EffectBeganEventId + 1,
        EffectUnpausedEventId = EffectPausedEventId + 1,
        EffectFinishedEventId = EffectUnpausedEventId + 1,
        EffectStoppedEventId = EffectFinishedEventId + 1,
        NextProducedEventId = EffectStoppedEventId + 1
    };

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);
    static const  EventProducerType  &getProducerClassType  (void);
    static        UInt32              getProducerClassTypeId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Event Produced Get                           */
    /*! \{                                                                 */

    virtual const EventProducerType &getProducerType(void) const; 

    virtual boost::signals2::connection attachActivity(UInt32 eventId,
                                                       Activity* TheActivity);
                                                         
    virtual UInt32                   getNumProducedEvents       (void                                ) const;
    virtual const EventDescription *getProducedEventDescription(const std::string &ProducedEventName) const;
    virtual const EventDescription *getProducedEventDescription(UInt32 ProducedEventId              ) const;
    virtual UInt32                   getProducedEventId         (const std::string &ProducedEventName) const;
    
    virtual boost::signals2::connection connectEvent(UInt32 eventId, 
                                              const BaseEventType::slot_type &listener,
                                              boost::signals2::connect_position at= boost::signals2::at_back);
                                              
    virtual boost::signals2::connection connectEvent(UInt32 eventId, 
                                              const BaseEventType::group_type &group,
                                              const BaseEventType::slot_type &listener,
                                              boost::signals2::connect_position at= boost::signals2::at_back);
    
    virtual void   disconnectEvent        (UInt32 eventId, const BaseEventType::group_type &group);
    virtual void   disconnectAllSlotsEvent(UInt32 eventId);
    virtual bool   isEmptyEvent           (UInt32 eventId) const;
    virtual UInt32 numSlotsEvent          (UInt32 eventId) const;

    /*! \}                                                                 */
    /*! \name                Event Access                                 */
    /*! \{                                                                 */
    
    //EffectBegan
    boost::signals2::connection connectEffectBegan    (const EffectBeganEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectEffectBegan    (const EffectBeganEventType::group_type &group,
                                                       const EffectBeganEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectEffectBegan            (const EffectBeganEventType::group_type &group);
    void   disconnectAllSlotsEffectBegan    (void);
    bool   isEmptyEffectBegan               (void) const;
    UInt32 numSlotsEffectBegan              (void) const;
    
    //EffectPaused
    boost::signals2::connection connectEffectPaused   (const EffectPausedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectEffectPaused   (const EffectPausedEventType::group_type &group,
                                                       const EffectPausedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectEffectPaused           (const EffectPausedEventType::group_type &group);
    void   disconnectAllSlotsEffectPaused   (void);
    bool   isEmptyEffectPaused              (void) const;
    UInt32 numSlotsEffectPaused             (void) const;
    
    //EffectUnpaused
    boost::signals2::connection connectEffectUnpaused (const EffectUnpausedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectEffectUnpaused (const EffectUnpausedEventType::group_type &group,
                                                       const EffectUnpausedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectEffectUnpaused         (const EffectUnpausedEventType::group_type &group);
    void   disconnectAllSlotsEffectUnpaused (void);
    bool   isEmptyEffectUnpaused            (void) const;
    UInt32 numSlotsEffectUnpaused           (void) const;
    
    //EffectFinished
    boost::signals2::connection connectEffectFinished (const EffectFinishedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectEffectFinished (const EffectFinishedEventType::group_type &group,
                                                       const EffectFinishedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectEffectFinished         (const EffectFinishedEventType::group_type &group);
    void   disconnectAllSlotsEffectFinished (void);
    bool   isEmptyEffectFinished            (void) const;
    UInt32 numSlotsEffectFinished           (void) const;
    
    //EffectStopped
    boost::signals2::connection connectEffectStopped  (const EffectStoppedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    boost::signals2::connection connectEffectStopped  (const EffectStoppedEventType::group_type &group,
                                                       const EffectStoppedEventType::slot_type &listener,
                                                       boost::signals2::connect_position at= boost::signals2::at_back);
    void   disconnectEffectStopped          (const EffectStoppedEventType::group_type &group);
    void   disconnectAllSlotsEffectStopped  (void);
    bool   isEmptyEffectStopped             (void) const;
    UInt32 numSlotsEffectStopped            (void) const;
    
    
    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:
    /*---------------------------------------------------------------------*/
    /*! \name                    Produced Event Signals                   */
    /*! \{                                                                 */

    //Event Event producers
    EffectBeganEventType _EffectBeganEvent;
    EffectPausedEventType _EffectPausedEvent;
    EffectUnpausedEventType _EffectUnpausedEvent;
    EffectFinishedEventType _EffectFinishedEvent;
    EffectStoppedEventType _EffectStoppedEvent;
    /*! \}                                                                 */

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    SFParentFieldContainerPtr _sfParentSceneObject;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    EffectBase(void);
    EffectBase(const EffectBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~EffectBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name Parent linking                                               */
    /*! \{                                                                 */

    virtual bool linkParent  (FieldContainer * const pParent,
                              UInt16           const childFieldId,
                              UInt16           const parentFieldId);
    virtual bool unlinkParent(FieldContainer * const pParent,
                              UInt16           const parentFieldId);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandleParentSceneObject (void) const;
    EditFieldHandlePtr editHandleParentSceneObject(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Event Access                     */
    /*! \{                                                                 */

    GetEventHandlePtr getHandleEffectBeganSignal(void) const;
    GetEventHandlePtr getHandleEffectPausedSignal(void) const;
    GetEventHandlePtr getHandleEffectUnpausedSignal(void) const;
    GetEventHandlePtr getHandleEffectFinishedSignal(void) const;
    GetEventHandlePtr getHandleEffectStoppedSignal(void) const;
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Event Producer Firing                    */
    /*! \{                                                                 */

    virtual void produceEvent       (UInt32 eventId, EventDetails* const e);
    
    void produceEffectBegan         (EffectBeganEventDetailsType* const e);
    void produceEffectPaused        (EffectPausedEventDetailsType* const e);
    void produceEffectUnpaused      (EffectUnpausedEventDetailsType* const e);
    void produceEffectFinished      (EffectFinishedEventDetailsType* const e);
    void produceEffectStopped       (EffectStoppedEventDetailsType* const e);
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      EffectBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/
    static EventDescription   *_eventDesc[];
    static EventProducerType _producerType;


    // prohibit default functions (move to 'public' if you need one)
    void operator =(const EffectBase &source);
};

typedef EffectBase *EffectBaseP;

OSG_END_NAMESPACE

#endif /* _OSGEFFECTBASE_H_ */
