/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class EffectEventDetails!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>




#include "KEEffectEventDetailsBase.h"
#include "KEEffectEventDetails.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::EffectEventDetails
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<EffectEventDetails *>::_type("EffectEventDetailsPtr", "EventDetailsPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(EffectEventDetails *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           EffectEventDetails *,
                           0);


/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void EffectEventDetailsBase::classDescInserter(TypeObject &oType)
{
}


EffectEventDetailsBase::TypeObject EffectEventDetailsBase::_type(
    EffectEventDetailsBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&EffectEventDetailsBase::createEmptyLocal),
    EffectEventDetails::initMethod,
    EffectEventDetails::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&EffectEventDetails::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"EffectEventDetails\"\n"
    "\tparent=\"EventDetails\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"single\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"true\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "\tsupportUnregisteredCreate=\"true\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &EffectEventDetailsBase::getType(void)
{
    return _type;
}

const FieldContainerType &EffectEventDetailsBase::getType(void) const
{
    return _type;
}

UInt32 EffectEventDetailsBase::getContainerSize(void) const
{
    return sizeof(EffectEventDetails);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 EffectEventDetailsBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void EffectEventDetailsBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void EffectEventDetailsBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
EffectEventDetailsTransitPtr EffectEventDetailsBase::createLocal(BitVector bFlags)
{
    EffectEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<EffectEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
EffectEventDetailsTransitPtr EffectEventDetailsBase::createDependent(BitVector bFlags)
{
    EffectEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<EffectEventDetails>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
EffectEventDetailsTransitPtr EffectEventDetailsBase::create(void)
{
    EffectEventDetailsTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<EffectEventDetails>(tmpPtr);
    }

    return fc;
}

EffectEventDetails *EffectEventDetailsBase::createEmptyLocal(BitVector bFlags)
{
    EffectEventDetails *returnValue;

    newPtr<EffectEventDetails>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
EffectEventDetails *EffectEventDetailsBase::createEmpty(void)
{
    EffectEventDetails *returnValue;

    newPtr<EffectEventDetails>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}

EffectEventDetails *EffectEventDetailsBase::createUnregistered(void)
{
    EffectEventDetails *returnValue = new EffectEventDetails;

#ifdef OSG_MT_CPTR_ASPECT
    returnValue->setupAspectStore();
#endif
    //Do not register with the FieldContainer Factory

    returnValue->onCreate      (      );
    returnValue->onCreateAspect(returnValue);
    
    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();
    
    return returnValue;
}


FieldContainerTransitPtr EffectEventDetailsBase::shallowCopyLocal(
    BitVector bFlags) const
{
    EffectEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const EffectEventDetails *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr EffectEventDetailsBase::shallowCopyDependent(
    BitVector bFlags) const
{
    EffectEventDetails *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const EffectEventDetails *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr EffectEventDetailsBase::shallowCopy(void) const
{
    EffectEventDetails *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const EffectEventDetails *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

EffectEventDetailsBase::EffectEventDetailsBase(void) :
    Inherited()
{
}

EffectEventDetailsBase::EffectEventDetailsBase(const EffectEventDetailsBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

EffectEventDetailsBase::~EffectEventDetailsBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void EffectEventDetailsBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    EffectEventDetails *pThis = static_cast<EffectEventDetails *>(this);

    pThis->execSync(static_cast<EffectEventDetails *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *EffectEventDetailsBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    EffectEventDetails *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const EffectEventDetails *>(pRefAspect),
                  dynamic_cast<const EffectEventDetails *>(this));

    return returnValue;
}
#endif

void EffectEventDetailsBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
