/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEEFFECTEVENTDETAILSFIELDS_H_
#define _KEEFFECTEVENTDETAILSFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class EffectEventDetails;

OSG_GEN_CONTAINERPTR(EffectEventDetails);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<EffectEventDetails *> :
    public FieldTraitsFCPtrBase<EffectEventDetails *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<EffectEventDetails *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFEffectEventDetailsPtr"; }
};

template<> inline
const Char8 *FieldTraits<EffectEventDetails *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecEffectEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectEventDetails *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecEffectEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectEventDetails *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakEffectEventDetailsPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectEventDetails *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdEffectEventDetailsPtr"; 
}



#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EffectEventDetails *,
                      RecordedRefCountPolicy  > SFRecEffectEventDetailsPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EffectEventDetails *,
                      UnrecordedRefCountPolicy> SFUnrecEffectEventDetailsPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EffectEventDetails *,
                      WeakRefCountPolicy      > SFWeakEffectEventDetailsPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EffectEventDetails *,
                      NoRefCountPolicy        > SFUncountedEffectEventDetailsPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecEffectEventDetailsPtr : 
    public PointerSField<EffectEventDetails *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecEffectEventDetailsPtr : 
    public PointerSField<EffectEventDetails *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakEffectEventDetailsPtr :
    public PointerSField<EffectEventDetails *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedEffectEventDetailsPtr :
    public PointerSField<EffectEventDetails *,
                         NoRefCountPolicy> {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEEFFECTEVENTDETAILSFIELDS_H_ */
