/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  Robert Goetz (rdgoetz@iastate.edu)                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEEFFECTGROUPFIELDS_H_
#define _KEEFFECTGROUPFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class EffectGroup;

OSG_GEN_CONTAINERPTR(EffectGroup);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<EffectGroup *> :
    public FieldTraitsFCPtrBase<EffectGroup *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<EffectGroup *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFEffectGroupPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFEffectGroupPtr"; }
};

template<> inline
const Char8 *FieldTraits<EffectGroup *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectGroup *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectGroup *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectGroup *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectGroup *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectGroup *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectGroup *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakEffectGroupPtr"; 
}

template<> inline
const Char8 *FieldTraits<EffectGroup *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdEffectGroupPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EffectGroup *,
                      RecordedRefCountPolicy  > SFRecEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EffectGroup *,
                      UnrecordedRefCountPolicy> SFUnrecEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EffectGroup *,
                      WeakRefCountPolicy      > SFWeakEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EffectGroup *,
                      NoRefCountPolicy        > SFUncountedEffectGroupPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<EffectGroup *,
                      RecordedRefCountPolicy  > MFRecEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<EffectGroup *,
                      UnrecordedRefCountPolicy> MFUnrecEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<EffectGroup *,
                      WeakRefCountPolicy      > MFWeakEffectGroupPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<EffectGroup *,
                      NoRefCountPolicy        > MFUncountedEffectGroupPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecEffectGroupPtr : 
    public PointerSField<EffectGroup *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecEffectGroupPtr : 
    public PointerSField<EffectGroup *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakEffectGroupPtr :
    public PointerSField<EffectGroup *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedEffectGroupPtr :
    public PointerSField<EffectGroup *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecEffectGroupPtr :
    public PointerMField<EffectGroup *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecEffectGroupPtr :
    public PointerMField<EffectGroup *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakEffectGroupPtr :
    public PointerMField<EffectGroup *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedEffectGroupPtr :
    public PointerMField<EffectGroup *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEEFFECTGROUPFIELDS_H_ */
