/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  Robert Goetz (rdgoetz@iastate.edu)                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ParticleSystemEffect!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>



#include "OSGParticleSystem.h"          // TheSystem Class

#include "KEParticleSystemEffectBase.h"
#include "KEParticleSystemEffect.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::ParticleSystemEffect
    The SceneObject.
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/

/*! \var ParticleSystem * ParticleSystemEffectBase::_sfTheSystem
    
*/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<ParticleSystemEffect *>::_type("ParticleSystemEffectPtr", "EffectPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(ParticleSystemEffect *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           ParticleSystemEffect *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           ParticleSystemEffect *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void ParticleSystemEffectBase::classDescInserter(TypeObject &oType)
{
    FieldDescriptionBase *pDesc = NULL;


    pDesc = new SFUnrecParticleSystemPtr::Description(
        SFUnrecParticleSystemPtr::getClassType(),
        "TheSystem",
        "",
        TheSystemFieldId, TheSystemFieldMask,
        false,
        (Field::SFDefaultFlags | Field::FStdAccess),
        static_cast<FieldEditMethodSig>(&ParticleSystemEffect::editHandleTheSystem),
        static_cast<FieldGetMethodSig >(&ParticleSystemEffect::getHandleTheSystem));

    oType.addInitialDesc(pDesc);
}


ParticleSystemEffectBase::TypeObject ParticleSystemEffectBase::_type(
    ParticleSystemEffectBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&ParticleSystemEffectBase::createEmptyLocal),
    ParticleSystemEffect::initMethod,
    ParticleSystemEffect::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&ParticleSystemEffect::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"ParticleSystemEffect\"\n"
    "\tparent=\"Effect\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "    isNodeCore=\"false\"\n"
    "    authors=\"Robert Goetz (rdgoetz@iastate.edu)                            \"\n"
    ">\n"
    "The SceneObject.\n"
    "\t<Field\n"
    "\t\tname=\"TheSystem\"\n"
    "\t\ttype=\"ParticleSystem\"\n"
    "\t\tcategory=\"pointer\"\n"
    "\t\tcardinality=\"single\"\n"
    "\t\tvisibility=\"external\"\n"
    "\t\taccess=\"protected\"\n"
    "        fieldHeader=\"OSGParticleSystemFields.h\"\n"
    "\t\ttypeHeader=\"OSGParticleSystem.h\"\n"
    "\t>\n"
    "\t</Field>\n"
    "</FieldContainer>\n",
    "The SceneObject.\n"
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &ParticleSystemEffectBase::getType(void)
{
    return _type;
}

const FieldContainerType &ParticleSystemEffectBase::getType(void) const
{
    return _type;
}

UInt32 ParticleSystemEffectBase::getContainerSize(void) const
{
    return sizeof(ParticleSystemEffect);
}

/*------------------------- decorator get ------------------------------*/


//! Get the ParticleSystemEffect::_sfTheSystem field.
const SFUnrecParticleSystemPtr *ParticleSystemEffectBase::getSFTheSystem(void) const
{
    return &_sfTheSystem;
}

SFUnrecParticleSystemPtr *ParticleSystemEffectBase::editSFTheSystem      (void)
{
    editSField(TheSystemFieldMask);

    return &_sfTheSystem;
}





/*------------------------------ access -----------------------------------*/

UInt32 ParticleSystemEffectBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (TheSystemFieldMask & whichField))
    {
        returnValue += _sfTheSystem.getBinSize();
    }

    return returnValue;
}

void ParticleSystemEffectBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (TheSystemFieldMask & whichField))
    {
        _sfTheSystem.copyToBin(pMem);
    }
}

void ParticleSystemEffectBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (TheSystemFieldMask & whichField))
    {
        _sfTheSystem.copyFromBin(pMem);
    }
}

//! create a new instance of the class
ParticleSystemEffectTransitPtr ParticleSystemEffectBase::createLocal(BitVector bFlags)
{
    ParticleSystemEffectTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<ParticleSystemEffect>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
ParticleSystemEffectTransitPtr ParticleSystemEffectBase::createDependent(BitVector bFlags)
{
    ParticleSystemEffectTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<ParticleSystemEffect>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
ParticleSystemEffectTransitPtr ParticleSystemEffectBase::create(void)
{
    ParticleSystemEffectTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<ParticleSystemEffect>(tmpPtr);
    }

    return fc;
}

ParticleSystemEffect *ParticleSystemEffectBase::createEmptyLocal(BitVector bFlags)
{
    ParticleSystemEffect *returnValue;

    newPtr<ParticleSystemEffect>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
ParticleSystemEffect *ParticleSystemEffectBase::createEmpty(void)
{
    ParticleSystemEffect *returnValue;

    newPtr<ParticleSystemEffect>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr ParticleSystemEffectBase::shallowCopyLocal(
    BitVector bFlags) const
{
    ParticleSystemEffect *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ParticleSystemEffect *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr ParticleSystemEffectBase::shallowCopyDependent(
    BitVector bFlags) const
{
    ParticleSystemEffect *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const ParticleSystemEffect *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr ParticleSystemEffectBase::shallowCopy(void) const
{
    ParticleSystemEffect *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const ParticleSystemEffect *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

ParticleSystemEffectBase::ParticleSystemEffectBase(void) :
    Inherited(),
    _sfTheSystem              (NULL)
{
}

ParticleSystemEffectBase::ParticleSystemEffectBase(const ParticleSystemEffectBase &source) :
    Inherited(source),
    _sfTheSystem              (NULL)
{
}


/*-------------------------- destructors ----------------------------------*/

ParticleSystemEffectBase::~ParticleSystemEffectBase(void)
{
}

void ParticleSystemEffectBase::onCreate(const ParticleSystemEffect *source)
{
    Inherited::onCreate(source);

    if(source != NULL)
    {
        ParticleSystemEffect *pThis = static_cast<ParticleSystemEffect *>(this);

        pThis->setTheSystem(source->getTheSystem());
    }
}

GetFieldHandlePtr ParticleSystemEffectBase::getHandleTheSystem       (void) const
{
    SFUnrecParticleSystemPtr::GetHandlePtr returnValue(
        new  SFUnrecParticleSystemPtr::GetHandle(
             &_sfTheSystem,
             this->getType().getFieldDesc(TheSystemFieldId),
             const_cast<ParticleSystemEffectBase *>(this)));

    return returnValue;
}

EditFieldHandlePtr ParticleSystemEffectBase::editHandleTheSystem      (void)
{
    SFUnrecParticleSystemPtr::EditHandlePtr returnValue(
        new  SFUnrecParticleSystemPtr::EditHandle(
             &_sfTheSystem,
             this->getType().getFieldDesc(TheSystemFieldId),
             this));

    returnValue->setSetMethod(
        boost::bind(&ParticleSystemEffect::setTheSystem,
                    static_cast<ParticleSystemEffect *>(this), _1));

    editSField(TheSystemFieldMask);

    return returnValue;
}


#ifdef OSG_MT_CPTR_ASPECT
void ParticleSystemEffectBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    ParticleSystemEffect *pThis = static_cast<ParticleSystemEffect *>(this);

    pThis->execSync(static_cast<ParticleSystemEffect *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *ParticleSystemEffectBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    ParticleSystemEffect *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const ParticleSystemEffect *>(pRefAspect),
                  dynamic_cast<const ParticleSystemEffect *>(this));

    return returnValue;
}
#endif

void ParticleSystemEffectBase::resolveLinks(void)
{
    Inherited::resolveLinks();

    static_cast<ParticleSystemEffect *>(this)->setTheSystem(NULL);


}


OSG_END_NAMESPACE
