/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  Robert Goetz (rdgoetz@iastate.edu)                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEPHYSICSIMPULSEEFFECTFIELDS_H_
#define _KEPHYSICSIMPULSEEFFECTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class PhysicsImpulseEffect;

OSG_GEN_CONTAINERPTR(PhysicsImpulseEffect);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<PhysicsImpulseEffect *> :
    public FieldTraitsFCPtrBase<PhysicsImpulseEffect *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<PhysicsImpulseEffect *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFPhysicsImpulseEffectPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFPhysicsImpulseEffectPtr"; }
};

template<> inline
const Char8 *FieldTraits<PhysicsImpulseEffect *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecPhysicsImpulseEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsImpulseEffect *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecPhysicsImpulseEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsImpulseEffect *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakPhysicsImpulseEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsImpulseEffect *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdPhysicsImpulseEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsImpulseEffect *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecPhysicsImpulseEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsImpulseEffect *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecPhysicsImpulseEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsImpulseEffect *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakPhysicsImpulseEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<PhysicsImpulseEffect *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdPhysicsImpulseEffectPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<PhysicsImpulseEffect *,
                      RecordedRefCountPolicy  > SFRecPhysicsImpulseEffectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<PhysicsImpulseEffect *,
                      UnrecordedRefCountPolicy> SFUnrecPhysicsImpulseEffectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<PhysicsImpulseEffect *,
                      WeakRefCountPolicy      > SFWeakPhysicsImpulseEffectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<PhysicsImpulseEffect *,
                      NoRefCountPolicy        > SFUncountedPhysicsImpulseEffectPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<PhysicsImpulseEffect *,
                      RecordedRefCountPolicy  > MFRecPhysicsImpulseEffectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<PhysicsImpulseEffect *,
                      UnrecordedRefCountPolicy> MFUnrecPhysicsImpulseEffectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<PhysicsImpulseEffect *,
                      WeakRefCountPolicy      > MFWeakPhysicsImpulseEffectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<PhysicsImpulseEffect *,
                      NoRefCountPolicy        > MFUncountedPhysicsImpulseEffectPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecPhysicsImpulseEffectPtr : 
    public PointerSField<PhysicsImpulseEffect *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecPhysicsImpulseEffectPtr : 
    public PointerSField<PhysicsImpulseEffect *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakPhysicsImpulseEffectPtr :
    public PointerSField<PhysicsImpulseEffect *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedPhysicsImpulseEffectPtr :
    public PointerSField<PhysicsImpulseEffect *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecPhysicsImpulseEffectPtr :
    public PointerMField<PhysicsImpulseEffect *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecPhysicsImpulseEffectPtr :
    public PointerMField<PhysicsImpulseEffect *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakPhysicsImpulseEffectPtr :
    public PointerMField<PhysicsImpulseEffect *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedPhysicsImpulseEffectPtr :
    public PointerMField<PhysicsImpulseEffect *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEPHYSICSIMPULSEEFFECTFIELDS_H_ */
