/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  Robert Goetz (rdgoetz@iastate.edu)                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class PhysicsImpulseEffect
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEPHYSICSIMPULSEEFFECTBASE_H_
#define _KEPHYSICSIMPULSEEFFECTBASE_H_
#ifdef __sgi
#pragma once
#endif



#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"
#include "KEConfig.h"

//#include "OpenSG/OSGBaseTypes.h"


#include "KEEffect.h" // Parent

#include <OpenSG/OSGPhysicsBodyFields.h> // PhysicsBodies type
#include <OpenSG/OSGPhysicsWorldFields.h> // PhysicsWorld type
#include <OpenSG/OSGPhysicsSpaceFields.h> // PhysicsSpace type

#include "KEPhysicsImpulseEffectFields.h"

OSG_BEGIN_NAMESPACE

class PhysicsImpulseEffect;

//! \brief PhysicsImpulseEffect Base Class.

class KE_KABALAENGINE_DLLMAPPING PhysicsImpulseEffectBase : public Effect
{
  public:

    typedef Effect Inherited;
    typedef Effect ParentContainer;

    typedef Inherited::TypeObject TypeObject;
    typedef TypeObject::InitPhase InitPhase;

    OSG_GEN_INTERNALPTR(PhysicsImpulseEffect);

    /*==========================  PUBLIC  =================================*/

  public:

    enum
    {
        PhysicsBodiesFieldId = Inherited::NextFieldId,
        PhysicsWorldFieldId = PhysicsBodiesFieldId + 1,
        PhysicsSpaceFieldId = PhysicsWorldFieldId + 1,
        PhysicsWorldFieldId = PhysicsSpaceFieldId + 1,
        NextFieldId = PhysicsWorldFieldId + 1
    };

    static const OSG::BitVector PhysicsBodiesFieldMask =
        (TypeTraits<BitVector>::One << PhysicsBodiesFieldId);
    static const OSG::BitVector PhysicsWorldFieldMask =
        (TypeTraits<BitVector>::One << PhysicsWorldFieldId);
    static const OSG::BitVector PhysicsSpaceFieldMask =
        (TypeTraits<BitVector>::One << PhysicsSpaceFieldId);
    static const OSG::BitVector PhysicsWorldFieldMask =
        (TypeTraits<BitVector>::One << PhysicsWorldFieldId);
    static const OSG::BitVector NextFieldMask =
        (TypeTraits<BitVector>::One << NextFieldId);
        
    typedef MFUnrecPhysicsBodyPtr MFPhysicsBodiesType;
    typedef SFUnrecPhysicsWorldPtr SFPhysicsWorldType;
    typedef SFUnrecPhysicsSpacePtr SFPhysicsSpaceType;
    typedef SFUnrecPhysicsWorldPtr SFPhysicsWorldType;

    /*---------------------------------------------------------------------*/
    /*! \name                    Class Get                                 */
    /*! \{                                                                 */

    static FieldContainerType &getClassType   (void);
    static UInt32              getClassTypeId (void);
    static UInt16              getClassGroupId(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                FieldContainer Get                            */
    /*! \{                                                                 */

    virtual       FieldContainerType &getType         (void);
    virtual const FieldContainerType &getType         (void) const;

    virtual       UInt32              getContainerSize(void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Get                                 */
    /*! \{                                                                 */

            const MFUnrecPhysicsBodyPtr *getMFPhysicsBodies  (void) const;
                  MFUnrecPhysicsBodyPtr *editMFPhysicsBodies  (void);
            const SFUnrecPhysicsWorldPtr *getSFPhysicsWorld   (void) const;
                  SFUnrecPhysicsWorldPtr *editSFPhysicsWorld   (void);
            const SFUnrecPhysicsSpacePtr *getSFPhysicsSpace   (void) const;
                  SFUnrecPhysicsSpacePtr *editSFPhysicsSpace   (void);
            const SFUnrecPhysicsWorldPtr *getSFPhysicsWorld   (void) const;
                  SFUnrecPhysicsWorldPtr *editSFPhysicsWorld   (void);


                  PhysicsBody * getPhysicsBodies  (const UInt32 index) const;

                  PhysicsWorld * getPhysicsWorld   (void) const;

                  PhysicsSpace * getPhysicsSpace   (void) const;

                  PhysicsWorld * getPhysicsWorld   (void) const;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Field Set                                 */
    /*! \{                                                                 */

            void setPhysicsWorld   (PhysicsWorld * const value);
            void setPhysicsSpace   (PhysicsSpace * const value);
            void setPhysicsWorld   (PhysicsWorld * const value);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr Field Set                                 */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                Ptr MField Set                                */
    /*! \{                                                                 */

    void pushToPhysicsBodies           (PhysicsBody * const value   );
    void assignPhysicsBodies          (const MFUnrecPhysicsBodyPtr &value);
    void removeFromPhysicsBodies (UInt32               uiIndex );
    void removeObjFromPhysicsBodies(PhysicsBody * const value   );
    void clearPhysicsBodies            (void                         );

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Binary Access                              */
    /*! \{                                                                 */

    virtual UInt32 getBinSize (ConstFieldMaskArg  whichField);
    virtual void   copyToBin  (BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);
    virtual void   copyFromBin(BinaryDataHandler &pMem,
                               ConstFieldMaskArg  whichField);


    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Construction                               */
    /*! \{                                                                 */

    static  PhysicsImpulseEffectTransitPtr  create          (void);
    static  PhysicsImpulseEffect           *createEmpty     (void);

    static  PhysicsImpulseEffectTransitPtr  createLocal     (
                                               BitVector bFlags = FCLocal::All);

    static  PhysicsImpulseEffect            *createEmptyLocal(
                                              BitVector bFlags = FCLocal::All);

    static  PhysicsImpulseEffectTransitPtr  createDependent  (BitVector bFlags);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Copy                                   */
    /*! \{                                                                 */

    virtual FieldContainerTransitPtr shallowCopy     (void) const;
    virtual FieldContainerTransitPtr shallowCopyLocal(
                                       BitVector bFlags = FCLocal::All) const;
    virtual FieldContainerTransitPtr shallowCopyDependent(
                                                      BitVector bFlags) const;

    /*! \}                                                                 */
    /*=========================  PROTECTED  ===============================*/

  protected:

    static TypeObject _type;

    static       void   classDescInserter(TypeObject &oType);
    static const Char8 *getClassname     (void             );

    /*---------------------------------------------------------------------*/
    /*! \name                      Fields                                  */
    /*! \{                                                                 */

    MFUnrecPhysicsBodyPtr _mfPhysicsBodies;
    SFUnrecPhysicsWorldPtr _sfPhysicsWorld;
    SFUnrecPhysicsSpacePtr _sfPhysicsSpace;
    SFUnrecPhysicsWorldPtr _sfPhysicsWorld;

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Constructors                               */
    /*! \{                                                                 */

    PhysicsImpulseEffectBase(void);
    PhysicsImpulseEffectBase(const PhysicsImpulseEffectBase &source);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                   Destructors                                */
    /*! \{                                                                 */

    virtual ~PhysicsImpulseEffectBase(void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     onCreate                                */
    /*! \{                                                                 */

    void onCreate(const PhysicsImpulseEffect *source = NULL);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                    Generic Field Access                      */
    /*! \{                                                                 */

    GetFieldHandlePtr  getHandlePhysicsBodies   (void) const;
    EditFieldHandlePtr editHandlePhysicsBodies  (void);
    GetFieldHandlePtr  getHandlePhysicsWorld    (void) const;
    EditFieldHandlePtr editHandlePhysicsWorld   (void);
    GetFieldHandlePtr  getHandlePhysicsSpace    (void) const;
    EditFieldHandlePtr editHandlePhysicsSpace   (void);
    GetFieldHandlePtr  getHandlePhysicsWorld    (void) const;
    EditFieldHandlePtr editHandlePhysicsWorld   (void);

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual void execSyncV(      FieldContainer    &oFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);

            void execSync (      PhysicsImpulseEffectBase *pFrom,
                                 ConstFieldMaskArg  whichField,
                                 AspectOffsetStore &oOffsets,
                                 ConstFieldMaskArg  syncMode  ,
                           const UInt32             uiSyncInfo);
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                     Aspect Create                            */
    /*! \{                                                                 */

#ifdef OSG_MT_CPTR_ASPECT
    virtual FieldContainer *createAspectCopy(
                                    const FieldContainer *pRefAspect) const;
#endif

    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Edit                                   */
    /*! \{                                                                 */
    /*! \}                                                                 */
    /*---------------------------------------------------------------------*/
    /*! \name                       Sync                                   */
    /*! \{                                                                 */

    virtual void resolveLinks(void);

    /*! \}                                                                 */
    /*==========================  PRIVATE  ================================*/

  private:
    /*---------------------------------------------------------------------*/

    // prohibit default functions (move to 'public' if you need one)
    void operator =(const PhysicsImpulseEffectBase &source);
};

typedef PhysicsImpulseEffectBase *PhysicsImpulseEffectBaseP;

OSG_END_NAMESPACE

#endif /* _OSGPHYSICSIMPULSEEFFECTBASE_H_ */
