/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  Robert Goetz (rdgoetz@iastate.edu)                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class SequentialEffectGroup!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>




#include "KESequentialEffectGroupBase.h"
#include "KESequentialEffectGroup.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::SequentialEffectGroup
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<SequentialEffectGroup *>::_type("SequentialEffectGroupPtr", "EffectGroupPtr");
#endif

OSG_FIELDTRAITS_GETTYPE(SequentialEffectGroup *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           SequentialEffectGroup *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           SequentialEffectGroup *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void SequentialEffectGroupBase::classDescInserter(TypeObject &oType)
{
}


SequentialEffectGroupBase::TypeObject SequentialEffectGroupBase::_type(
    SequentialEffectGroupBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&SequentialEffectGroupBase::createEmptyLocal),
    SequentialEffectGroup::initMethod,
    SequentialEffectGroup::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&SequentialEffectGroup::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"SequentialEffectGroup\"\n"
    "\tparent=\"EffectGroup\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "    authors=\"Robert Goetz (rdgoetz@iastate.edu)                            \"\n"
    ">\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &SequentialEffectGroupBase::getType(void)
{
    return _type;
}

const FieldContainerType &SequentialEffectGroupBase::getType(void) const
{
    return _type;
}

UInt32 SequentialEffectGroupBase::getContainerSize(void) const
{
    return sizeof(SequentialEffectGroup);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 SequentialEffectGroupBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void SequentialEffectGroupBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void SequentialEffectGroupBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
SequentialEffectGroupTransitPtr SequentialEffectGroupBase::createLocal(BitVector bFlags)
{
    SequentialEffectGroupTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<SequentialEffectGroup>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
SequentialEffectGroupTransitPtr SequentialEffectGroupBase::createDependent(BitVector bFlags)
{
    SequentialEffectGroupTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<SequentialEffectGroup>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
SequentialEffectGroupTransitPtr SequentialEffectGroupBase::create(void)
{
    SequentialEffectGroupTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<SequentialEffectGroup>(tmpPtr);
    }

    return fc;
}

SequentialEffectGroup *SequentialEffectGroupBase::createEmptyLocal(BitVector bFlags)
{
    SequentialEffectGroup *returnValue;

    newPtr<SequentialEffectGroup>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
SequentialEffectGroup *SequentialEffectGroupBase::createEmpty(void)
{
    SequentialEffectGroup *returnValue;

    newPtr<SequentialEffectGroup>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr SequentialEffectGroupBase::shallowCopyLocal(
    BitVector bFlags) const
{
    SequentialEffectGroup *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const SequentialEffectGroup *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr SequentialEffectGroupBase::shallowCopyDependent(
    BitVector bFlags) const
{
    SequentialEffectGroup *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const SequentialEffectGroup *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr SequentialEffectGroupBase::shallowCopy(void) const
{
    SequentialEffectGroup *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const SequentialEffectGroup *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}




/*------------------------- constructors ----------------------------------*/

SequentialEffectGroupBase::SequentialEffectGroupBase(void) :
    Inherited()
{
}

SequentialEffectGroupBase::SequentialEffectGroupBase(const SequentialEffectGroupBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

SequentialEffectGroupBase::~SequentialEffectGroupBase(void)
{
}



#ifdef OSG_MT_CPTR_ASPECT
void SequentialEffectGroupBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    SequentialEffectGroup *pThis = static_cast<SequentialEffectGroup *>(this);

    pThis->execSync(static_cast<SequentialEffectGroup *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *SequentialEffectGroupBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    SequentialEffectGroup *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const SequentialEffectGroup *>(pRefAspect),
                  dynamic_cast<const SequentialEffectGroup *>(this));

    return returnValue;
}
#endif

void SequentialEffectGroupBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
