/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  Robert Goetz (rdgoetz@iastate.edu)                            *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESOUNDEFFECTFIELDS_H_
#define _KESOUNDEFFECTFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SoundEffect;

OSG_GEN_CONTAINERPTR(SoundEffect);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SoundEffect *> :
    public FieldTraitsFCPtrBase<SoundEffect *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SoundEffect *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSoundEffectPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSoundEffectPtr"; }
};

template<> inline
const Char8 *FieldTraits<SoundEffect *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSoundEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SoundEffect *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSoundEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SoundEffect *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSoundEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SoundEffect *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSoundEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SoundEffect *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSoundEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SoundEffect *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSoundEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SoundEffect *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSoundEffectPtr"; 
}

template<> inline
const Char8 *FieldTraits<SoundEffect *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSoundEffectPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SoundEffect *,
                      RecordedRefCountPolicy  > SFRecSoundEffectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SoundEffect *,
                      UnrecordedRefCountPolicy> SFUnrecSoundEffectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SoundEffect *,
                      WeakRefCountPolicy      > SFWeakSoundEffectPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SoundEffect *,
                      NoRefCountPolicy        > SFUncountedSoundEffectPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SoundEffect *,
                      RecordedRefCountPolicy  > MFRecSoundEffectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SoundEffect *,
                      UnrecordedRefCountPolicy> MFUnrecSoundEffectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SoundEffect *,
                      WeakRefCountPolicy      > MFWeakSoundEffectPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SoundEffect *,
                      NoRefCountPolicy        > MFUncountedSoundEffectPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSoundEffectPtr : 
    public PointerSField<SoundEffect *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSoundEffectPtr : 
    public PointerSField<SoundEffect *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSoundEffectPtr :
    public PointerSField<SoundEffect *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSoundEffectPtr :
    public PointerSField<SoundEffect *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecSoundEffectPtr :
    public PointerMField<SoundEffect *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecSoundEffectPtr :
    public PointerMField<SoundEffect *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakSoundEffectPtr :
    public PointerMField<SoundEffect *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedSoundEffectPtr :
    public PointerMField<SoundEffect *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESOUNDEFFECTFIELDS_H_ */
