/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KECAMERAEDITORFIELDS_H_
#define _KECAMERAEDITORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class CameraEditor;

OSG_GEN_CONTAINERPTR(CameraEditor);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<CameraEditor *> :
    public FieldTraitsFCPtrBase<CameraEditor *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<CameraEditor *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFCameraEditorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFCameraEditorPtr"; }
};

template<> inline
const Char8 *FieldTraits<CameraEditor *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecCameraEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<CameraEditor *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecCameraEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<CameraEditor *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakCameraEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<CameraEditor *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdCameraEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<CameraEditor *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecCameraEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<CameraEditor *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecCameraEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<CameraEditor *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakCameraEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<CameraEditor *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdCameraEditorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<CameraEditor *,
                      RecordedRefCountPolicy  > SFRecCameraEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<CameraEditor *,
                      UnrecordedRefCountPolicy> SFUnrecCameraEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<CameraEditor *,
                      WeakRefCountPolicy      > SFWeakCameraEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<CameraEditor *,
                      NoRefCountPolicy        > SFUncountedCameraEditorPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<CameraEditor *,
                      RecordedRefCountPolicy  > MFRecCameraEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<CameraEditor *,
                      UnrecordedRefCountPolicy> MFUnrecCameraEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<CameraEditor *,
                      WeakRefCountPolicy      > MFWeakCameraEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<CameraEditor *,
                      NoRefCountPolicy        > MFUncountedCameraEditorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecCameraEditorPtr : 
    public PointerSField<CameraEditor *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecCameraEditorPtr : 
    public PointerSField<CameraEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakCameraEditorPtr :
    public PointerSField<CameraEditor *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedCameraEditorPtr :
    public PointerSField<CameraEditor *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecCameraEditorPtr :
    public PointerMField<CameraEditor *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecCameraEditorPtr :
    public PointerMField<CameraEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakCameraEditorPtr :
    public PointerMField<CameraEditor *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedCameraEditorPtr :
    public PointerMField<CameraEditor *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KECAMERAEDITORFIELDS_H_ */
