/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEEDITORINTERFACEFIELDS_H_
#define _KEEDITORINTERFACEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class EditorInterface;

OSG_GEN_CONTAINERPTR(EditorInterface);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<EditorInterface *> :
    public FieldTraitsFCPtrBase<EditorInterface *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<EditorInterface *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFEditorInterfacePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFEditorInterfacePtr"; }
};

template<> inline
const Char8 *FieldTraits<EditorInterface *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecEditorInterfacePtr"; 
}

template<> inline
const Char8 *FieldTraits<EditorInterface *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecEditorInterfacePtr"; 
}

template<> inline
const Char8 *FieldTraits<EditorInterface *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakEditorInterfacePtr"; 
}

template<> inline
const Char8 *FieldTraits<EditorInterface *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdEditorInterfacePtr"; 
}

template<> inline
const Char8 *FieldTraits<EditorInterface *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecEditorInterfacePtr"; 
}

template<> inline
const Char8 *FieldTraits<EditorInterface *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecEditorInterfacePtr"; 
}

template<> inline
const Char8 *FieldTraits<EditorInterface *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakEditorInterfacePtr"; 
}

template<> inline
const Char8 *FieldTraits<EditorInterface *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdEditorInterfacePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EditorInterface *,
                      RecordedRefCountPolicy  > SFRecEditorInterfacePtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EditorInterface *,
                      UnrecordedRefCountPolicy> SFUnrecEditorInterfacePtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EditorInterface *,
                      WeakRefCountPolicy      > SFWeakEditorInterfacePtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<EditorInterface *,
                      NoRefCountPolicy        > SFUncountedEditorInterfacePtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<EditorInterface *,
                      RecordedRefCountPolicy  > MFRecEditorInterfacePtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<EditorInterface *,
                      UnrecordedRefCountPolicy> MFUnrecEditorInterfacePtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<EditorInterface *,
                      WeakRefCountPolicy      > MFWeakEditorInterfacePtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<EditorInterface *,
                      NoRefCountPolicy        > MFUncountedEditorInterfacePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecEditorInterfacePtr : 
    public PointerSField<EditorInterface *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecEditorInterfacePtr : 
    public PointerSField<EditorInterface *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakEditorInterfacePtr :
    public PointerSField<EditorInterface *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedEditorInterfacePtr :
    public PointerSField<EditorInterface *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecEditorInterfacePtr :
    public PointerMField<EditorInterface *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecEditorInterfacePtr :
    public PointerMField<EditorInterface *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakEditorInterfacePtr :
    public PointerMField<EditorInterface *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedEditorInterfacePtr :
    public PointerMField<EditorInterface *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEEDITORINTERFACEFIELDS_H_ */
