/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEAPPLICATIONMODEFIELDS_H_
#define _KEAPPLICATIONMODEFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class ApplicationMode;

OSG_GEN_CONTAINERPTR(ApplicationMode);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<ApplicationMode *> :
    public FieldTraitsFCPtrBase<ApplicationMode *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ApplicationMode *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFApplicationModePtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFApplicationModePtr"; }
};

template<> inline
const Char8 *FieldTraits<ApplicationMode *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecApplicationModePtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationMode *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecApplicationModePtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationMode *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakApplicationModePtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationMode *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdApplicationModePtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationMode *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecApplicationModePtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationMode *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecApplicationModePtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationMode *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakApplicationModePtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationMode *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdApplicationModePtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ApplicationMode *,
                      RecordedRefCountPolicy  > SFRecApplicationModePtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ApplicationMode *,
                      UnrecordedRefCountPolicy> SFUnrecApplicationModePtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ApplicationMode *,
                      WeakRefCountPolicy      > SFWeakApplicationModePtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ApplicationMode *,
                      NoRefCountPolicy        > SFUncountedApplicationModePtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ApplicationMode *,
                      RecordedRefCountPolicy  > MFRecApplicationModePtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ApplicationMode *,
                      UnrecordedRefCountPolicy> MFUnrecApplicationModePtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ApplicationMode *,
                      WeakRefCountPolicy      > MFWeakApplicationModePtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ApplicationMode *,
                      NoRefCountPolicy        > MFUncountedApplicationModePtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecApplicationModePtr : 
    public PointerSField<ApplicationMode *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecApplicationModePtr : 
    public PointerSField<ApplicationMode *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakApplicationModePtr :
    public PointerSField<ApplicationMode *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedApplicationModePtr :
    public PointerSField<ApplicationMode *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecApplicationModePtr :
    public PointerMField<ApplicationMode *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecApplicationModePtr :
    public PointerMField<ApplicationMode *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakApplicationModePtr :
    public PointerMField<ApplicationMode *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedApplicationModePtr :
    public PointerMField<ApplicationMode *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEAPPLICATIONMODEFIELDS_H_ */
