/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala (dkabala@vrac.iastate.edu)                        *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ApplicationSettings!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILEAPPLICATIONSETTINGSINST

#include <stdlib.h>
#include <stdio.h>

#include "KEConfig.h"

#include "KEApplicationSettingsBase.h"
#include "KEApplicationSettings.h"


KE_USING_NAMESPACE

const OSG::BitVector  ApplicationSettingsBase::DataDirectoryFieldMask = 
    (TypeTraits<BitVector>::One << ApplicationSettingsBase::DataDirectoryFieldId);

const OSG::BitVector  ApplicationSettingsBase::LastOpenedProjectFileFieldMask = 
    (TypeTraits<BitVector>::One << ApplicationSettingsBase::LastOpenedProjectFileFieldId);

const OSG::BitVector  ApplicationSettingsBase::DefaultWindowPositionFieldMask = 
    (TypeTraits<BitVector>::One << ApplicationSettingsBase::DefaultWindowPositionFieldId);

const OSG::BitVector  ApplicationSettingsBase::DefaultWindowSizeFieldMask = 
    (TypeTraits<BitVector>::One << ApplicationSettingsBase::DefaultWindowSizeFieldId);

const OSG::BitVector ApplicationSettingsBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var Path            ApplicationSettingsBase::_sfDataDirectory
    
*/
/*! \var Path            ApplicationSettingsBase::_sfLastOpenedProjectFile
    
*/
/*! \var Pnt2f           ApplicationSettingsBase::_sfDefaultWindowPosition
    
*/
/*! \var Vec2f           ApplicationSettingsBase::_sfDefaultWindowSize
    
*/

//! ApplicationSettings description

FieldDescription *ApplicationSettingsBase::_desc[] = 
{
    new FieldDescription(SFPath::getClassType(), 
                     "DataDirectory", 
                     DataDirectoryFieldId, DataDirectoryFieldMask,
                     false,
                     (FieldAccessMethod) &ApplicationSettingsBase::getSFDataDirectory),
    new FieldDescription(SFPath::getClassType(), 
                     "LastOpenedProjectFile", 
                     LastOpenedProjectFileFieldId, LastOpenedProjectFileFieldMask,
                     false,
                     (FieldAccessMethod) &ApplicationSettingsBase::getSFLastOpenedProjectFile),
    new FieldDescription(SFPnt2f::getClassType(), 
                     "DefaultWindowPosition", 
                     DefaultWindowPositionFieldId, DefaultWindowPositionFieldMask,
                     false,
                     (FieldAccessMethod) &ApplicationSettingsBase::getSFDefaultWindowPosition),
    new FieldDescription(SFVec2f::getClassType(), 
                     "DefaultWindowSize", 
                     DefaultWindowSizeFieldId, DefaultWindowSizeFieldMask,
                     false,
                     (FieldAccessMethod) &ApplicationSettingsBase::getSFDefaultWindowSize)
};


FieldContainerType ApplicationSettingsBase::_type(
    "ApplicationSettings",
    "FieldContainer",
    NULL,
    (PrototypeCreateF) &ApplicationSettingsBase::createEmpty,
    ApplicationSettings::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(ApplicationSettingsBase, ApplicationSettingsPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &ApplicationSettingsBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &ApplicationSettingsBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr ApplicationSettingsBase::shallowCopy(void) const 
{ 
    ApplicationSettingsPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const ApplicationSettings *>(this)); 

    return returnValue; 
}

::osg::UInt32 ApplicationSettingsBase::getContainerSize(void) const 
{ 
    return sizeof(ApplicationSettings); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void ApplicationSettingsBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((ApplicationSettingsBase *) &other, whichField);
}
#else
void ApplicationSettingsBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((ApplicationSettingsBase *) &other, whichField, sInfo);
}
void ApplicationSettingsBase::execBeginEdit(const BitVector &whichField, 
                                            ::osg::UInt32     uiAspect,
                                            ::osg::UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void ApplicationSettingsBase::onDestroyAspect(::osg::UInt32 uiId, ::osg::UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

ApplicationSettingsBase::ApplicationSettingsBase(void) :
    _sfDataDirectory          (), 
    _sfLastOpenedProjectFile  (), 
    _sfDefaultWindowPosition  (Pnt2f(0.0f,0.0f)), 
    _sfDefaultWindowSize      (Vec2f(900.0f,800.0f)), 
    Inherited() 
{
}

ApplicationSettingsBase::ApplicationSettingsBase(const ApplicationSettingsBase &source) :
    _sfDataDirectory          (source._sfDataDirectory          ), 
    _sfLastOpenedProjectFile  (source._sfLastOpenedProjectFile  ), 
    _sfDefaultWindowPosition  (source._sfDefaultWindowPosition  ), 
    _sfDefaultWindowSize      (source._sfDefaultWindowSize      ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

ApplicationSettingsBase::~ApplicationSettingsBase(void)
{
}

/*------------------------------ access -----------------------------------*/

::osg::UInt32 ApplicationSettingsBase::getBinSize(const BitVector &whichField)
{
    ::osg::UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (DataDirectoryFieldMask & whichField))
    {
        returnValue += _sfDataDirectory.getBinSize();
    }

    if(FieldBits::NoField != (LastOpenedProjectFileFieldMask & whichField))
    {
        returnValue += _sfLastOpenedProjectFile.getBinSize();
    }

    if(FieldBits::NoField != (DefaultWindowPositionFieldMask & whichField))
    {
        returnValue += _sfDefaultWindowPosition.getBinSize();
    }

    if(FieldBits::NoField != (DefaultWindowSizeFieldMask & whichField))
    {
        returnValue += _sfDefaultWindowSize.getBinSize();
    }


    return returnValue;
}

void ApplicationSettingsBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (DataDirectoryFieldMask & whichField))
    {
        _sfDataDirectory.copyToBin(pMem);
    }

    if(FieldBits::NoField != (LastOpenedProjectFileFieldMask & whichField))
    {
        _sfLastOpenedProjectFile.copyToBin(pMem);
    }

    if(FieldBits::NoField != (DefaultWindowPositionFieldMask & whichField))
    {
        _sfDefaultWindowPosition.copyToBin(pMem);
    }

    if(FieldBits::NoField != (DefaultWindowSizeFieldMask & whichField))
    {
        _sfDefaultWindowSize.copyToBin(pMem);
    }


}

void ApplicationSettingsBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (DataDirectoryFieldMask & whichField))
    {
        _sfDataDirectory.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (LastOpenedProjectFileFieldMask & whichField))
    {
        _sfLastOpenedProjectFile.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (DefaultWindowPositionFieldMask & whichField))
    {
        _sfDefaultWindowPosition.copyFromBin(pMem);
    }

    if(FieldBits::NoField != (DefaultWindowSizeFieldMask & whichField))
    {
        _sfDefaultWindowSize.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void ApplicationSettingsBase::executeSyncImpl(      ApplicationSettingsBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (DataDirectoryFieldMask & whichField))
        _sfDataDirectory.syncWith(pOther->_sfDataDirectory);

    if(FieldBits::NoField != (LastOpenedProjectFileFieldMask & whichField))
        _sfLastOpenedProjectFile.syncWith(pOther->_sfLastOpenedProjectFile);

    if(FieldBits::NoField != (DefaultWindowPositionFieldMask & whichField))
        _sfDefaultWindowPosition.syncWith(pOther->_sfDefaultWindowPosition);

    if(FieldBits::NoField != (DefaultWindowSizeFieldMask & whichField))
        _sfDefaultWindowSize.syncWith(pOther->_sfDefaultWindowSize);


}
#else
void ApplicationSettingsBase::executeSyncImpl(      ApplicationSettingsBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (DataDirectoryFieldMask & whichField))
        _sfDataDirectory.syncWith(pOther->_sfDataDirectory);

    if(FieldBits::NoField != (LastOpenedProjectFileFieldMask & whichField))
        _sfLastOpenedProjectFile.syncWith(pOther->_sfLastOpenedProjectFile);

    if(FieldBits::NoField != (DefaultWindowPositionFieldMask & whichField))
        _sfDefaultWindowPosition.syncWith(pOther->_sfDefaultWindowPosition);

    if(FieldBits::NoField != (DefaultWindowSizeFieldMask & whichField))
        _sfDefaultWindowSize.syncWith(pOther->_sfDefaultWindowSize);



}

void ApplicationSettingsBase::execBeginEditImpl (const BitVector &whichField, 
                                                 ::osg::UInt32     uiAspect,
                                                 ::osg::UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<ApplicationSettingsPtr>::_type("ApplicationSettingsPtr", "FieldContainerPtr");
#endif

KE_BEGIN_NAMESPACE

OSG_DLLEXPORT_SFIELD_DEF1(ApplicationSettingsPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(ApplicationSettingsPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);

KE_END_NAMESPACE


