/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                         www.vrac.iastate.edu                              *
 *                                                                           *
 *   Authors: David Kabala (dkabala@vrac.iastate.edu)                        *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU Library General Public License as published    *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU Library General Public         *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ApplicationMode!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILEAPPLICATIONMODEINST

#include <stdlib.h>
#include <stdio.h>

#include "KEConfig.h"

#include "KEApplicationModeBase.h"
#include "KEApplicationMode.h"


KE_USING_NAMESPACE

const OSG::BitVector ApplicationModeBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 



FieldContainerType ApplicationModeBase::_type(
    "ApplicationMode",
    "FieldContainer",
    NULL,
    NULL, 
    ApplicationMode::initMethod,
    NULL,
    0);

//OSG_FIELD_CONTAINER_DEF(ApplicationModeBase, ApplicationModePtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &ApplicationModeBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &ApplicationModeBase::getType(void) const 
{
    return _type;
} 


UInt32 ApplicationModeBase::getContainerSize(void) const 
{ 
    return sizeof(ApplicationMode); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void ApplicationModeBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl((ApplicationModeBase *) &other, whichField);
}
#else
void ApplicationModeBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((ApplicationModeBase *) &other, whichField, sInfo);
}
void ApplicationModeBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void ApplicationModeBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

ApplicationModeBase::ApplicationModeBase(void) :
    Inherited() 
{
}

ApplicationModeBase::ApplicationModeBase(const ApplicationModeBase &source) :
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

ApplicationModeBase::~ApplicationModeBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 ApplicationModeBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void ApplicationModeBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);


}

void ApplicationModeBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void ApplicationModeBase::executeSyncImpl(      ApplicationModeBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);


}
#else
void ApplicationModeBase::executeSyncImpl(      ApplicationModeBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);



}

void ApplicationModeBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<ApplicationModePtr>::_type("ApplicationModePtr", "FieldContainerPtr");
#endif

KE_BEGIN_NAMESPACE

OSG_DLLEXPORT_SFIELD_DEF1(ApplicationModePtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(ApplicationModePtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);

KE_END_NAMESPACE


