/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEAPPLICATIONSTARTSCREENFIELDS_H_
#define _KEAPPLICATIONSTARTSCREENFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class ApplicationStartScreen;

OSG_GEN_CONTAINERPTR(ApplicationStartScreen);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<ApplicationStartScreen *> :
    public FieldTraitsFCPtrBase<ApplicationStartScreen *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<ApplicationStartScreen *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFApplicationStartScreenPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFApplicationStartScreenPtr"; }
};

template<> inline
const Char8 *FieldTraits<ApplicationStartScreen *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecApplicationStartScreenPtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationStartScreen *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecApplicationStartScreenPtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationStartScreen *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakApplicationStartScreenPtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationStartScreen *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdApplicationStartScreenPtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationStartScreen *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecApplicationStartScreenPtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationStartScreen *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecApplicationStartScreenPtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationStartScreen *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakApplicationStartScreenPtr"; 
}

template<> inline
const Char8 *FieldTraits<ApplicationStartScreen *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdApplicationStartScreenPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ApplicationStartScreen *,
                      RecordedRefCountPolicy  > SFRecApplicationStartScreenPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ApplicationStartScreen *,
                      UnrecordedRefCountPolicy> SFUnrecApplicationStartScreenPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ApplicationStartScreen *,
                      WeakRefCountPolicy      > SFWeakApplicationStartScreenPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<ApplicationStartScreen *,
                      NoRefCountPolicy        > SFUncountedApplicationStartScreenPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ApplicationStartScreen *,
                      RecordedRefCountPolicy  > MFRecApplicationStartScreenPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ApplicationStartScreen *,
                      UnrecordedRefCountPolicy> MFUnrecApplicationStartScreenPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ApplicationStartScreen *,
                      WeakRefCountPolicy      > MFWeakApplicationStartScreenPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<ApplicationStartScreen *,
                      NoRefCountPolicy        > MFUncountedApplicationStartScreenPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecApplicationStartScreenPtr : 
    public PointerSField<ApplicationStartScreen *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecApplicationStartScreenPtr : 
    public PointerSField<ApplicationStartScreen *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakApplicationStartScreenPtr :
    public PointerSField<ApplicationStartScreen *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedApplicationStartScreenPtr :
    public PointerSField<ApplicationStartScreen *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecApplicationStartScreenPtr :
    public PointerMField<ApplicationStartScreen *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecApplicationStartScreenPtr :
    public PointerMField<ApplicationStartScreen *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakApplicationStartScreenPtr :
    public PointerMField<ApplicationStartScreen *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedApplicationStartScreenPtr :
    public PointerMField<ApplicationStartScreen *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEAPPLICATIONSTARTSCREENFIELDS_H_ */
