/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KEMAINWINDOWFIELDS_H_
#define _KEMAINWINDOWFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class MainWindow;

OSG_GEN_CONTAINERPTR(MainWindow);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<MainWindow *> :
    public FieldTraitsFCPtrBase<MainWindow *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<MainWindow *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFMainWindowPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFMainWindowPtr"; }
};

template<> inline
const Char8 *FieldTraits<MainWindow *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecMainWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<MainWindow *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecMainWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<MainWindow *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakMainWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<MainWindow *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdMainWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<MainWindow *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecMainWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<MainWindow *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecMainWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<MainWindow *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakMainWindowPtr"; 
}

template<> inline
const Char8 *FieldTraits<MainWindow *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdMainWindowPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<MainWindow *,
                      RecordedRefCountPolicy  > SFRecMainWindowPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<MainWindow *,
                      UnrecordedRefCountPolicy> SFUnrecMainWindowPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<MainWindow *,
                      WeakRefCountPolicy      > SFWeakMainWindowPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<MainWindow *,
                      NoRefCountPolicy        > SFUncountedMainWindowPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<MainWindow *,
                      RecordedRefCountPolicy  > MFRecMainWindowPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<MainWindow *,
                      UnrecordedRefCountPolicy> MFUnrecMainWindowPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<MainWindow *,
                      WeakRefCountPolicy      > MFWeakMainWindowPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<MainWindow *,
                      NoRefCountPolicy        > MFUncountedMainWindowPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecMainWindowPtr : 
    public PointerSField<MainWindow *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecMainWindowPtr : 
    public PointerSField<MainWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakMainWindowPtr :
    public PointerSField<MainWindow *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedMainWindowPtr :
    public PointerSField<MainWindow *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecMainWindowPtr :
    public PointerMField<MainWindow *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecMainWindowPtr :
    public PointerMField<MainWindow *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakMainWindowPtr :
    public PointerMField<MainWindow *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedMainWindowPtr :
    public PointerMField<MainWindow *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KEMAINWINDOWFIELDS_H_ */
