/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *                                                                           *
 *   contact: djkabala@gmail.com                                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class ApplicationBuilder!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#define KE_COMPILEAPPLICATIONBUILDERINST

#include <stdlib.h>
#include <stdio.h>

#include <OpenSG/OSGConfig.h>

#include "KEApplicationBuilderBase.h"
#include "KEApplicationBuilder.h"


OSG_BEGIN_NAMESPACE

const OSG::BitVector  ApplicationBuilderBase::EditingProjectFieldMask = 
    (TypeTraits<BitVector>::One << ApplicationBuilderBase::EditingProjectFieldId);

const OSG::BitVector ApplicationBuilderBase::MTInfluenceMask = 
    (Inherited::MTInfluenceMask) | 
    (static_cast<BitVector>(0x0) << Inherited::NextFieldId); 


// Field descriptions

/*! \var ProjectPtr      ApplicationBuilderBase::_sfEditingProject
    
*/

//! ApplicationBuilder description

FieldDescription *ApplicationBuilderBase::_desc[] = 
{
    new FieldDescription(SFProjectPtr::getClassType(), 
                     "EditingProject", 
                     EditingProjectFieldId, EditingProjectFieldMask,
                     false,
                     reinterpret_cast<FieldAccessMethod>(&ApplicationBuilderBase::editSFEditingProject))
};


FieldContainerType ApplicationBuilderBase::_type(
    "ApplicationBuilder",
    "ApplicationMode",
    NULL,
    reinterpret_cast<PrototypeCreateF>(&ApplicationBuilderBase::createEmpty),
    ApplicationBuilder::initMethod,
    _desc,
    sizeof(_desc));

//OSG_FIELD_CONTAINER_DEF(ApplicationBuilderBase, ApplicationBuilderPtr)

/*------------------------------ get -----------------------------------*/

FieldContainerType &ApplicationBuilderBase::getType(void) 
{
    return _type; 
} 

const FieldContainerType &ApplicationBuilderBase::getType(void) const 
{
    return _type;
} 


FieldContainerPtr ApplicationBuilderBase::shallowCopy(void) const 
{ 
    ApplicationBuilderPtr returnValue; 

    newPtr(returnValue, dynamic_cast<const ApplicationBuilder *>(this)); 

    return returnValue; 
}

UInt32 ApplicationBuilderBase::getContainerSize(void) const 
{ 
    return sizeof(ApplicationBuilder); 
}


#if !defined(OSG_FIXED_MFIELDSYNC)
void ApplicationBuilderBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField)
{
    this->executeSyncImpl(static_cast<ApplicationBuilderBase *>(&other),
                          whichField);
}
#else
void ApplicationBuilderBase::executeSync(      FieldContainer &other,
                                    const BitVector      &whichField,                                    const SyncInfo       &sInfo     )
{
    this->executeSyncImpl((ApplicationBuilderBase *) &other, whichField, sInfo);
}
void ApplicationBuilderBase::execBeginEdit(const BitVector &whichField, 
                                            UInt32     uiAspect,
                                            UInt32     uiContainerSize) 
{
    this->execBeginEditImpl(whichField, uiAspect, uiContainerSize);
}

void ApplicationBuilderBase::onDestroyAspect(UInt32 uiId, UInt32 uiAspect)
{
    Inherited::onDestroyAspect(uiId, uiAspect);

}
#endif

/*------------------------- constructors ----------------------------------*/

#ifdef OSG_WIN32_ICL
#pragma warning (disable : 383)
#endif

ApplicationBuilderBase::ApplicationBuilderBase(void) :
    _sfEditingProject         (ProjectPtr(NullFC)), 
    Inherited() 
{
}

#ifdef OSG_WIN32_ICL
#pragma warning (default : 383)
#endif

ApplicationBuilderBase::ApplicationBuilderBase(const ApplicationBuilderBase &source) :
    _sfEditingProject         (source._sfEditingProject         ), 
    Inherited                 (source)
{
}

/*-------------------------- destructors ----------------------------------*/

ApplicationBuilderBase::~ApplicationBuilderBase(void)
{
}

/*------------------------------ access -----------------------------------*/

UInt32 ApplicationBuilderBase::getBinSize(const BitVector &whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);

    if(FieldBits::NoField != (EditingProjectFieldMask & whichField))
    {
        returnValue += _sfEditingProject.getBinSize();
    }


    return returnValue;
}

void ApplicationBuilderBase::copyToBin(      BinaryDataHandler &pMem,
                                  const BitVector         &whichField)
{
    Inherited::copyToBin(pMem, whichField);

    if(FieldBits::NoField != (EditingProjectFieldMask & whichField))
    {
        _sfEditingProject.copyToBin(pMem);
    }


}

void ApplicationBuilderBase::copyFromBin(      BinaryDataHandler &pMem,
                                    const BitVector    &whichField)
{
    Inherited::copyFromBin(pMem, whichField);

    if(FieldBits::NoField != (EditingProjectFieldMask & whichField))
    {
        _sfEditingProject.copyFromBin(pMem);
    }


}

#if !defined(OSG_FIXED_MFIELDSYNC)
void ApplicationBuilderBase::executeSyncImpl(      ApplicationBuilderBase *pOther,
                                        const BitVector         &whichField)
{

    Inherited::executeSyncImpl(pOther, whichField);

    if(FieldBits::NoField != (EditingProjectFieldMask & whichField))
        _sfEditingProject.syncWith(pOther->_sfEditingProject);


}
#else
void ApplicationBuilderBase::executeSyncImpl(      ApplicationBuilderBase *pOther,
                                        const BitVector         &whichField,
                                        const SyncInfo          &sInfo      )
{

    Inherited::executeSyncImpl(pOther, whichField, sInfo);

    if(FieldBits::NoField != (EditingProjectFieldMask & whichField))
        _sfEditingProject.syncWith(pOther->_sfEditingProject);



}

void ApplicationBuilderBase::execBeginEditImpl (const BitVector &whichField, 
                                                 UInt32     uiAspect,
                                                 UInt32     uiContainerSize)
{
    Inherited::execBeginEditImpl(whichField, uiAspect, uiContainerSize);

}
#endif



OSG_END_NAMESPACE

#include <OpenSG/OSGSFieldTypeDef.inl>
#include <OpenSG/OSGMFieldTypeDef.inl>

OSG_BEGIN_NAMESPACE

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldDataTraits<ApplicationBuilderPtr>::_type("ApplicationBuilderPtr", "ApplicationModePtr");
#endif

OSG_DLLEXPORT_SFIELD_DEF1(ApplicationBuilderPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);
OSG_DLLEXPORT_MFIELD_DEF1(ApplicationBuilderPtr, KE_KABALAENGINELIB_DLLTMPLMAPPING);

OSG_END_NAMESPACE

