/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 **     Do not change this file, changes should be done in the derived      **
 **     class SceneEditor!
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/

#include <cstdlib>
#include <cstdio>
#include <boost/assign/list_of.hpp>

#include <OpenSG/OSGConfig.h>




#include "KESceneEditorBase.h"
#include "KESceneEditor.h"

#include <boost/bind.hpp>

#ifdef WIN32 // turn off 'this' : used in base member initializer list warning
#pragma warning(disable:4355)
#endif

OSG_BEGIN_NAMESPACE

/***************************************************************************\
 *                            Description                                  *
\***************************************************************************/

/*! \class OSG::SceneEditor
    
 */

/***************************************************************************\
 *                        Field Documentation                              *
\***************************************************************************/


/***************************************************************************\
 *                      FieldType/FieldTrait Instantiation                 *
\***************************************************************************/

#if !defined(OSG_DO_DOC) || defined(OSG_DOC_DEV)
DataType FieldTraits<SceneEditor *>::_type("SceneEditorPtr", "EditorInterfacePtr");
#endif

OSG_FIELDTRAITS_GETTYPE(SceneEditor *)

OSG_EXPORT_PTR_SFIELD_FULL(PointerSField,
                           SceneEditor *,
                           0);

OSG_EXPORT_PTR_MFIELD_FULL(PointerMField,
                           SceneEditor *,
                           0);

/***************************************************************************\
 *                         Field Description                               *
\***************************************************************************/

void SceneEditorBase::classDescInserter(TypeObject &oType)
{
}


SceneEditorBase::TypeObject SceneEditorBase::_type(
    SceneEditorBase::getClassname(),
    Inherited::getClassname(),
    "NULL",
    0,
    reinterpret_cast<PrototypeCreateF>(&SceneEditorBase::createEmptyLocal),
    SceneEditor::initMethod,
    SceneEditor::exitMethod,
    reinterpret_cast<InitalInsertDescFunc>(&SceneEditor::classDescInserter),
    false,
    0,
    "<?xml version=\"1.0\"?>\n"
    "\n"
    "<FieldContainer\n"
    "\tname=\"SceneEditor\"\n"
    "\tparent=\"EditorInterface\"\n"
    "\tlibrary=\"KabalaEngine\"\n"
    "\tpointerfieldtypes=\"both\"\n"
    "\tstructure=\"concrete\"\n"
    "\tsystemcomponent=\"false\"\n"
    "\tparentsystemcomponent=\"false\"\n"
    "\tdecoratable=\"false\"\n"
    "\tuseLocalIncludes=\"false\"\n"
    "\tlibnamespace=\"KE\"\n"
    "    authors=\"David Kabala (djkabala@gmail.com)                             \"\n"
    ">\n"
    "</FieldContainer>\n",
    ""
    );

/*------------------------------ get -----------------------------------*/

FieldContainerType &SceneEditorBase::getType(void)
{
    return _type;
}

const FieldContainerType &SceneEditorBase::getType(void) const
{
    return _type;
}

UInt32 SceneEditorBase::getContainerSize(void) const
{
    return sizeof(SceneEditor);
}

/*------------------------- decorator get ------------------------------*/






/*------------------------------ access -----------------------------------*/

UInt32 SceneEditorBase::getBinSize(ConstFieldMaskArg whichField)
{
    UInt32 returnValue = Inherited::getBinSize(whichField);


    return returnValue;
}

void SceneEditorBase::copyToBin(BinaryDataHandler &pMem,
                                  ConstFieldMaskArg  whichField)
{
    Inherited::copyToBin(pMem, whichField);

}

void SceneEditorBase::copyFromBin(BinaryDataHandler &pMem,
                                    ConstFieldMaskArg  whichField)
{
    Inherited::copyFromBin(pMem, whichField);

}

//! create a new instance of the class
SceneEditorTransitPtr SceneEditorBase::createLocal(BitVector bFlags)
{
    SceneEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyLocal(bFlags);

        fc = dynamic_pointer_cast<SceneEditor>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class, copy the container flags
SceneEditorTransitPtr SceneEditorBase::createDependent(BitVector bFlags)
{
    SceneEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopyDependent(bFlags);

        fc = dynamic_pointer_cast<SceneEditor>(tmpPtr);
    }

    return fc;
}

//! create a new instance of the class
SceneEditorTransitPtr SceneEditorBase::create(void)
{
    SceneEditorTransitPtr fc;

    if(getClassType().getPrototype() != NULL)
    {
        FieldContainerTransitPtr tmpPtr =
            getClassType().getPrototype()-> shallowCopy();

        fc = dynamic_pointer_cast<SceneEditor>(tmpPtr);
    }

    return fc;
}

SceneEditor *SceneEditorBase::createEmptyLocal(BitVector bFlags)
{
    SceneEditor *returnValue;

    newPtr<SceneEditor>(returnValue, bFlags);

    returnValue->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

//! create an empty new instance of the class, do not copy the prototype
SceneEditor *SceneEditorBase::createEmpty(void)
{
    SceneEditor *returnValue;

    newPtr<SceneEditor>(returnValue, Thread::getCurrentLocalFlags());

    returnValue->_pFieldFlags->_bNamespaceMask &=
        ~Thread::getCurrentLocalFlags();

    return returnValue;
}


FieldContainerTransitPtr SceneEditorBase::shallowCopyLocal(
    BitVector bFlags) const
{
    SceneEditor *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const SceneEditor *>(this), bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~bFlags;

    return returnValue;
}

FieldContainerTransitPtr SceneEditorBase::shallowCopyDependent(
    BitVector bFlags) const
{
    SceneEditor *tmpPtr;

    newPtr(tmpPtr, dynamic_cast<const SceneEditor *>(this), ~bFlags);

    FieldContainerTransitPtr returnValue(tmpPtr);

    tmpPtr->_pFieldFlags->_bNamespaceMask = bFlags;

    return returnValue;
}

FieldContainerTransitPtr SceneEditorBase::shallowCopy(void) const
{
    SceneEditor *tmpPtr;

    newPtr(tmpPtr,
           dynamic_cast<const SceneEditor *>(this),
           Thread::getCurrentLocalFlags());

    tmpPtr->_pFieldFlags->_bNamespaceMask &= ~Thread::getCurrentLocalFlags();

    FieldContainerTransitPtr returnValue(tmpPtr);

    return returnValue;
}



/*------------------------- constructors ----------------------------------*/

SceneEditorBase::SceneEditorBase(void) :
    Inherited()
{
}

SceneEditorBase::SceneEditorBase(const SceneEditorBase &source) :
    Inherited(source)
{
}


/*-------------------------- destructors ----------------------------------*/

SceneEditorBase::~SceneEditorBase(void)
{
}




#ifdef OSG_MT_CPTR_ASPECT
void SceneEditorBase::execSyncV(      FieldContainer    &oFrom,
                                        ConstFieldMaskArg  whichField,
                                        AspectOffsetStore &oOffsets,
                                        ConstFieldMaskArg  syncMode,
                                  const UInt32             uiSyncInfo)
{
    SceneEditor *pThis = static_cast<SceneEditor *>(this);

    pThis->execSync(static_cast<SceneEditor *>(&oFrom),
                    whichField,
                    oOffsets,
                    syncMode,
                    uiSyncInfo);
}
#endif


#ifdef OSG_MT_CPTR_ASPECT
FieldContainer *SceneEditorBase::createAspectCopy(
    const FieldContainer *pRefAspect) const
{
    SceneEditor *returnValue;

    newAspectCopy(returnValue,
                  dynamic_cast<const SceneEditor *>(pRefAspect),
                  dynamic_cast<const SceneEditor *>(this));

    return returnValue;
}
#endif

void SceneEditorBase::resolveLinks(void)
{
    Inherited::resolveLinks();


}


OSG_END_NAMESPACE
