/*---------------------------------------------------------------------------*\
 *                             Kabala Engine                                 *
 *                                                                           *
 *               Copyright (C) 2009-2010 by David Kabala                     *
 *                                                                           *
 *   authors:  David Kabala (djkabala@gmail.com)                             *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                License                                    *
 *                                                                           *
 * This library is free software; you can redistribute it and/or modify it   *
 * under the terms of the GNU General Public License as published            *
 * by the Free Software Foundation, version 3.                               *
 *                                                                           *
 * This library is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of                *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU         *
 * Library General Public License for more details.                          *
 *                                                                           *
 * You should have received a copy of the GNU General Public                 *
 * License along with this library; if not, write to the Free Software       *
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.                 *
 *                                                                           *
\*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*\
 *                                Changes                                    *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
 *                                                                           *
\*---------------------------------------------------------------------------*/

/*****************************************************************************\
 *****************************************************************************
 **                                                                         **
 **                  This file is automatically generated.                  **
 **                                                                         **
 **          Any changes made to this file WILL be lost when it is          **
 **           regenerated, which can become necessary at any time.          **
 **                                                                         **
 *****************************************************************************
\*****************************************************************************/


#ifndef _KESCENEEDITORFIELDS_H_
#define _KESCENEEDITORFIELDS_H_
#ifdef __sgi
#pragma once
#endif

#include <OpenSG/OSGConfig.h>
#include "KEKabalaEngineDef.h"

#include <OpenSG/OSGFieldContainerFields.h>
#include <OpenSG/OSGPointerSField.h>
#include <OpenSG/OSGPointerMField.h>


OSG_BEGIN_NAMESPACE

class SceneEditor;

OSG_GEN_CONTAINERPTR(SceneEditor);

/*! \ingroup GrpKabalaEngineFieldTraits
    \ingroup GrpLibOSGKabalaEngine
 */
template <>
struct FieldTraits<SceneEditor *> :
    public FieldTraitsFCPtrBase<SceneEditor *>
{
  private:

    static DataType             _type;

  public:

    typedef FieldTraits<SceneEditor *>  Self;

    enum                        { Convertible = NotConvertible };

    static KE_KABALAENGINE_DLLMAPPING DataType &getType(void);

    template<typename RefCountPolicy> inline
    static const Char8    *getSName     (void);

//    static const char *getSName(void) { return "SFSceneEditorPtr"; }
    template<typename RefCountPolicy> inline
    static const Char8    *getMName     (void);

//    static const char *getMName(void) { return "MFSceneEditorPtr"; }
};

template<> inline
const Char8 *FieldTraits<SceneEditor *, 0>::getSName<RecordedRefCountPolicy>(void)
{
    return "SFRecSceneEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditor *, 0>::getSName<UnrecordedRefCountPolicy>(void)
{
    return "SFUnrecSceneEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditor *, 0>::getSName<WeakRefCountPolicy>(void)
{
    return "SFWeakSceneEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditor *, 0>::getSName<NoRefCountPolicy>(void)
{
    return "SFUnrefdSceneEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditor *, 0>::getMName<RecordedRefCountPolicy>(void)
{
    return "MFRecSceneEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditor *, 0>::getMName<UnrecordedRefCountPolicy>(void)
{
    return "MFUnrecSceneEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditor *, 0>::getMName<WeakRefCountPolicy>(void)
{
    return "MFWeakSceneEditorPtr"; 
}

template<> inline
const Char8 *FieldTraits<SceneEditor *, 0>::getMName<NoRefCountPolicy>(void)
{
    return "MFUnrefdSceneEditorPtr"; 
}


#ifndef DOXYGEN_SHOULD_SKIP_THIS
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEditor *,
                      RecordedRefCountPolicy  > SFRecSceneEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEditor *,
                      UnrecordedRefCountPolicy> SFUnrecSceneEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEditor *,
                      WeakRefCountPolicy      > SFWeakSceneEditorPtr;
/*! \ingroup GrpKabalaEngineFieldSFields */
typedef PointerSField<SceneEditor *,
                      NoRefCountPolicy        > SFUncountedSceneEditorPtr;


/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneEditor *,
                      RecordedRefCountPolicy  > MFRecSceneEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneEditor *,
                      UnrecordedRefCountPolicy> MFUnrecSceneEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneEditor *,
                      WeakRefCountPolicy      > MFWeakSceneEditorPtr;
/*! \ingroup GrpKabalaEngineFieldMFields */
typedef PointerMField<SceneEditor *,
                      NoRefCountPolicy        > MFUncountedSceneEditorPtr;




#else // these are the doxygen hacks

/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFRecSceneEditorPtr : 
    public PointerSField<SceneEditor *,
                         RecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUnrecSceneEditorPtr : 
    public PointerSField<SceneEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFWeakSceneEditorPtr :
    public PointerSField<SceneEditor *,
                         WeakRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldSFields \ingroup GrpLibOSGKabalaEngine */
struct SFUncountedSceneEditorPtr :
    public PointerSField<SceneEditor *,
                         NoRefCountPolicy> {};


/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFRecSceneEditorPtr :
    public PointerMField<SceneEditor *,
                         RecordedRefCountPolicy  > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUnrecSceneEditorPtr :
    public PointerMField<SceneEditor *,
                         UnrecordedRefCountPolicy> {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFWeakSceneEditorPtr :
    public PointerMField<SceneEditor *,
                         WeakRefCountPolicy      > {};
/*! \ingroup GrpKabalaEngineFieldMFields \ingroup GrpLibOSGKabalaEngine */
struct MFUncountedSceneEditorPtr :
    public PointerMField<SceneEditor *,
                         NoRefCountPolicy        > {};



#endif // these are the doxygen hacks

OSG_END_NAMESPACE

#endif /* _KESCENEEDITORFIELDS_H_ */
